ALTER SESSION SET STATISTICS_LEVEL = 'ALL';

SELECT /*+ GATHER_PLAN_STATISTICS SQL01 */
  FROM ... -- 튜닝할 쿼리 실행
;

SELECT S.SQL_ID
     , S.CHILD_NUMBER
     , X.*
  FROM V$SQL S
     , TABLE(DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID=>S.SQL_ID, CURSOR_CHILD_NO=>S.CHILD_NUMBER, FORMAT=>'TYPICAL')) X
 WHERE S.SQL_TEXT LIKE '%SQL01%'
   AND S.SQL_TEXT NOT LIKE '%V$SQL%';
   
   
/*
FORMAT : 
	- ALL     (ALLSTATS LAST) ????
	- BASIC
	- SERIAL
	- TYPICAL (DEFAULT)
	- ADAPTIVE
*/