ALTER SESSION SET STATISTICS_LEVEL = 'ALL';
SELECT /*+ NO_MONITOR */
       B.INST_ID
     , A.SQL_ID
     , B.MODULE
     , A.PLAN_HASH_VALUE
     , B.EXECUTIONS AS EXEC_CNT
     , ROUND(DECODE(B.EXECUTIONS, NULL, 0, 0, 0, (NVL(B.BUFFER_GETS, 0) / B.EXECUTIONS)), 0)    AS "BUFFER I/O"
     , ROUND(DECODE(B.EXECUTIONS, NULL, 0, 0, 0, (NVL(B.ROWS_PROCESSED, 0) / B.EXECUTIONS)), 0) AS "ROWS PER EXEC"
     , ROUND(DECODE(B.EXECUTIONS, NULL, 0, 0, 0, (NVL(B.ELAPSED_TIME, 0) / B.EXECUTIONS)), 0)   AS "ELAPSED"
     , A.ACCESS_PATH
     , SUBSTR(B.SQL_TEXT, 1, 50) AS SQL_TEXT
     , DBMS_LOB.SUBSTR(B.SQL_FULLTEXT, 3000, 1)    AS SQL_FULLTEXT1
     , DBMS_LOB.SUBSTR(B.SQL_FULLTEXT, 3000, 3001) AS SQL_FULLTEXT2
     , DBMS_LOB.SUBSTR(B.SQL_FULLTEXT, 3000, 6001) AS SQL_FULLTEXT3
     , 'SELECT SNAP_ID
             , SNAP_ID
             , NAME
             , DATATYPE_STRING
             , MIN(POSITION) POSITION
             , REPLACE(MAX(VALUE_STRING), ''NULL'', '''') BIND_VALUE
             , MAX(LAST_CAPTURED) LAST_CAPTURE
          FROM DBA_HIST_SQLBIND
         WHERE SQL_ID = ''' || A.SQL_ID || '''
         GROUP BY SQL_ID, NAME, DATATYPE_STRING, SNAP_ID
         ORDER BY SNAP_ID, POSITION;' || CHR(10) || CHR(10) AS BIND_DATA
	 , 'SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(''' || A.SQL_ID || ''', 0, ''ALLSTATS LAST ADVANCED''));' AS DBMS_XPLAN
--   , 'SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(SQL_ID=>''' || A.SQL_ID || ''', EVENT_DETAIL=>''YES'', TYPE=>''TEXT'', REPORT_LEVEL=>''ALL-SQL_TEXT'') FROM DUAL;' AS SQL_MONITOR
  FROM (
        SELECT ROW_NUMBER() OVER(PARTITION BY SQL_ID, CHILD_NUMBER, PLAN_HASH_VALUE ORDER BY SQL_ID, CHILD_NUMBER, PLAN_HASH_VALUE, ID, POSITION) RN1
             , SQL_ID, PLAN_HASH_VALUE, CHILD_NUMBER, OPERATION, OPTIONS
             , OBJECT_NAME || ' --> (Card:' || CARDINALITY || ' Bytes:' || BYTES || DECODE(PARTITION_START, NULL, '', ' PS/PE:') || PARTITION_START || DECODE(PARTITION_START, NULL, '', '/') || PARTITION_STOP || ')' || CHR(10)
             , || '    [O# ' || OPERATION || ' ' || OPTIONS || ']'
               || DECODE(ACCESS_PREDICATES, NULL, '', CHR(10) || '    [A# ' || ACCESS_PREDICATES || ']')
               || DECODE(FILTER_PREDICATES, NULL, '', CHR(10) || '    [F# ' || FILTER_PREDICATES || ']') AS ACCESS_PATH
          FROM GV$SQL_PLAN A
         WHERE 1=1
           AND OBJECT_OWNER = :OWNER
           AND (OBJECT_OWNER, OBJECT_NAME) IN (SELECT :OWNER OBJECT_OWNER, :TABLE_NAME OBJECT_NAME)
                                                 FROM DUAL
                                                UNION ALL
                                               SELECT OWNER OBJECT_OWNER, INDEX_NAME OBJECT_NAME
                                                 FROM DBA_INDEXES
                                                WHERE OWNER = :OWNER AND TABLE_NAME = :TABLE_NAME)
           AND ((OPERATION, OPTIONS) IN (('TABLE ACCESS', 'STORAGE FULL'))
            OR  (OPERATION, OPTIONS) IN (('INDEX', 'STORAGE FAST FULL SCAN')))
         ORDER BY SQL_ID, PLAN_HASH_VALUE, ID, POSITION
		) A
	    , GV$SQL B
 WHERE A.RN1 = 1
   AND A.SQL_ID = B.SQL_ID(+)
   AND A.CHILD_NUMBER = B.CHILD_NUMBER(+)
   AND A.PLAN_HASH_VALUE = B.PLAN_HASH_VALUE(+)
   AND MODULE NOT IN ('Orange for Oracle DBA ', '')
   AND B.EXECUTIONS > 1
   AND LAST_ACTIVE_TIME > SYSDATE-1
   AND ROUND(DECODE(B.EXECUTIONS, NULL, 0, 0, 0, (NVL(B.ELAPSED_TIME, 0) / B.EXECUTIONS)), 0) > 0.1
 ORDER BY ELAPSED DESC
;
	 