SELECT S.SQL_ID
     , S.CHILD_NUMBER
     , X.*
  FROM V$SQL S
     , TABLE(DBMS_XPLAN.DISPLAY_CURSOR(SQL_ID=>S.SQL_ID, CURSOR_CHILD_NO=>S.CHILD_NUMBER, FORMAT=>'TYPICAL')) X
 WHERE S.SQL_TEXT LIKE '%DISTINCT-QUERYTEXT%'
   AND S.SQL_TEXT NOT LIKE '%V$SQL%';
   
   
/*
FORMAT : 
	- ALL
	- BASIC
	- SERIAL
	- TYPICAL (DEFAULT)
	- ADAPTIVE
*/