SELECT INST_ID
     , SQL_ID
     , REPORT_ID
     , STATUS
     , USERNAME
     , MODULE
     , PROGRAM
--     , FIRST_REFRESH_TIME
     , LAST_REFRESH_TIME
     , REFRESH_COUNT
     , ROUND(ELAPSED_TIME / 1000 / 1000, 2) AS ELAPSED_SEC
     , ROUND(CPU_TIME / 1000 / 1000, 2) AS CPU_SEC
--     , ROUND(QUEUING_TIME / 1000 / 1000, 2) AS QUEUING_SEC
     , 'SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(SQL_ID=>''' || SQL_ID || ''', EVENT_DETAIL=>''YES'', TYPE=>''TEXT'', REPORT_LEVEL=>''ALL-SQL_TEXT'') FROM DUAL;' AS REPORT_QRY
  FROM GV$SQL_MONITOR
 WHERE USERNAME='PMPBMIG'
--   AND SQL_TEXT LIKE '%QUERY_IDENTIFIER%'
 ORDER BY LAST_REFRESH_TIME DESC
;