SET PAGESIZE 500
SET HEADING ON
COL OWNER FORMAT A10
COL TABLE_NAME FORMAT A35
COL TS_NAME FORMAT A15
SELECT A.OWNER
     , A.TABLE_NAME  
     , NVL(A.TABLESPACE_NAME, B.DEF_TABLESPACE_NAME) TS_NAME
  FROM DBA_TABLES A, DBA_PART_TABLES B
 WHERE A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER IN ('')
 ORDER BY 1,2
;


-- synonyms.sql
SET PAGESIZE 0
SET LINESIZE 200
COL DDL FORMAT A200
SELECT 'CREATE OR REPLACE SYNONYM [APP_USER].' || OBJECT_NAME || ' FOR .' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = '[APP_USER]')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM [BAT_USER].' || OBJECT_NAME || ' FOR .' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = '[BAT_USER]')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM .' || OBJECT_NAME || ' FOR .' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = '')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM [DEV_USER].' || OBJECT_NAME || ' FOR .' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = '[DEV_USER]')
 ORDER BY 1;

-- grants.sql
SET PAGESIZE 0
SET LINESIZE 200
COL GRANT_DDL FORMAT A200
SELECT 'GRANT ' || D.PRIVILEGE || ' ON ' || D.OWNER || '.' || D.TABLE_NAME || ' TO ' || D.GRANTEE ||';' AS GRANT_DDL
  FROM (
        SELECT -- 있어야 할 테이블 권한
               C.OWNER  
             , C.TABLE_NAME
             , C.GRANTEE
             , C.PRIVILEGE
          FROM (
                SELECT A.OWNER
                     , A.TABLE_NAME
                     , B.ROLE AS GRANTEE
                     , B.PRIVILEGE
                  FROM HKG_TABLE_INFO A
                     , HKG_MODULE_ROLE_PRIVS B
                 WHERE A.MODULE = B.MODULE
                 UNION ALL
                SELECT A.OWNER
                     , A.TABLE_NAME
                     , B.ROLE AS GRANTEE
                     , B.PRIVILEGE
                  FROM (SELECT * FROM HKG_TABLE_INFO WHERE EAI_YN = 'Y' ) A
                     , (SELECT * FROM HKG_MODULE_ROLE_PRIVS B WHERE MODULE = 'EAI') B
                ) C
		 WHERE C.TABLE_NAME NOT IN (
) 
         MINUS
        SELECT -- 현재 DB에 존재하는 권한
               UNISTR(A.OWNER) OWNER 
             , UNISTR(A.TABLE_NAME) TABLE_NAME
             , UNISTR(A.GRANTEE) GRANTEE
             , UNISTR(A.PRIVILEGE) PRIVILEGE
          FROM DBA_TAB_PRIVS A
         WHERE A.OWNER = ''
           AND A.GRANTEE <> ''
) D
;

-- grants2.sql
SET PAGESIZE 0
SET LINESIZE 200
COL GRANT_DDL FORMAT A200
SELECT CASE 
         WHEN OBJECT_TYPE IN ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION') THEN 
           'GRANT SELECT,INSERT,UPDATE,DELETE ON .' || OBJECT_NAME || ' TO [ROLE_DBA];' || CHR(13) || 
           'GRANT SELECT ON .' || OBJECT_NAME || ' TO [ROLE_SELECT];'
         WHEN OBJECT_TYPE IN ('VIEW', 'SEQUENCE') THEN
           'GRANT SELECT ON .' || OBJECT_NAME || ' TO [ROLE_SELECT], [ROLE_DBA];'
         WHEN OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE') THEN
           'GRANT EXECUTE ON .' || OBJECT_NAME || ' TO [APP_USER], [BAT_USER], [DEV_USER];'
         ELSE NULL
       END AS GRANT_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK', 'TRIGGER', 'TABLE', 'SYNONYM')
   AND OBJECT_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS)
 ORDER BY 1;

-- ################ 일반테이블 비교 ################
-- TABLES 비교
SET PAGESIZE 500
SET HEADING ON
SET LINESIZE 200
COL OWNER FORMAT A10
COL TABLE_NAME FORMAT A35
COL TS_NAME FORMAT A10
COL PARTITIONED FORMAT A11
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES@DB_LINK WHERE OWNER IN ('')
AND TABLE_NAME NOT IN (''
)
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('');

-- TAB_COLUMNS 비교 
SET PAGESIZE 500
SET HEADING ON
SET LINESIZE 200
COL OWNER FORMAT A19
COL TABLE_NAME FORMAT A36
COL COLUMN_NAME FORMAT A35
COL DATA_TYPE FORMAT A15
COL DATA_LENGTH FORMAT 999,999
COL DATA_PRECISION FORMAT 999,999
COL DATA_SCALE FORMAT 999,999
COL NULL FORMAT A1
COL COL_ID FORMAT 999
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS WHERE OWNER IN ('')
MINUS 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DB_LINK WHERE OWNER IN ('')
AND TABLE_NAME NOT IN ();