SET PAGESIZE 500
SET HEADING ON
COL OWNER FORMAT A10
COL TABLE_NAME FORMAT A35
COL TS_NAME FORMAT A15
SELECT A.OWNER
     , A.TABLE_NAME  
     , NVL(A.TABLESPACE_NAME, B.DEF_TABLESPACE_NAME) TS_NAME
  FROM DBA_TABLES A, DBA_PART_TABLES B
 WHERE A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
--   AND A.OWNER = 'PMPBADM'
   AND A.OWNER IN ('PMPBADM', 'EVNTADM', 'EVNTDEV', 'WFFWADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
 ORDER BY 1,2
;


-- synonyms.sql
SET PAGESIZE 0
SET LINESIZE 200
COL DDL FORMAT A200
SELECT 'CREATE OR REPLACE SYNONYM PMPBAPP.' || OBJECT_NAME || ' FOR PMPBADM.' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = 'PMPBADM'
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PMPBAPP')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM PMPBBAT.' || OBJECT_NAME || ' FOR PMPBADM.' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = 'PMPBADM'
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PMPBBAT')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM PMPBMIG.' || OBJECT_NAME || ' FOR PMPBADM.' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = 'PMPBADM'
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PMPBMIG')
 UNION 
SELECT 'CREATE OR REPLACE SYNONYM PMPBDEV.' || OBJECT_NAME || ' FOR PMPBADM.' || OBJECT_NAME || ';' AS SYNONYM_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = 'PMPBADM'
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK')
   AND OBJECT_NAME NOT IN (SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PMPBDEV')
 ORDER BY 1;

-- grants.sql
SET PAGESIZE 0
SET LINESIZE 200
COL GRANT_DDL FORMAT A200
SELECT 'GRANT ' || D.PRIVILEGE || ' ON ' || D.OWNER || '.' || D.TABLE_NAME || ' TO ' || D.GRANTEE ||';' AS GRANT_DDL
  FROM (
        SELECT -- 있어야 할 테이블 권한
               C.OWNER  
             , C.TABLE_NAME
             , C.GRANTEE
             , C.PRIVILEGE
          FROM (
                SELECT A.OWNER
                     , A.TABLE_NAME
                     , B.ROLE AS GRANTEE
                     , B.PRIVILEGE
                  FROM PMPBDBA.HKG_TABLE_INFO A
                     , PMPBDBA.HKG_MODULE_ROLE_PRIVS B
                 WHERE A.MODULE = B.MODULE
                 UNION ALL
                SELECT A.OWNER
                     , A.TABLE_NAME
                     , B.ROLE AS GRANTEE
                     , B.PRIVILEGE
                  FROM (SELECT * FROM PMPBDBA.HKG_TABLE_INFO WHERE EAI_YN = 'Y' ) A
                     , (SELECT * FROM PMPBDBA.HKG_MODULE_ROLE_PRIVS B WHERE MODULE = 'EAI') B
                ) C
		 WHERE C.TABLE_NAME NOT IN (
  'TB_PMPB_CABL_RTNG_ER_REC_H_I01'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I02'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I03'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I04'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I05'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I06'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I07'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I08'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I09'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM10'
, 'TB_PMPB_DROP_RECO_H_I01'
, 'TB_PMPB_DROP_RECO_H_I02'
, 'TB_PMPB_DROP_RECO_H_I03'
, 'TB_PMPB_DROP_RECO_H_I04'
, 'TB_PMPB_DROP_RECO_H_I05'
, 'TB_PMPB_DROP_RECO_H_I06'
, 'TB_PMPB_DROP_RECO_H_I07'
, 'TB_PMPB_DROP_RECO_H_I08'
, 'TB_PMPB_DROP_RECO_H_I09'
, 'TB_PMPB_DROP_RECO_H_I10'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I01'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I02'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I03'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I04'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I05'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I06'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I07'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I08'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I09'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM10'		 
) 
         MINUS
        SELECT -- 현재 DB에 존재하는 권한
               UNISTR(A.OWNER) OWNER 
             , UNISTR(A.TABLE_NAME) TABLE_NAME
             , UNISTR(A.GRANTEE) GRANTEE
             , UNISTR(A.PRIVILEGE) PRIVILEGE
          FROM DBA_TAB_PRIVS A
         WHERE A.OWNER = 'PMPBADM'
           AND A.GRANTEE < > 'PMPBMIG'
) D
;

-- grants2.sql
SET PAGESIZE 0
SET LINESIZE 200
COL GRANT_DDL FORMAT A200
SELECT CASE 
         WHEN OBJECT_TYPE IN ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION') THEN 
           'GRANT SELECT,INSERT,UPDATE,DELETE ON PMPBADM.' || OBJECT_NAME || ' TO RL_PMPB_ALL;' || CHR(13) || 
           'GRANT SELECT ON PMPBADM.' || OBJECT_NAME || ' TO RL_PMPB_SEL;'
         WHEN OBJECT_TYPE IN ('VIEW', 'SEQUENCE') THEN
           'GRANT SELECT ON PMPBADM.' || OBJECT_NAME || ' TO RL_PMPB_SEL, RL_PMPB_ALL;'
         WHEN OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE') THEN
           'GRANT EXECUTE ON PMPBADM.' || OBJECT_NAME || ' TO PMPBAPP, PMPBBAT, PMPBDEV;'
         ELSE NULL
       END AS GRANT_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = 'PMPBADM'
   AND OBJECT_TYPE NOT IN ('INDEX', 'INDEX PARTITION', 'INDEX SUBPARTITION', 'LOB', 'TYPE', 'DATABASE LINK', 'TRIGGER', 'TABLE', 'SYNONYM')
   AND OBJECT_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS)
 ORDER BY 1;

-- ################ 일반테이블 비교 ################
-- TABLES 비교
SET PAGESIZE 500
SET HEADING ON
SET LINESIZE 200
COL OWNER FORMAT A10
COL TABLE_NAME FORMAT A35
COL TS_NAME FORMAT A10
COL PARTITIONED FORMAT A11
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('PMPBADM')
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES@DL_DNUPB WHERE OWNER IN ('PMPBADM');
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES@DL_DNUPB WHERE OWNER IN ('PMPBADM')
AND TABLE_NAME NOT IN (
  'TB_PMPB_CABL_RTNG_ER_REC_H_I01'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I02'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I03'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I04'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I05'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I06'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I07'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I08'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I09'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM10'
, 'TB_PMPB_DROP_RECO_H_I01'
, 'TB_PMPB_DROP_RECO_H_I02'
, 'TB_PMPB_DROP_RECO_H_I03'
, 'TB_PMPB_DROP_RECO_H_I04'
, 'TB_PMPB_DROP_RECO_H_I05'
, 'TB_PMPB_DROP_RECO_H_I06'
, 'TB_PMPB_DROP_RECO_H_I07'
, 'TB_PMPB_DROP_RECO_H_I08'
, 'TB_PMPB_DROP_RECO_H_I09'
, 'TB_PMPB_DROP_RECO_H_I10'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I01'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I02'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I03'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I04'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I05'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I06'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I07'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I08'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I09'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CR10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_CRMV10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_DT10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_MV10'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM01'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM02'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM03'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM04'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM05'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM06'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM07'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM08'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM09'
, 'TB_PMPB_WRLS_RTNG_FFIL_D_I_RM10'
)
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME TS_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('PMPBADM');

-- TAB_COLUMNS 비교 
SET PAGESIZE 500
SET HEADING ON
SET LINESIZE 200
COL OWNER FORMAT A19
COL TABLE_NAME FORMAT A36
COL COLUMN_NAME FORMAT A35
COL DATA_TYPE FORMAT A15
COL DATA_LENGTH FORMAT 999,999
COL DATA_PRECISION FORMAT 999,999
COL DATA_SCALE FORMAT 999,999
COL NULL FORMAT A1
COL COL_ID FORMAT 999
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS WHERE OWNER IN ('PMPBADM')
MINUS 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DL_DNUPB WHERE OWNER IN ('PMPBADM');
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DL_DNUPB WHERE OWNER IN ('PMPBADM')
AND TABLE_NAME NOT IN (
  'TB_PMPB_CABL_RTNG_ER_REC_H_I01'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I02'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I03'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I04'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I05'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I06'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I07'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I08'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I09'
, 'TB_PMPB_CABL_RTNG_ER_REC_H_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CR10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_CRMV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_DT10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_MV10'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM01'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM02'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM03'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM04'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM05'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM06'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM07'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM08'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM09'
, 'TB_PMPB_CABL_RTNG_FFIL_D_I_RM10'
, 'TB_PMPB_DROP_RECO_H_I01'
, 'TB_PMPB_DROP_RECO_H_I02'
, 'TB_PMPB_DROP_RECO_H_I03'
, 'TB_PMPB_DROP_RECO_H_I04'
, 'TB_PMPB_DROP_RECO_H_I05'
, 'TB_PMPB_DROP_RECO_H_I06'
, 'TB_PMPB_DROP_RECO_H_I07'
, 'TB_PMPB_DROP_RECO_H_I08'
, 'TB_PMPB_DROP_RECO_H_I09'
, 'TB_PMPB_DROP_RECO_H_I10'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I01'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I02'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I03'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I04'
, 'TB_PMPB_WRLS_RTNG_ER_REC_H_I05'
, 'TB_PMPB_WRLS_RTNG_