SET PAGESIZE 500
SET HEADING ON
COL OWNER FORMAT A10
COL DB_LINK FORMAT A15
COL USERNAME FORMAT A15
COL HOST FORMAT A15
SELECT OWNER
     , DB_LINK
     , USERNAME
     , HOST
  FROM DBA_DB_LINKS
 ORDER BY 1,2
;