TTITLE "[DBName] Database|Oracle Data Files";

SET PAGESIZE 500
SET LINESIZE 200
SET HEADING ON

COL FILE_NAME FORMAT A40
COL FILE_ID FORMAT 999,999
COL TS_NAME FORMAT A15
COL GB FORMAT 999,999
COL BYTES FORMAT 999,999
COL AUTOEXTENSIBLE FORMAT A15
COL STATUS FORMAT A15
COL RESIZE_DDL FORMAT A80

SELECT FILE_NAME
     , FILE_ID
     , TABLESPACE_NAME AS TS_NAME
     , BYTES/1024/1024/1024 GB
--     , BYTES
     , STATUS
     , AUTOEXTENSIBLE
     , 'ALTER DATABASE DATAFILE ''' || FILE_NAME || ''' RESIZE 30G;' AS RESIZE_DDL
  FROM DBA_DATA_FILES
 UNION ALL
SELECT FILE_NAME
     , FILE_ID
     , TABLESPACE_NAME AS TS_NAME
     , BYTES/1024/1024/1024 GB
--     , BYTES
     , STATUS
     , AUTOEXTENSIBLE
     , 'ALTER DATABASE TEMPFILE ''' || FILE_NAME || ''' RESIZE 30G;' AS RESIZE_DDL
  FROM DBA_TEMP_FILES
 ORDER BY 3,2;

TTITLE OFF
