-- PARALLEL TABLE 확인
SELECT OWNER
     , TABLE_NAME
     , DEGREE
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' NOPARALLEL;' AS DDL
  FROM DBA_TABLES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND TRIM(DEGREE) <> '1';
 
-- PARALLEL INDEX 확인
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
     , DEGREE
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' NOPARALLEL;' AS DDL
  FROM DBA_INDEXES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND TRIM(DEGREE) <> '1'
   AND INDEX_TYPE <> 'LOB';