-- ################ COMMENTS 존재 여부 확인 ################
-- 코멘트 없는 테이블 확인
SELECT * FROM DBA_TAB_COMMENTS WHERE TABLE_TYPE < > 'VIEW' AND COMMENTS IS NULL AND OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM') ORDER BY 1,2;

-- 코멘트 없는 컬럼 확인
SELECT * FROM DBA_COL_COMMENTS WHERE COMMENTS IS NULL AND TABLE_NAME NOT IN (SELECT TABLE_NAME FROM DBA_TAB_COMMENTS WHERE TABLE_TYPE = 'VIEW') AND OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM') ORDER BY 1,2,3;


-- ################ INDEX 사용 가능 여부 확인 ################
-- UNUSABLE INDEX 확인
SELECT TABLE_OWNER
     , TABLE_NAME
     , TABLE_TYPE
     , INDEX_NAME
     , INDEX_TYPE
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' REBUILD;' AS REBUILD_DDL
  FROM DBA_INDEXES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND STATUS = 'UNUSABLE';
 
SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || PARTITION_NAME || ';' AS REBUILD_DDL
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND STATUS = 'UNUSABLE';
   
SELECT INDEX_OWNER
     , INDEX_NAME
     , SUBPARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || SUBPARTITION_NAME || ';' AS REBUILD_DDL
  FROM DBA_IND_SUBPARTITIONS
 WHERE INDEX_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND STATUS = 'UNUSABLE'; 

-- GLOBAL INDEX 생성 여부 확인
SELECT A.TABLE_NAME
     , B.INDEX_NAME
     , A.PARTITIONED TAB_PART_YN
     , B.PARTITIONED IDX_PART_YN
  FROM DBA_TABLES A
     , DBA_INDEXES B
 WHERE 1=1
   AND A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND A.PARTITIONED = 'YES'
   AND B.PARTITIONED = 'NO';
   
   
-- ################ LOGGING 확인 ################
-- NOLOGGING TABLE 확인
SELECT OWNER
     , TABLE_NAME
	 , LOGGING
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' LOGGING;' AS DDL
  FROM DBA_TABLES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES';

SELECT OWNER
     , TABLE_NAME
     , DEF_LOGGING
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' LOGGING;' AS DDL
  FROM DBA_PART_TABLES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND DEF_LOGGING < > 'YES' ;
 
SELECT TABLE_OWNER
     , TABLE_NAME
     , PARTITION_NAME
     , LOGGING
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MODIFY PARTITION ' || PARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_TAB_PARTITIONS
 WHERE TABLE_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;

SELECT TABLE_OWNER
     , TABLE_NAME
     , SUBPARTITION_NAME
     , LOGGING
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MODIFY SUBPARTITION ' || SUBPARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_TAB_SUBPARTITIONS
 WHERE TABLE_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;
 
-- NOLOGGING INDEX 확인
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' LOGGING;' AS DDL
  FROM DBA_INDEXES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES';

SELECT OWNER
     , INDEX_NAME
     , DEF_LOGGING
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' LOGGING;' AS DDL
  FROM DBA_PART_INDEXES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND DEF_LOGGING < > 'YES';

SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , LOGGING
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' MODIFY PARTITION ' || PARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;

SELECT INDEX_OWNER
     , INDEX_NAME
     , SUBPARTITION_NAME
     , LOGGING
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' MODIFY SUBPARTITION ' || SUBPARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_IND_SUBPARTITIONS
 WHERE INDEX_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;


-- ################ PARALLEL DEGREE 확인 ################
-- PARALLEL TABLE 확인
SELECT OWNER
     , TABLE_NAME
     , DEGREE
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' NOPARALLEL;' AS DDL
  FROM DBA_TABLES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND TRIM(DEGREE) < > '1';
 
-- PARALLEL INDEX 확인
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
     , DEGREE
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' NOPARALLEL;' AS DDL
  FROM DBA_INDEXES
 WHERE OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND TRIM(DEGREE) < > '1'
   AND INDEX_TYPE < > 'LOB';


-- ################ INDEX, CONSTRAINT NAME 일치 여부 확인 ################   
-- CONSTRAINT NAME 확인
SELECT A.OWNER
     , A.TABLE_NAME
     , C.CONSTRAINT_NAME
     , 'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' RENAME CONSTRAINT ' || C.CONSTRAINT_NAME || ' TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS CONSTRAINT_DDL
  FROM DBA_TABLES A
  , DBA_CONSTRAINTS C
 WHERE 1=1
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND C.CONSTRAINT_TYPE = 'P'
   AND C.CONSTRAINT_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
;

-- INDEX NAME 확인
SELECT A.OWNER
     , A.TABLE_NAME
     , B.INDEX_NAME
     , 'ALTER INDEX ' || A.OWNER || '.' || B.INDEX_NAME || ' RENAME TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS INDEX_DDL
  FROM DBA_TABLES A
  , DBA_INDEXES B
 WHERE 1=1
   AND A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND B.INDEX_NAME LIKE '%PK%'
   AND B.UNIQUENESS = 'UNIQUE'
   AND B.INDEX_NAME NOT LIKE '%STB%'
   AND B.INDEX_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
;
   

-- ################ PK CONSTRAINT 존재 여부 확인 ################
-- PK CONSTRAINT 없는 테이블 확인
SELECT A.OWNER
     , A.TABLE_NAME
     , A.PARTITIONED
     , NVL(A.TABLESPACE_NAME, B.DEF_TABLESPACE_NAME) TABLESPACE_NAME
  FROM DBA_TABLES A
     , DBA_PART_TABLES B
 WHERE A.OWNER = B.OWNER(+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER IN ('PMPBADM'
             , 'BLCP01ADM'
             , 'BLCP02ADM'
             , 'BLCP03ADM'
             , 'BLCP04ADM'
             , 'BLCP05ADM'
             , 'BLCP06ADM'
             , 'BLCP07ADM'
             , 'BLCP08ADM'
             , 'BLCP09ADM'
             , 'BLCP10ADM')
   AND NOT EXISTS (
           SELECT 1
             FROM DBA_CONSTRAINTS B
            WHERE B.OWNER = A.OWNER
              AND B.TABLE_NAME = A.TABLE_NAME
              AND B.CONSTRAINT_TYPE = 'P'
                  )
 ORDER BY A.OWNER, A.TABLE_NAME;
 
-- ################ PK 컬럼 NOT NULL 여부 확인 ################
SELECT B.OWNER
     , B.TABLE_NAME
     , B.CONSTRAINT_NAME
     , B.COLUMN_NAME
     , B.POSITION
     , C.NULLABLE
  FROM DBA_CONSTRAINTS A
     , DBA_CONS_COLUMNS B
     , DBA_TAB_COLUMNS C
 WHERE A.OWNER = B.OWNER
   AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
   AND A.CONSTRAINT_TYPE = 'P'
   AND B.OWNER = C.OWNER
   AND B.TABLE_NAME = C.TABLE_NAME
   AND B.COLUMN_NAME = C.COLUMN_NAME
   AND A.OWNER IN ('PMPBADM'
             , 'BLCP01ADM'
             , 'BLCP02ADM'
             , 'BLCP03ADM'
             , 'BLCP04ADM'
             , 'BLCP05ADM'
             , 'BLCP06ADM'
             , 'BLCP07ADM'
             , 'BLCP08ADM'
             , 'BLCP09ADM'
             , 'BLCP10ADM')
   AND C.NULLABLE = 'Y'
;