-- ################ 일반테이블 비교 ################
-- TABLES 비교
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, PARTITIONED FROM DBA_TABLES@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, PARTITIONED FROM DBA_TABLES@DB_LINK WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, PARTITIONED FROM DBA_TABLES WHERE OWNER IN ('');

-- TAB_COLUMNS 비교 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS WHERE OWNER IN ('')
MINUS 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS@DB_LINK WHERE OWNER IN ('')
MINUS 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID FROM DBA_TAB_COLUMNS WHERE OWNER IN ('');

-- INDEXES 비교
SELECT TABLE_OWNER, TABLE_NAME, TABLE_TYPE, OWNER, INDEX_NAME, INDEX_TYPE FROM DBA_INDEXES WHERE TABLE_OWNER IN ('') AND INDEX_TYPE < > 'LOB'
MINUS
SELECT TABLE_OWNER, TABLE_NAME, TABLE_TYPE, OWNER, INDEX_NAME, INDEX_TYPE FROM DBA_INDEXES@DB_LINK WHERE TABLE_OWNER IN ('') AND INDEX_TYPE < > 'LOB';
SELECT TABLE_OWNER, TABLE_NAME, TABLE_TYPE, OWNER, INDEX_NAME, INDEX_TYPE FROM DBA_INDEXES@DB_LINK WHERE TABLE_OWNER IN ('') AND INDEX_TYPE < > 'LOB'
MINUS
SELECT TABLE_OWNER, TABLE_NAME, TABLE_TYPE, OWNER, INDEX_NAME, INDEX_TYPE FROM DBA_INDEXES WHERE TABLE_OWNER IN ('') AND INDEX_TYPE < > 'LOB';

-- IND_COLUMNS 비교 
SELECT TABLE_OWNER, TABLE_NAME, INDEX_OWNER, INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, COLUMN_LENGTH, CHAR_LENGTH, DESCEND, COLLATED_COLUMN_ID FROM DBA_IND_COLUMNS WHERE TABLE_OWNER IN ('')
MINUS
SELECT TABLE_OWNER, TABLE_NAME, INDEX_OWNER, INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, COLUMN_LENGTH, CHAR_LENGTH, DESCEND, COLLATED_COLUMN_ID FROM DBA_IND_COLUMNS@DB_LINK WHERE TABLE_OWNER IN ('');
SELECT TABLE_OWNER, TABLE_NAME, INDEX_OWNER, INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, COLUMN_LENGTH, CHAR_LENGTH, DESCEND, COLLATED_COLUMN_ID FROM DBA_IND_COLUMNS@DB_LINK WHERE TABLE_OWNER IN ('')
MINUS
SELECT TABLE_OWNER, TABLE_NAME, INDEX_OWNER, INDEX_NAME, COLUMN_NAME, COLUMN_POSITION, COLUMN_LENGTH, CHAR_LENGTH, DESCEND, COLLATED_COLUMN_ID FROM DBA_IND_COLUMNS WHERE TABLE_OWNER IN ('');

-- CONSTRAINTS 비교 
SELECT OWNER, TABLE_NAME, CASE WHEN CONSTRAINT_TYPE='P' THEN CONSTRAINT_NAME ELSE NULL END AS CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION_VC, STATUS, DEFERRABLE, DEFERRED, VALIDATED, GENERATED FROM DBA_CONSTRAINTS WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, CASE WHEN CONSTRAINT_TYPE='P' THEN CONSTRAINT_NAME ELSE NULL END AS CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION_VC, STATUS, DEFERRABLE, DEFERRED, VALIDATED, GENERATED FROM DBA_CONSTRAINTS@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, CASE WHEN CONSTRAINT_TYPE='P' THEN CONSTRAINT_NAME ELSE NULL END AS CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION_VC, STATUS, DEFERRABLE, DEFERRED, VALIDATED, GENERATED FROM DBA_CONSTRAINTS@DB_LINK WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, CASE WHEN CONSTRAINT_TYPE='P' THEN CONSTRAINT_NAME ELSE NULL END AS CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION_VC, STATUS, DEFERRABLE, DEFERRED, VALIDATED, GENERATED FROM DBA_CONSTRAINTS WHERE OWNER IN ('');


-- ################ 파티션테이블 비교 ################
-- PART_TABLES 비교
SELECT OWNER, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, STATUS, DEF_TABLESPACE_NAME, DEF_PCT_FREE, DEF_PCT_USED FROM DBA_PART_TABLES WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, STATUS, DEF_TABLESPACE_NAME, DEF_PCT_FREE, DEF_PCT_USED FROM DBA_PART_TABLES@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, STATUS, DEF_TABLESPACE_NAME, DEF_PCT_FREE, DEF_PCT_USED FROM DBA_PART_TABLES@DB_LINK WHERE OWNER IN ('')
MINUS
SELECT OWNER, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, STATUS, DEF_TABLESPACE_NAME, DEF_PCT_FREE, DEF_PCT_USED FROM DBA_PART_TABLES WHERE OWNER IN ('');

-- TAB_PARTITIONS 비교
SELECT TABLE_OWNER, TABLE_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, HIGH_VALUE_LENGTH, PARTITION_POSITION, TABLESPACE_NAME, PCT_FREE, PCT_USED FROM DBA_TAB_PARTITIONS WHERE TABLE_OWNER IN ('')
MINUS
SELECT TABLE_OWNER, TABLE_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, HIGH_VALUE_LENGTH, PARTITION_POSITION, TABLESPACE_NAME, PCT_FREE, PCT_USED FROM DBA_TAB_PARTITIONS@DB_LINK WHERE TABLE_OWNER IN ('');
SELECT TABLE_OWNER, TABLE_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, HIGH_VALUE_LENGTH, PARTITION_POSITION, TABLESPACE_NAME, PCT_FREE, PCT_USED FROM DBA_TAB_PARTITIONS@DB_LINK WHERE TABLE_OWNER IN ('')
MINUS
SELECT TABLE_OWNER, TABLE_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, HIGH_VALUE_LENGTH, PARTITION_POSITION, TABLESPACE_NAME, PCT_FREE, PCT_USED FROM DBA_TAB_PARTITIONS WHERE TABLE_OWNER IN ('');

-- PART_INDEXES 비교
SELECT OWNER, INDEX_NAME, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, LOCALITY, ALIGNMENT, DEF_TABLESPACE_NAME, DEF_PCT_FREE FROM DBA_PART_INDEXES WHERE OWNER IN ('')
MINUS
SELECT OWNER, INDEX_NAME, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, LOCALITY, ALIGNMENT, DEF_TABLESPACE_NAME, DEF_PCT_FREE FROM DBA_PART_INDEXES@DB_LINK WHERE OWNER IN ('');
SELECT OWNER, INDEX_NAME, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, LOCALITY, ALIGNMENT, DEF_TABLESPACE_NAME, DEF_PCT_FREE FROM DBA_PART_INDEXES@DB_LINK WHERE OWNER IN ('')
MINUS
SELECT OWNER, INDEX_NAME, TABLE_NAME, PARTITIONING_TYPE, SUBPARTITIONING_TYPE, PARTITION_COUNT, DEF_SUBPARTITION_COUNT, PARTITIONING_KEY_COUNT, SUBPARTITIONING_KEY_COUNT, LOCALITY, ALIGNMENT, DEF_TABLESPACE_NAME, DEF_PCT_FREE FROM DBA_PART_INDEXES WHERE OWNER IN ('');

-- IND_PARTITIONS 비교
SELECT INDEX_OWNER, INDEX_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, PARTITION_POSITION, STATUS, TABLESPACE_NAME, PCT_FREE FROM DBA_IND_PARTITIONS WHERE INDEX_OWNER IN ('')
MINUS
SELECT INDEX_OWNER, INDEX_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, PARTITION_POSITION, STATUS, TABLESPACE_NAME, PCT_FREE FROM DBA_IND_PARTITIONS@DB_LINK WHERE INDEX_OWNER IN ('');
SELECT INDEX_OWNER, INDEX_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, PARTITION_POSITION, STATUS, TABLESPACE_NAME, PCT_FREE FROM DBA_IND_PARTITIONS@DB_LINK WHERE INDEX_OWNER IN ('')
MINUS
SELECT INDEX_OWNER, INDEX_NAME, COMPOSITE, PARTITION_NAME, SUBPARTITION_COUNT, PARTITION_POSITION, STATUS, TABLESPACE_NAME, PCT_FREE FROM DBA_IND_PARTITIONS WHERE INDEX_OWNER IN ('');

-- PART_KEY_COLUMNS 비교
SELECT * FROM DBA_PART_KEY_COLUMNS WHERE OWNER IN ('')
MINUS
SELECT * FROM DBA_PART_KEY_COLUMNS@DB_LINK WHERE OWNER IN ('');
SELECT * FROM DBA_PART_KEY_COLUMNS@DB_LINK WHERE OWNER IN ('')
MINUS
SELECT * FROM DBA_PART_KEY_COLUMNS WHERE OWNER IN ('');


-- ################ 코멘트 비교 ################
-- TAB_COMMENTS 비교
SELECT * FROM DBA_TAB_COMMENTS WHERE OWNER = ''
MINUS 
SELECT * FROM DBA_TAB_COMMENTS@DB_LINK WHERE OWNER = ''; 
SELECT * FROM DBA_TAB_COMMENTS@DB_LINK WHERE OWNER = ''
MINUS
SELECT * FROM DBA_TAB_COMMENTS WHERE OWNER = '';

-- COL_COMMENTS 비교
SELECT * FROM DBA_COL_COMMENTS WHERE OWNER = ''
MINUS
SELECT * FROM DBA_COL_COMMENTS@DB_LINK WHERE OWNER = '';
SELECT * FROM DBA_COL_COMMENTS@DB_LINK WHERE OWNER = ''
MINUS
SELECT * FROM DBA_COL_COMMENTS WHERE OWNER = '';


-- ################ 권한 및 동의어 비교 ################
-- TAB_PRIVS 비교
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTOR = ''
MINUS
SELECT * FROM DBA_TAB_PRIVS@DB_LINK WHERE GRANTOR = '';
SELECT * FROM DBA_TAB_PRIVS@DB_LINK WHERE GRANTOR = ''
MINUS
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTOR = '';

-- SYNONYMS 비교
SELECT * FROM DBA_SYNONYMS WHERE OWNER = ''
MINUS
SELECT * FROM DBA_SYNONYMS@DB_LINK WHERE OWNER = '';
SELECT * FROM DBA_SYNONYMS@DB_LINK WHERE OWNER = ''
MINUS
SELECT * FROM DBA_SYNONYMS WHERE OWNER = '';


-- ################ 기타 오브젝트 비교 ################
-- PROCEDURES 비교 (TRIGGER, FUNCTION 포함)
SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, SUBPROGRAM_ID, OVERLOAD, OBJECT_TYPE, AGGREGATE, PIPELINED, IMPLTYPEOWNER, IMPLTYPENAME, PARALLEL, INTERFACE, DETERMINISTIC, AUTHID, RESULT_CACHE, ORIGIN_CON_ID, POLYMORPHIC FROM DBA_PROCEDURES WHERE OWNER = ''
MINUS
SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, SUBPROGRAM_ID, OVERLOAD, OBJECT_TYPE, AGGREGATE, PIPELINED, IMPLTYPEOWNER, IMPLTYPENAME, PARALLEL, INTERFACE, DETERMINISTIC, AUTHID, RESULT_CACHE, ORIGIN_CON_ID, POLYMORPHIC FROM DBA_PROCEDURES@DB_LINK WHERE OWNER = '';
SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, SUBPROGRAM_ID, OVERLOAD, OBJECT_TYPE, AGGREGATE, PIPELINED, IMPLTYPEOWNER, IMPLTYPENAME, PARALLEL, INTERFACE, DETERMINISTIC, AUTHID, RESULT_CACHE, ORIGIN_CON_ID, POLYMORPHIC FROM DBA_PROCEDURES@DB_LINK WHERE OWNER = ''
MINUS
SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, SUBPROGRAM_ID, OVERLOAD, OBJECT_TYPE, AGGREGATE, PIPELINED, IMPLTYPEOWNER, IMPLTYPENAME, PARALLEL, INTERFACE, DETERMINISTIC, AUTHID, RESULT_CACHE, ORIGIN_CON_ID, POLYMORPHIC FROM DBA_PROCEDURES WHERE OWNER = '';

-- VIEWS 비교
SELECT OWNER, VIEW_NAME, TEXT_LENGTH, TEXT_VC, TYPE_TEXT_LENGTH, TYPE_TEXT, OID_TEXT_LENGTH, OID_TEXT, VIEW_TYPE_OWNER, VIEW_TYPE, SUPERVIEW_NAME, EDITIONING_VIEW, READ_ONLY, CONTAINER_DATA, BEQUEATH, ORIGIN_CON_ID, DEFAULT_COLLATION, CONTAINERS_DEFAULT, CONTAINER_MAP, EXTENDED_DATA_LINK, EXTENDED_DATA_LINK_MAP, HAS_SENSITIVE_COLUMN, ADMIT_NULL, PDB_LOCAL_ONLY FROM DBA_VIEWS WHERE OWNER = ''
MINUS
SELECT OWNER, VIEW_NAME, TEXT_LENGTH, TEXT_VC, TYPE_TEXT_LENGTH, TYPE_TEXT, OID_TEXT_LENGTH, OID_TEXT, VIEW_TYPE_OWNER, VIEW_TYPE, SUPERVIEW_NAME, EDITIONING_VIEW, READ_ONLY, CONTAINER_DATA, BEQUEATH, ORIGIN_CON_ID, DEFAULT_COLLATION, CONTAINERS_DEFAULT, CONTAINER_MAP, EXTENDED_DATA_LINK, EXTENDED_DATA_LINK_MAP, HAS_SENSITIVE_COLUMN, ADMIT_NULL, PDB_LOCAL_ONLY FROM DBA_VIEWS@DB_LINK WHERE OWNER = '';
SELECT OWNER, VIEW_NAME, TEXT_LENGTH, TEXT_VC, TYPE_TEXT_LENGTH, TYPE_TEXT, OID_TEXT_LENGTH, OID_TEXT, VIEW_TYPE_OWNER, VIEW_TYPE, SUPERVIEW_NAME, EDITIONING_VIEW, READ_ONLY, CONTAINER_DATA, BEQUEATH, ORIGIN_CON_ID, DEFAULT_COLLATION, CONTAINERS_DEFAULT, CONTAINER_MAP, EXTENDED_DATA_LINK, EXTENDED_DATA_LINK_MAP, HAS_SENSITIVE_COLUMN, ADMIT_NULL, PDB_LOCAL_ONLY FROM DBA_VIEWS@DB_LINK WHERE OWNER = ''
MINUS
SELECT OWNER, VIEW_NAME, TEXT_LENGTH, TEXT_VC, TYPE_TEXT_LENGTH, TYPE_TEXT, OID_TEXT_LENGTH, OID_TEXT, VIEW_TYPE_OWNER, VIEW_TYPE, SUPERVIEW_NAME, EDITIONING_VIEW, READ_ONLY, CONTAINER_DATA, BEQUEATH, ORIGIN_CON_ID, DEFAULT_COLLATION, CONTAINERS_DEFAULT, CONTAINER_MAP, EXTENDED_DATA_LINK, EXTENDED_DATA_LINK_MAP, HAS_SENSITIVE_COLUMN, ADMIT_NULL, PDB_LOCAL_ONLY FROM DBA_VIEWS WHERE OWNER = '';

-- SEQUENCES 비교
SELECT SEQUENCE_OWNER, SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER = ''
MINUS
SELECT SEQUENCE_OWNER, SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE FROM DBA_SEQUENCES@DB_LINK WHERE SEQUENCE_OWNER = '';
SELECT SEQUENCE_OWNER, SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE FROM DBA_SEQUENCES@DB_LINK WHERE SEQUENCE_OWNER = ''
MINUS
SELECT SEQUENCE_OWNER, SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, SCALE_FLAG, EXTEND_FLAG, SHARDED_FLAG, SESSION_FLAG, KEEP_VALUE FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER = '';