CREATE PROFILE PF_ULT LIMIT 
	COMPOSITE_LIMIT				UNLIMITED
	CONNECT_TIME				UNLIMITED
	CPU_PER_CALL				UNLIMITED
	CPU_PER_SESSION				UNLIMITED
	FAILED_LOGIN_ATTEMPTS		UNLIMITED
	IDLE_TIME					UNLIMITED
	INACTIVE_ACCOUNT_TIME		UNLIMITED
	LOGICAL_READS_PER_CALL		UNLIMITED
	LOGICAL_READS_PER_SESSION	UNLIMITED
	PASSWORD_GRACE_TIME			UNLIMITED
	PASSWORD_LIFE_TIME			UNLIMITED
	PASSWORD_LOCK_TIME			UNLIMITED
	PASSWORD_REUSE_MAX			UNLIMITED
	PASSWORD_REUSE_TIME			UNLIMITED
	PASSWORD_ROLLOVER_TIME		0
	PASSWORD_VERIFY_FUNCTION	NULL
	PRIVATE_SGA					UNLIMITED
	SESSIONS_PER_USER			UNLIMITED;

CREATE PROFILE PF_PWD LIMIT 
	COMPOSITE_LIMIT				UNLIMITED
	CONNECT_TIME				UNLIMITED
	CPU_PER_CALL				UNLIMITED
	CPU_PER_SESSION				UNLIMITED
	FAILED_LOGIN_ATTEMPTS		5
	IDLE_TIME					UNLIMITED
	INACTIVE_ACCOUNT_TIME		UNLIMITED
	LOGICAL_READS_PER_CALL		UNLIMITED
	LOGICAL_READS_PER_SESSION	UNLIMITED
	PASSWORD_GRACE_TIME			7
	PASSWORD_LIFE_TIME			90
	PASSWORD_LOCK_TIME			UNLIMITED
	PASSWORD_REUSE_MAX			3
	PASSWORD_REUSE_TIME			180
	PASSWORD_ROLLOVER_TIME		0
	PASSWORD_VERIFY_FUNCTION	NULL
	PRIVATE_SGA					UNLIMITED
	SESSIONS_PER_USER			UNLIMITED;

SELECT * FROM DBA_PROFILES WHERE PROFILE IN ('PF_ULT', 'PF_PWD');