SELECT A.OWNER
     , A.TABLE_NAME
     , C.CONSTRAINT_NAME
     , 'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' RENAME CONSTRAINT ' || C.CONSTRAINT_NAME || ' TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS CONSTRAINT_DDL
  FROM DBA_TABLES A
  , DBA_CONSTRAINTS C
 WHERE 1=1
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.TABLESPACE_NAME LIKE '%'
   AND A.OWNER IN ('')
   AND C.CONSTRAINT_TYPE = 'P'
   AND C.CONSTRAINT_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
;

SELECT A.OWNER
     , A.TABLE_NAME
     , B.INDEX_NAME
     , 'ALTER INDEX ' || A.OWNER || '.' || B.INDEX_NAME || ' RENAME TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS INDEX_DDL
  FROM DBA_TABLES A
  , DBA_INDEXES B
 WHERE 1=1
   AND A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER IN ('')
   AND A.TABLESPACE_NAME LIKE '%'
   AND B.INDEX_NAME LIKE '%PK%'
   AND B.UNIQUENESS = 'UNIQUE'
   AND B.INDEX_NAME NOT LIKE '%STB%'
   AND B.INDEX_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
;










SELECT * FROM 
(SELECT A.OWNER
     , A.TABLE_NAME
     , D.COMMENTS
     , C.CONSTRAINT_NAME
--     , 'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' RENAME CONSTRAINT ' || C.CONSTRAINT_NAME || ' TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS CONSTRAINT_DDL
  FROM DBA_TABLES A
  , DBA_CONSTRAINTS C
  , DBA_TAB_COMMENTS D
 WHERE 1=1
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.OWNER = D.OWNER (+)
   AND A.TABLE_NAME = D.TABLE_NAME (+)
   AND A.OWNER IN ('')
   AND C.CONSTRAINT_TYPE = 'P'
--   AND C.CONSTRAINT_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
   AND (C.CONSTRAINT_NAME NOT LIKE 'PK%'
   OR C.CONSTRAINT_NAME LIKE '%\_TB\_%' ESCAPE '\')
) X
FULL OUTER JOIN 
(
SELECT A.OWNER
     , A.TABLE_NAME
     , D.COMMENTS
     , B.INDEX_NAME
--     , 'ALTER INDEX ' || A.OWNER || '.' || B.INDEX_NAME || ' RENAME TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS INDEX_DDL
  FROM DBA_TABLES A
  , DBA_INDEXES B
  , DBA_TAB_COMMENTS D
 WHERE 1=1
   AND A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER = D.OWNER (+)
   AND A.TABLE_NAME = D.TABLE_NAME (+)
   AND A.OWNER IN ('')
   AND B.UNIQUENESS = 'UNIQUE'
--   AND B.INDEX_NAME < > REPLACE(A.TABLE_NAME, 'TB_', 'PK_')
   AND B.INDEX_NAME NOT LIKE 'SYS%'
   AND (B.INDEX_NAME NOT LIKE 'PK%'
   OR B.INDEX_NAME LIKE '%\_TB\_%' ESCAPE '\')
) Y
ON X.OWNER = Y.OWNER
AND X.TABLE_NAME = Y.TABLE_NAME
ORDER BY 1,2




-- PK조사
SELECT A.OWNER
     , A.TABLE_NAME
     , D.COMMENTS
     , C.CONSTRAINT_NAME
--     , 'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' RENAME CONSTRAINT ' || C.CONSTRAINT_NAME || ' TO ' || REPLACE(A.TABLE_NAME, 'TB_','PK_') || ';' AS CONSTRAINT_DDL
  FROM DBA_TABLES A
  , DBA_CONSTRAINTS C
  , DBA_TAB_COMMENTS D
 WHERE 1=1
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.OWNER = D.OWNER (+)
   AND A.TABLE_NAME = D.TABLE_NAME (+)
   AND A.OWNER IN ('')
   AND C.CONSTRAINT_TYPE = 'P'
   AND EXISTS ( SELECT 1 FROM DBA_INDEXES B WHERE C.OWNER = B.OWNER AND C.CONSTRAINT_NAME = B.INDEX_NAME)