-- ************************** WITHOUT PARTITION **************************
-- MOVE TABLE TABLESPACE
SELECT OWNER
     , TABLE_NAME
     , TABLESPACE_NAME
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' MOVE TABLESPACE TS_PMPB_D05;' AS MOVE_DDL
  FROM DBA_TABLES
 WHERE TABLESPACE_NAME = 'TS_ST_D01';

-- MOVE INDEX TABLESPACE
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
     , TABLESPACE_NAME
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' REBUILD TABLESPACE TS_PMPB_D05;' AS MOVE_DDL
  FROM DBA_INDEXES
 WHERE TABLESPACE_NAME = 'TS_ST_I01';


-- ************************** WITH PARTITION **************************
-- MODIFY DEFAULT TABLESPACE OF PARTITIONED TABLE
SELECT OWNER
     , TABLE_NAME
     , DEF_TABLESPACE_NAME
     , 'ALTER TABLE  ' || OWNER || '.' || TABLE_NAME || ' MODIFY DEFAULT ATTRIBUTES TABLESPACE TS_PMPB_DP01;' AS DDL
  FROM DBA_PART_TABLES
 WHERE OWNER = 'PMPBADM'
   AND DEF_TABLESPACE_NAME = 'TS_PMPB_DP05';
 
-- MOVE TABLESPACE OF TABLE PARTITION
SELECT TABLE_OWNER
     , TABLE_NAME
     , PARTITION_NAME
     , TABLESPACE_NAME
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MOVE PARTITION ' || PARTITION_NAME || ' TABLESPACE TS_PMPB_DP01;' MOVE_DDL
  FROM DBA_TAB_PARTITIONS
 WHERE TABLE_OWNER = 'PMPBADM'
   AND TABLESPACE_NAME = 'TS_PMPB_DP05';

-- MOVE TABLESPACE OF TABLE SUBPARTITION
SELECT TABLE_OWNER
     , TABLE_NAME
     , SUBPARTITION_NAME
     , TABLESPACE_NAME
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MOVE PARTITION ' || SUBPARTITION_NAME || ' TABLESPACE TS_PMPB_DP01;' MOVE_DDL
  FROM DBA_TAB_SUBPARTITIONS
 WHERE TABLE_OWNER = 'PMPBADM'
   AND TABLESPACE_NAME = 'TS_PMPB_DP05';
 
-- MODIFY DEFAULT TABLESPACE OF PARTITIONED INDEX
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
	 , DEF_TABLESPACE_NAME
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' MODIFY DEFAULT ATTRIBUTES TABLESPACE TS_PMPB_IP05;' AS DDL
  FROM DBA_PART_INDEXES
 WHERE DEF_TABLESPACE_NAME = 'TS_ST_IP01';
 
-- MOVE TABLESPACE OF INDEX PARTITION
SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || PARTITION_NAME || ' TABLESPACE TS_PMPB_IP05;' AS MOVE_DDL
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER = 'PMPBADM'
   AND TABLESPACE_NAME = 'TS_ST_IP01';

-- MOVE TABLESPACE OF INDEX SUBPARTITION
SELECT INDEX_OWNER
     , INDEX_NAME
     , SUBPARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || SUBPARTITION_NAME || ' TABLESPACE TS_PMPB_IP05;' AS MOVE_DDL
  FROM DBA_IND_SUBPARTITIONS
 WHERE INDEX_OWNER = 'PMPBADM'
   AND TABLESPACE_NAME = 'TS_ST_IP01';
   
   
-- ************************** CHECK FOR UNUSABLE INDEXES AFTER MOVING TABLESPACES OF TABLES **************************
SELECT TABLE_OWNER
     , TABLE_NAME
     , TABLE_TYPE
     , INDEX_NAME
     , INDEX_TYPE
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' REBUILD;' AS REBUILD_DDL
  FROM DBA_INDEXES
 WHERE OWNER = 'PMPBADM'
   AND STATUS = 'UNUSABLE';
 
SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || PARTITION_NAME || ';' AS REBUILD_DDL
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER = 'PMPBADM'
   AND STATUS = 'UNUSABLE';
   
SELECT INDEX_OWNER
     , INDEX_NAME
     , SUBPARTITION_NAME
     , TABLESPACE_NAME
     , STATUS
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' REBUILD PARTITION ' || SUBPARTITION_NAME || ';' AS REBUILD_DDL
  FROM DBA_IND_SUBPARTITIONS
 WHERE INDEX_OWNER = 'PMPBADM'
   AND STATUS = 'UNUSABLE'; 


-- ************************** LOB **************************
SELECT A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.TABLESPACE_NAME AS ASIS_TS
     , NVL(B.TABLESPACE_NAME, C.DEF_TABLESPACE_NAME) AS TOBE_TS
     , 'ALTER TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ' MOVE LOB (' || A.COLUMN_NAME || ') STORE AS (TABLESPACE ' || NVL(B.TABLESPACE_NAME, C.DEF_TABLESPACE_NAME) || ');' AS MOVE_DDL
  FROM DBA_LOBS A
     , DBA_TABLES B
     , DBA_PART_TABLES C
 WHERE A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.OWNER IN ('PMPBADM'
             , 'BLCP01ADM'
             , 'BLCP02ADM'
             , 'BLCP03ADM'
             , 'BLCP04ADM'
             , 'BLCP05ADM'
             , 'BLCP06ADM'
             , 'BLCP07ADM'
             , 'BLCP08ADM'
             , 'BLCP09ADM'
             , 'BLCP10ADM')
   AND A.TABLESPACE_NAME < > NVL(B.TABLESPACE_NAME, C.DEF_TABLESPACE_NAME)
;
















-- ************************** COMPARE TABLESPACES BETWEEN DNUPB, PNUPB **************************
-- 5. 파티션 인덱스 : DEFAULT TS 변경 DDL
SELECT A.OWNER
     , A.TABLE_NAME
     , A.INDEX_NAME
     , A.DEF_TABLESPACE_NAME DEV_TS
     , B.DEF_TABLESPACE_NAME PRD_TS
     , 'ALTER INDEX ' || A.OWNER || '.' || A.INDEX_NAME || ' MODIFY DEFAULT ATTRIBUTES TABLESPACE ' || B.DEF_TABLESPACE_NAME || ';' AS DDL
  FROM DBA_PART_INDEXES A, DBA_PART_INDEXES@DL_PNUPB1 B  
 WHERE 1=1
   AND A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.INDEX_NAME = B.INDEX_NAME
   AND A.OWNER = 'PMPBADM'
   AND A.DEF_TABLESPACE_NAME < > B.DEF_TABLESPACE_NAME;
   AND A.DEF_TABLESPACE_NAME = 'TS_ST_IP01';

-- 6. 파티션 인덱스 : move 파티션 TS DDL
SELECT A.INDEX_OWNER
     , A.INDEX_NAME
     , A.PARTITION_NAME
     , A.TABLESPACE_NAME DEV_TS
     , B.TABLESPACE_NAME PRD_TS
     , A.STATUS
     , 'ALTER INDEX ' || A.INDEX_OWNER || '.' || A.INDEX_NAME || ' REBUILD PARTITION ' || A.PARTITION_NAME || ' TABLESPACE ' || B.TABLESPACE_NAME || ';' AS MOVE_DDL
  FROM DBA_IND_PARTITIONS A, DBA_IND_PARTITIONS@DL_PNUPB1 B
 WHERE 1=1
   AND A.INDEX_OWNER = B.INDEX_OWNER
   AND A.INDEX_NAME = B.INDEX_NAME
   AND A.PARTITION_NAME = B.PARTITION_NAME
   AND A.INDEX_OWNER = 'PMPBADM'
   AND A.TABLESPACE_NAME < > B.TABLESPACE_NAME;