DROP TABLE HKG_TABLE_INFO PURGE;

CREATE TABLE HKG_TABLE_INFO (
    OWNER 					NVARCHAR2(10),
    TABLE_NAME 				NVARCHAR2(50),
    TABLESPACE_NAME 		NVARCHAR2(50),
    TABLE_COMMENT 			NVARCHAR2(200),
    PARTITIONING_TYPE 		NVARCHAR2(10),
    PART_KEY 				NVARCHAR2(50),
    MIN_PART 				NVARCHAR2(10),
    MAX_PART 				NVARCHAR2(10),
    SUBPARTITIONING_TYPE 	NVARCHAR2(10),
    SUBPARTITION_COUNT 		NVARCHAR2(5),
    MODULE 					NVARCHAR2(50),
    MODEL_TABLE_NAME 		NVARCHAR2(50),
    REMARKS 				NVARCHAR2(500),
    EAI_YN  				NVARCHAR2(1)
) TABLESPACE TS_PMPBDBA_D01;

CREATE UNIQUE INDEX PK_HKG_TABLE_INFO ON HKG_TABLE_INFO (OWNER, TABLE_NAME);
ALTER TABLE HKG_TABLE_INFO ADD CONSTRAINT PK_HKG_TABLE_INFO PRIMARY KEY (OWNER, TABLE_NAME) USING INDEX PK_HKG_TABLE_INFO;


CREATE OR REPLACE SYNONYM PMPBADM.HKG_TABLE_INFO FOR PMPBDBA.HKG_TABLE_INFO;
CREATE OR REPLACE SYNONYM PMPBMIG.HKG_TABLE_INFO FOR PMPBDBA.HKG_TABLE_INFO;