-- DNUPB에 생성
CREATE TABLE PMPBDBA.HKG_MODULE_TABLESPACES(
    MODULE NVARCHAR2(200),
    TAB_TS_NAME VARCHAR2(20),
    IDX_TS_NAME VARCHAR2(20),
    PART_TAB_TS_NAME VARCHAR2(20),
    PART_IDX_TS_NAME VARCHAR2(20)
)
;
CREATE OR REPLACE SYNONYM PMPBADM.HKG_MODULE_TABLESPACES FOR PMPBDBA.HKG_MODULE_TABLESPACES;

INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP01', 'TS_BLCP_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP02', 'TS_BLCP_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP03', 'TS_BLCP_IP03');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP04', 'TS_BLCP_IP04');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP05', 'TS_BLCP_IP05');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP06', 'TS_BLCP_IP06');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP07', 'TS_BLCP_IP07');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP08', 'TS_BLCP_IP08');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP09', 'TS_BLCP_IP09');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_BLCP_DP10', 'TS_BLCP_IP10');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_정산슬림화인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_IFCS_DP01', 'TS_IFCS_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_공통정보_SET', 'TS_PMPB_D02', 'TS_PMPB_I02', 'TS_PMPB_DP02', 'TS_PMPB_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_MVNO정산_SET', 'TS_PMPB_D03', 'TS_PMPB_I03', 'TS_PMPB_DP03', 'TS_PMPB_IP03');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_기준정보_SET', 'TS_PMPB_D02', 'TS_PMPB_I02', 'TS_PMPB_DP02', 'TS_PMPB_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_로밍정산_SET', 'TS_PMPB_D02', 'TS_PMPB_I02', 'TS_PMPB_DP02', 'TS_PMPB_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_무선접속료정산_SET', 'TS_PMPB_D03', 'TS_PMPB_I03', 'TS_PMPB_DP02', 'TS_PMPB_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_발신변작방지_SET', 'TS_PMPB_D01', 'TS_PMPB_I01', 'TS_PMPB_DP01', 'TS_PMPB_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_일반정산_SET', 'TS_PMPB_D04', 'TS_PMPB_I04', 'TS_PMPB_DP04', 'TS_PMPB_IP04');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('01_임차정산_SET', 'TS_PMPB_D03', 'TS_PMPB_I03', 'TS_PMPB_DP03', 'TS_PMPB_IP03');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('02_VOD정산_SET', 'TS_PMPB_D03', 'TS_PMPB_I03', 'TS_PMPB_DP02', 'TS_PMPB_IP02');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('02_유선국제정산_SET', 'TS_PMPB_D01', 'TS_PMPB_I01', 'TS_PMPB_DP01', 'TS_PMPB_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('02_유선접속료정산_SET', 'TS_PMPB_D01', 'TS_PMPB_I01', 'TS_PMPB_DP01', 'TS_PMPB_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('03_유선국내정산_SET', 'TS_PMPB_D01', 'TS_PMPB_I01', 'TS_PMPB_DP01', 'TS_PMPB_IP01');
INSERT INTO PMPBDBA.HKG_MODULE_TABLESPACES (MODULE, TAB_TS_NAME, IDX_TS_NAME, PART_TAB_TS_NAME, PART_IDX_TS_NAME) VALUES ('02_정산가상단인터페이스_SET', 'TS_IFCS_D01', 'TS_IFCS_I01', 'TS_IFCS_DP01', 'TS_IFCS_IP01');
COMMIT;

SELECT * FROM PMPBDBA.HKG_MODULE_TABLESPACES;





-- PNUPB, TNUPB에서 SYNONYM 생성
CREATE OR REPLACE SYNONYM PMPBADM.HKG_MODULE_TABLESPACES FOR PMPBDBA.HKG_MODULE_TABLESPACES@DL_DNUPB;
CREATE OR REPLACE SYNONYM PMPBDBA.HKG_MODULE_TABLESPACES FOR PMPBDBA.HKG_MODULE_TABLESPACES@DL_DNUPB;