DROP TABLE PMPBDBA.HKG_MODULE_ROLE_PRIVS PURGE;
CREATE TABLE PMPBDBA.HKG_MODULE_ROLE_PRIVS (
    MODULE                  NVARCHAR2(50),
    "ROLE"        			NVARCHAR2(20),
    PRIVILEGE               NVARCHAR2(10)
)
TABLESPACE TS_PMPBDBA_D01;


CREATE OR REPLACE SYNONYM PMPBADM.HKG_MODULE_ROLE_PRIVS
FOR PMPBDBA.HKG_MODULE_ROLE_PRIVS;

CREATE OR REPLACE SYNONYM PMPBMIG.HKG_MODULE_ROLE_PRIVS
FOR PMPBDBA.HKG_MODULE_ROLE_PRIVS;


INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_EVNT_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_EVNT_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_EVNT_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_EVNT_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_EVNT_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_정산슬림화인터페이스_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_공통정보_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_공통정보_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_공통정보_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_공통정보_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_공통정보_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_MVNO정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_MVNO정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_MVNO정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_MVNO정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_MVNO정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_기준정보_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_기준정보_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_기준정보_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_기준정보_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_기준정보_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_로밍정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_로밍정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_로밍정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_로밍정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_로밍정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_무선접속료정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_무선접속료정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_무선접속료정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_무선접속료정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_무선접속료정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_발신변작방지_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_발신변작방지_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_발신변작방지_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_발신변작방지_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_발신변작방지_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_일반정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_일반정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_일반정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_일반정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_일반정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_임차정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_임차정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_임차정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_임차정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('01_임차정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_VOD정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_VOD정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_VOD정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_VOD정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_VOD정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선국제정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선국제정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선국제정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선국제정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선국제정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선접속료정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선접속료정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선접속료정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선접속료정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_유선접속료정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('03_유선국내정산_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('03_유선국내정산_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('03_유선국내정산_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('03_유선국내정산_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('03_유선국내정산_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_정산가상단인터페이스_SET', 'RL_PMPB_ALL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_정산가상단인터페이스_SET', 'RL_PMPB_ALL', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_정산가상단인터페이스_SET', 'RL_PMPB_ALL', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_정산가상단인터페이스_SET', 'RL_PMPB_ALL', 'DELETE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('02_정산가상단인터페이스_SET', 'RL_PMPB_SEL', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('EAI', 'RL_PMPB_EAI', 'SELECT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('EAI', 'RL_PMPB_EAI', 'INSERT');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('EAI', 'RL_PMPB_EAI', 'UPDATE');
INSERT INTO PMPBDBA.HKG_MODULE_ROLE_PRIVS(MODULE, ROLE, PRIVILEGE) VALUES ('EAI', 'RL_PMPB_EAI', 'DELETE');
COMMIT;





SELECT * FROM HKG_MODULE_ROLE_PRIVS;