SELECT B.OWNER
     , B.TABLE_NAME
     , B.COLUMN_NAME
     , A.CONSTRAINT_NAME
     , A.CONSTRAINT_TYPE
     , B.POSITION
     , A.SEARCH_CONDITION
     , A.SEARCH_CONDITION_VC
     , A.STATUS
     -- A.INVALID
     , A.VALIDATED
     , A.GENERATED
     --, A.DEFERRABLE
     --, A.DEFERRED
     , A.LAST_CHANGE
     , A.INDEX_OWNER
     , A.INDEX_NAME
     , A.*
  FROM DBA_CONSTRAINTS A
     , DBA_CONS_COLUMNS B
 WHERE A.OWNER = B.OWNER 
   AND A.TABLE_NAME = B.TABLE_NAME
   AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
   AND A.OWNER IN ('POP_ADM')
   AND A.TABLE_NAME NOT LIKE 'DR$%'
 ORDER BY B.TABLE_NAME, B.POSITION
;