SELECT A.OWNER
     , A.TABLE_NAME
     , NVL(A.TABLESPACE_NAME, B.DEF_TABLESPACE_NAME) AS TABLESPACE_NAME
     , C.COMMENTS
     , B.PARTITIONING_TYPE
     , E.PART_KEY
     , D.MIN_PART
     , D.MAX_PART
     , B.SUBPARTITIONING_TYPE
     , D.SUBPART_COUNT
  FROM DBA_TABLES A
     , DBA_PART_TABLES B
     , DBA_TAB_COMMENTS C
     , (SELECT TABLE_OWNER
	         , TABLE_NAME
	         , MIN(PARTITION_NAME) AS MIN_PART
	         , MAX(PARTITION_NAME) AS MAX_PART
			 , MAX(SUBPARTITION_COUNT) AS SUBPART_COUNT
	      FROM DBA_TAB_PARTITIONS
		 WHERE OWNER IN ('')
		 GROUP BY TABLE_OWNER, TABLE_NAME) D
     , (SELECT OWNER
             , NAME
             , LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY COLUMN_POSITION) AS PART_KEY
          FROM DBA_PART_KEY_COLUMNS
         WHERE OWNER IN ('')
           AND OBJECT_TYPE = 'TABLE'
         GROUP BY OWNER, NAME) E
 WHERE A.OWNER = B.OWNER (+)
   AND A.TABLE_NAME = B.TABLE_NAME (+)
   AND A.OWNER = C.OWNER (+)
   AND A.TABLE_NAME = C.TABLE_NAME (+)
   AND A.OWNER = D.TABLE_OWNER (+)
   AND A.TABLE_NAME = D.TABLE_NAME (+)
   AND A.OWNER = E.OWNER (+)
   AND A.TABLE_NAME = E.NAME (+)
   AND A.OWNER IN ('')
 ORDER BY A.OWNER, A.TABLE_NAME;