-- 테이블사이즈 조회(LOB포함)
SELECT OWNER
     , TABLE_NAME
     , ROUND(SUM(TOT_SIZE_MB)) TOT_SIZE_MB
     , ROUND(SUM(TB_SIZE_MB)) TB_SIZE_MB
     , ROUND(SUM(IND_SIZE_MB)) IND_SIZE_MB
     , ROUND(SUM(LOB_SIZE_MB)) LOB_SIZE_MB 
  FROM (SELECT A.OWNER
             , B.TABLE_NAME
             , SUM(BYTES)/1024/1024 TOT_SIZE_MB
             , SUM(BYTES)/1024/1024 TB_SIZE_MB
             , 0 IND_SIZE_MB
             , 0 LOB_SIZE_MB  
          FROM DBA_SEGMENTS A,
               (SELECT OWNER, TABLE_NAME FROM DBA_TABLES WHERE OWNER = 'META_ADM') B
         WHERE A.OWNER = B.OWNER
           AND A.SEGMENT_NAME = B.TABLE_NAME
         GROUP BY A.OWNER, B.TABLE_NAME
         UNION ALL
        SELECT A.OWNER
             , B.TABLE_NAME
             , SUM(BYTES)/1024/1024 TOT_SIZE_MB
             , 0
             , 0
             , SUM(BYTES)/1024/1024 LOB_SIZE_MB 
          FROM DBA_SEGMENTS A,
               (SELECT OWNER, SEGMENT_NAME, TABLE_NAME FROM DBA_LOBS WHERE OWNER = 'META_ADM') B
         WHERE A.OWNER = B.OWNER
           AND A.SEGMENT_NAME = B.SEGMENT_NAME
         GROUP BY A.OWNER, B.TABLE_NAME
         UNION ALL
        SELECT A.OWNER
		     , B.TABLE_NAME
			 , SUM(BYTES)/1024/1024 TOT_SIZE_MB
			 , 0
			 , SUM(BYTES)/1024/1024 TB_IND_SIZE_MB
			 , 0
          FROM DBA_SEGMENTS A, 
               (SELECT OWNER, INDEX_NAME, TABLE_NAME FROM DBA_INDEXES WHERE OWNER = 'META_ADM') B
         WHERE A.OWNER = B.OWNER
           AND A.SEGMENT_NAME = B.INDEX_NAME
         GROUP BY A.OWNER, B.TABLE_NAME)
 GROUP BY OWNER, TABLE_NAME
 ORDER BY 1, 2;