TTITLE "[DBname] Database|Oracle Jobs"

SET LINESIZE 250
SET PAGESIZE 1000
SET HEADING ON

COL JOB          FORMAT 99999
COL LOG_USER     FORMAT A12
COL PRIV_USER    FORMAT A12
COL SCHEMA_USER  FORMAT A12
COL LAST_DATE    FORMAT A19
COL LAST_SEC     FORMAT 99999999
COL THIS_DATE    FORMAT A19
COL THIS_SEC     FORMAT 99999999
COL NEXT_DATE    FORMAT A19
COL NEXT_SEC     FORMAT 99999999
COL TOTAL_TIME   FORMAT 99999999
COL BROKEN       FORMAT A6
COL INTERVAL     FORMAT A19
COL FAILURES     FORMAT 99999
COL WHAT         FORMAT A30
COL NLS_ENV      FORMAT A30
COL MISC_ENV     FORMAT A30
COL INSTANCE     FORMAT 99

SELECT JOB
     , LOG_USER
     , PRIV_USER
     , SCHEMA_USER
     , TO_CHAR(LAST_DATE,'YYYY/MM/DD HH24:MM:SS') LAST_DATE
     , LAST_SEC
     , TO_CHAR(THIS_DATE,'YYYY/MM/DD HH24:MM:SS') THIS_DATE
     , THIS_SEC
     , TO_CHAR(NEXT_DATE,'YYYY/MM/DD HH24:MM:SS') NEXT_DATE
     , NEXT_SEC
     , TOTAL_TIME
     , BROKEN
     , INTERVAL
     , FAILURES
     , WHAT
     , NLS_ENV
     , MISC_ENV
     , INSTANCE
  FROM DBA_JOBS;
  
TTITLE OFF