TTITLE "[DBname] Database|Oracle Scheduler Jobs"

SET LINESIZE 250
SET PAGESIZE 1000
SET HEADING ON

COL OWNER          FORMAT A10
COL JOB_NAME     FORMAT A30
COL ENABLED    FORMAT A6
COL AUTO_DROP  FORMAT A5 HEADING AUTO|DROP
COL RESTART_RECO    FORMAT A7 HEADING RESTART|ON_RECO
COL RESTART_FAIL     FORMAT A7 HEADING RESTART|ON_FAIL
COL PROGRAM_NAME    FORMAT A30
COL JOB_STYLE     FORMAT A9
COL JOB_CREATOR    FORMAT A11
COL PROGRAM_OWNER     FORMAT A10
COL PROGRAM_NAME   FORMAT A30
COL SCHEDULE_OWNER       FORMAT A10
COL SCHEDULE_NAME     FORMAT A30
COL SCHEDULE_TYPE     FORMAT A13
COL START_DATE         FORMAT A19
COL REPEAT_INTERVAL      FORMAT A40
COL JOB_TYPE     FORMAT A16
COL JOB_ACTION     FORMAT A60

SELECT OWNER
     , JOB_NAME
     , ENABLED
--     , AUTO_DROP
--     , RESTART_ON_RECOVERY AS RESTART_RECO
--     , RESTART_ON_FAILURE AS RESTART_FAIL
     , JOB_STYLE
     , JOB_CREATOR
--     , PROGRAM_OWNER
     , PROGRAM_NAME
--     , SCHEDULE_OWNER
--     , SCHEDULE_NAME
--     , SCHEDULE_TYPE
     , TO_CHAR(START_DATE,'YYYY/MM/DD HH24:MM:SS') START_DATE
     , SUBSTR(REPEAT_INTERVAL,1,40) AS REPEAT_INTERVAL
     , JOB_TYPE
     , SUBSTR(JOB_ACTION, 1, 60) AS JOB_ACTION
  FROM DBA_SCHEDULER_JOBS;

TTITLE OFF