TTITLE "[DBname] Database|Oracle Instance Status"

SET LINESIZE 200
SET PAGESIZE 500
SET HEADING ON
COL INST_ID FORMAT 999
COL HOST_NAME FORMAT A15
COL INST_NAME FORMAT A10
COL STARTUP_TIME FORMAT A19
COL INST_STATUS FORMAT A12
COL PARALLEL FORMAT A10
COL ARCHIVER FORMAT A10
COL LOG_SWITCH_WAIT FORMAT A15
COL LOGINS FORMAT A10
COL SHUTDOWN_PENDING FORMAT A16
COL DB_STATUS FORMAT A10
COL DB_ROLE FORMAT A10
COL INST_ROLE FORMAT A16
COL ACTIVE_STATE FORMAT A12

SELECT HOST_NAME
     , INST_ID
     , INSTANCE_NAME AS INST_NAME
     , STATUS AS INST_STATUS
     , TO_CHAR(STARTUP_TIME,'YYYY/MM/DD HH24:MM:SS') STARTUP_TIME
     , ARCHIVER
     , LOG_SWITCH_WAIT
     , PARALLEL
     , LOGINS
     , SHUTDOWN_PENDING
     , INSTANCE_ROLE AS INST_ROLE
     , ACTIVE_STATE
     , DATABASE_STATUS AS DB_STATUS
     , DATABASE_TYPE AS DB_TYPE
  FROM GV$INSTANCE;
  
TTITLE OFF