SELECT TRUNC (FIRST_TIME) "DATE"
     , TO_CHAR (TRUNC (FIRST_TIME),'DY') "DAY"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 0, 1)) "00"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 1, 1)) "01"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 2, 1)) "02"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 3, 1)) "03"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 4, 1)) "04"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 5, 1)) "05"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 6, 1)) "06"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 7, 1)) "07"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 8, 1)) "08"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 9, 1)) "09"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 10, 1)) "10"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 11, 1)) "11"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 12, 1)) "12"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 13, 1)) "13"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 14, 1)) "14"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 15, 1)) "15"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 16, 1)) "16"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 17, 1)) "17"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 18, 1)) "18"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 19, 1)) "19"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 20, 1)) "20"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 21, 1)) "21"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 22, 1)) "22"
     , SUM (DECODE (TO_NUMBER (TO_CHAR (FIRST_TIME, 'HH24')), 23, 1)) "23"
  FROM V$LOG_HISTORY
 WHERE TRUNC (FIRST_TIME) >= (TRUNC(SYSDATE) - 14) -- LAST X DAYS. 0 = TODAY ONLY. 1 = TODAY AND YESTERDAY
 GROUP BY TRUNC (FIRST_TIME)
 ORDER BY TRUNC (FIRST_TIME) DESC;



/* log switch frequency by month
col c1 format a10 heading "Month"
col c2 format a25 heading "Archive Date"
col c3 format 999 heading "Switches"
compute AVG of C on A
compute AVG of C on REPORT
break on A skip 1 on REPORT skip 1
SELECT TO_CHAR(TRUNC(FIRST_TIME), 'MONTH') C1
     , TO_CHAR(TRUNC(FIRST_TIME), 'DAY : DD-MON-YYYY') C2
     , COUNT(*) C3
  FROM V$LOG_HISTORY
 WHERE TRUNC(FIRST_TIME) > LAST_DAY(SYSDATE-100) +1
 GROUP BY TRUNC(FIRST_TIME)
 ORDER BY TRUNC(FIRST_TIME);
*/