SELECT FILE_NAME
     , FILE_ID
     , TABLESPACE_NAME
     , BYTES/1024/1024/1024 GB
     , BYTES
     , STATUS
     , AUTOEXTENSIBLE
     , 'ALTER DATABASE DATAFILE ''' || FILE_NAME || ''' RESIZE 30G;' AS RESIZE_DDL
  FROM DBA_DATA_FILES
-- WHERE BYTES = 10737418240
 ORDER BY 3,2;