SELECT A.LOG_ID
     , TO_CHAR(A.LOG_DATE, 'YYYY/MM/DD HH24:MM:SS') LOG_DATE
     , A.OWNER
     , A.JOB_NAME
     , A.JOB_SUBNAME
     , A.JOB_CLASS
     , A.OPERATION
     , A.STATUS
     , B.INSTANCE_ID AS INST#
     , TO_CHAR(B.REQ_START_DATE, 'YYYY/MM/DD HH24:MM:SS') AS REQ_START_DATE
     , TO_CHAR(B.ACTUAL_START_DATE, 'YYYY/MM/DD HH24:MM:SS') AS ACTUAL_START_DATE
     , B.CPU_USED
     , B.SESSION_ID
     , B.ERROR#
     , B.ERRORS
     , SUBSTR(A.ADDITIONAL_INFO, 1, 60) AS ADDITIONAL_INFO
     , SUBSTR(B.OUTPUT, 1, 40) AS OUTPUT
  FROM DBA_SCHEDULER_JOB_LOG A
     , DBA_SCHEDULER_JOB_RUN_DETAILS B
 WHERE A.LOG_ID = B.LOG_ID (+)
 ORDER BY A.LOG_DATE DESC
;
 
 
 
/*
SELECT * FROM DBA_SCHEDULER_JOB_CLASSES;

SELECT * FROM DBA_SCHEDULER_JOBS;
SELECT * FROM DBA_SCHEDULER_JOB_ARGS;
SELECT * FROM DBA_SCHEDULER_RUNNING_JOBS;
SELECT * FROM DBA_SCHEDULER_JOB_LOG;
SELECT * FROM DBA_SCHEDULER_JOB_RUN_DETAILS;

SELECT * FROM DBA_SCHEDULER_PROGRAMS;
SELECT * FROM DBA_SCHEDULER_PROGRAM_ARGS;

SELECT * FROM DBA_SCHEDULER_SCHEDULES;

SELECT * FROM DBA_SCHEDULER_WINDOWS;
SELECT * FROM DBA_SCHEDULER_WINDOW_DETAILS;
SELECT * FROM DBA_SCHEDULER_WINDOW_LOG;

SELECT * FROM DBA_SCHEDULER_CREDENTIALS;
*/