TTITLE "[DBName] Database|Oracle Recompilable Objects"

SET PAGESIZE 1000
SET LINESIZE 250
SET HEADING ON
COL OBJECT_TYPE FORMAT A12
COL OWNER FORMAT A10
COL OBJECT_NAME FORMAT A35
COL STATUS FORMAT A8
COL CREATED FORMAT A19
COL LAST_DDL_TIME FORMAT A19
COL COMPILE_DDL FORMAT A80

SELECT OBJECT_TYPE
     , OWNER
     , OBJECT_NAME
     , STATUS
     , TO_CHAR(CREATED, 'YYYY/MM/DD HH24:MM:SS') CREATED
     , TO_CHAR(LAST_DDL_TIME, 'YYYY/MM/DD HH24:MM:SS') LAST_DDL_TIME
     , 'ALTER ' || OBJECT_TYPE || ' ' || OWNER || '.' || OBJECT_NAME || ' COMPILE;' AS COMPILE_DDL
  FROM DBA_OBJECTS
 WHERE OWNER = ''
   AND OBJECT_TYPE IN ( 'FUNCTION'
                      , 'PACKAGE'
                      , 'PACKAGE_BODY'
                      , 'PROCEDURE'
                      , 'TRIGGER'
                      , 'VIEW' )
   AND STATUS = 'INVALID'
 ORDER BY OBJECT_TYPE, OWNER, OBJECT_NAME
;