SET PAGESIZE 500
SET HEADING ON
COL USERNAME FORMAT A25
COL DEFAULT_TS FORMAT A15
COL TEMP_TS FORMAT A15
COL LOCAL_TMP_TS FORMAT A15
COL ACCOUNT_STATUS FORMAT A16
SELECT USERNAME
     , DEFAULT_TABLESPACE DEFAULT_TS
     , TEMPORARY_TABLESPACE TEMP_TS
     , LOCAL_TEMP_TABLESPACE LOCAL_TMP_TS
     , ACCOUNT_STATUS
  FROM DBA_USERS
-- WHERE ACCOUNT_STATUS = 'OPEN'
 ORDER BY ACCOUNT_STATUS, USERNAME;