TTITLE "[DBName] Database|Oracle Dependencies"

SET PAGESIZE 1000
SET LINESIZE 200
SET HEADING ON
COL OBJECT_TYPE FORMAT A12
COL OWNER FORMAT A10
COL OBJECT_NAME FORMAT A35
COL STATUS FORMAT A8
COL CREATED FORMAT A19
COL LAST_DDL_TIME FORMAT A19
COL REF_TYPE FORMAT A12
COL REF_OWNER FORMAT A10
COL REF_NAME FORMAT A35
COL REF_LINK_NAME FORMAT A10

SELECT A.OBJECT_TYPE
     , A.OWNER
     , A.OBJECT_NAME
     , A.STATUS
     , TO_CHAR(A.CREATED, 'YYYY/MM/DD HH24:MM:SS') CREATED
     , TO_CHAR(A.LAST_DDL_TIME, 'YYYY/MM/DD HH24:MM:SS') LAST_DDL_TIME
     , B.REFERENCED_OWNER AS REF_OWNER
     , B.REFERENCED_NAME AS REF_NAME
     , B.REFERENCED_TYPE AS REF_TYPE
     , B.REFERENCED_LINK_NAME AS REF_LINK_NAME
--     , B.DEPENDENCY_TYPE
  FROM DBA_OBJECTS A
     , DBA_DEPENDENCIES B
 WHERE A.OWNER = B.OWNER (+)
   AND A.OBJECT_NAME = B.NAME (+)
   AND A.OWNER = ''
   AND A.OBJECT_TYPE IN ( 'FUNCTION'
                        , 'PACKAGE'
                        , 'PACKAGE_BODY'
                        , 'PROCEDURE'
                        , 'TRIGGER'
                        , 'VIEW' )
   AND B.REFERENCED_OWNER NOT IN ('SYS', 'PUBLIC')
 ORDER BY A.OBJECT_TYPE, A.OWNER, A.OBJECT_NAME 
;