-- DBMS_STATS.GATHER_TABLE_STATS() 함수와 달리 ANALYZE TABLE 명령어는 일반 클라이언트 툴에서 실행 가능 
SELECT 'ANALYZE TABLE ' || OWNER || '.' || TABLE_NAME || ' COMPUTE STATISTICS;' AS GATHER_STATS
  FROM DBA_TABLES
 WHERE 1=1
   AND LAST_ANALYZED < SYSDATE-180
   AND OWNER IN ('');