-- NOLOGGING TABLE 확인
SELECT OWNER
     , TABLE_NAME
	 , LOGGING
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' LOGGING;' AS DDL
  FROM DBA_TABLES
 WHERE OWNER IN ('')
   AND LOGGING < > 'YES';

SELECT OWNER
     , TABLE_NAME
     , DEF_LOGGING
     , 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' LOGGING;' AS DDL
  FROM DBA_PART_TABLES
 WHERE OWNER IN ('')
   AND DEF_LOGGING < > 'YES' ;
 
SELECT TABLE_OWNER
     , TABLE_NAME
     , PARTITION_NAME
     , LOGGING
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MODIFY PARTITION ' || PARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_TAB_PARTITIONS
 WHERE TABLE_OWNER IN ('')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;

SELECT TABLE_OWNER
     , TABLE_NAME
     , SUBPARTITION_NAME
     , LOGGING
     , 'ALTER TABLE ' || TABLE_OWNER || '.' || TABLE_NAME || ' MODIFY SUBPARTITION ' || SUBPARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_TAB_SUBPARTITIONS
 WHERE TABLE_OWNER IN ('')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;
 
-- NOLOGGING INDEX 확인
SELECT OWNER
     , TABLE_NAME
     , INDEX_NAME
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' LOGGING;' AS DDL
  FROM DBA_INDEXES
 WHERE OWNER IN ('')
   AND LOGGING < > 'YES';

SELECT OWNER
     , INDEX_NAME
     , DEF_LOGGING
     , 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' LOGGING;' AS DDL
  FROM DBA_PART_INDEXES
 WHERE OWNER IN ('')
   AND DEF_LOGGING < > 'YES';

SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , LOGGING
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' MODIFY PARTITION ' || PARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER IN ('')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;

SELECT INDEX_OWNER
     , INDEX_NAME
     , SUBPARTITION_NAME
     , LOGGING
     , 'ALTER INDEX ' || INDEX_OWNER || '.' || INDEX_NAME || ' MODIFY SUBPARTITION ' || SUBPARTITION_NAME || ' LOGGING;' AS DDL
  FROM DBA_IND_SUBPARTITIONS
 WHERE INDEX_OWNER IN ('')
   AND LOGGING < > 'YES'
 ORDER BY 1,2,3;