ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION ENABLE PARALLEL DDL;
ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION SET WORKAREA_SIZE_POLICY=MANUAL;
ALTER SESSION SET SORT_AREA_SIZE=512000000;
ALTER SESSION SET SORT_AREA_RETAINED_SIZE=512000000;
ALTER SESSION SET HASH_AREA_SIZE=512000000;
ALTER SESSION SET HASH_MULTIBLOCK_IO_COUNT=128;
ALTER SESSION SET DB_FILE_MULTIBLOCK_READ_COUNT=128;
INSERT /*+APPEND PARALLEL(A 8) */ INTO OWNER.TABLE1 A 
SELECT /*+FULL(B) PARALLEL(B 8) */* FROM OWNER.TABLE2 B;
COMMIT;