DROP TABLE HKG_MODULE_ROLE_PRIVS PURGE;
CREATE TABLE HKG_MODULE_ROLE_PRIVS (
    MODULE                  NVARCHAR2(50),
    "ROLE"        			NVARCHAR2(20),
    PRIVILEGE               NVARCHAR2(10)
);



SELECT * FROM HKG_MODULE_ROLE_PRIVS;