-- DNUPB에 생성
CREATE TABLE HKG_MODULE_TABLESPACES(
    MODULE NVARCHAR2(200),
    TAB_TS_NAME VARCHAR2(20),
    IDX_TS_NAME VARCHAR2(20),
    PART_TAB_TS_NAME VARCHAR2(20),
    PART_IDX_TS_NAME VARCHAR2(20)
)
;

SELECT * FROM HKG_MODULE_TABLESPACES;
