SELECT FILE_NAME
     , FILE_ID
     , TABLESPACE_NAME AS TS_NAME
     , BYTES/1024/1024/1024 GB
--     , BYTES
     , STATUS
     , AUTOEXTENSIBLE
     , 'ALTER DATABASE DATAFILE ''' || FILE_NAME || ''' RESIZE 30G;' AS RESIZE_DDL
  FROM DBA_DATA_FILES
 UNION ALL
SELECT FILE_NAME
     , FILE_ID
     , TABLESPACE_NAME AS TS_NAME
     , BYTES/1024/1024/1024 GB
--     , BYTES
     , STATUS
     , AUTOEXTENSIBLE
     , 'ALTER DATABASE TEMPFILE ''' || FILE_NAME || ''' RESIZE 30G;' AS RESIZE_DDL
  FROM DBA_TEMP_FILES
 ORDER BY 3,2;