SELECT A.TABLESPACE_NAME TS_NAME
     , B.GB AS TOTAL_GB
     , ROUND(C.GB, 2) AS USED_GB
	 , TO_CHAR(ROUND(C.GB/B.GB, 4) * 100,'fm990D00','NLS_NUMERIC_CHARACTERS = ''.,''') || '%' USED_PCT
     , A.STATUS
     , B.AUTOEXTENSIBLE
     , A.EXTENT_MANAGEMENT AS EXT_MGMT
     , A.ALLOCATION_TYPE AS ALLOC_TYPE
     , A.MIN_EXTLEN/1024/1024 AS MIN_EXTEN_MB
     , CASE
           WHEN ROUND(C.GB/B.GB, 4) * 100 >= 90 THEN 'ALTER TABLESPACE ' || A.TABLESPACE_NAME || ' ADD DATAFILE ''+DATA'' SIZE 30G;'
           ELSE NULL
       END AS ADD_DATAFILE_DDL
  FROM DBA_TABLESPACES A
     , (SELECT TABLESPACE_NAME
             , SUM(BYTES/1024/1024/1024) AS GB
             , AUTOEXTENSIBLE
          FROM DBA_DATA_FILES
         GROUP BY TABLESPACE_NAME, AUTOEXTENSIBLE) B
     , (SELECT TABLESPACE_NAME
             , SUM(BYTES/1024/1024/1024) AS GB
          FROM DBA_SEGMENTS
         GROUP BY TABLESPACE_NAME) C
 WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME
   AND B.TABLESPACE_NAME = C.TABLESPACE_NAME
 ORDER BY A.TABLESPACE_NAME;