-- ************************ CORE, PORTAL, LGC, LGCNS, LGES ************************
-- SHOW GRANTS FOR 'root'@'%';
-- SHOW GRANTS FOR `cloudsqlsuperuser`@`%`;

-- 내 IP
CREATE USER 'root'@'10.65.60.10' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.60.10';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.60.10' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPAPP.* TO 'root'@'10.65.60.10' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPHRRT.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON INORG.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SAC.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FLYWAY.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.60.10' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.60.10`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.60.10';

-- 전진 책임님 IP
CREATE USER 'root'@'10.65.62.115' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.62.115';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPAPP.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPHRRT.* TO 'root'@'10.65.62.115'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON INORG.* TO 'root'@'10.65.62.115'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SAC.* TO 'root'@'10.65.62.115'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FLYWAY.* TO 'root'@'10.65.62.115'  WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.62.115' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.62.115`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.62.115';

-- 승환 선임님 IP
CREATE USER 'root'@'10.65.78.123' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.78.123';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPAPP.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPHRRT.* TO 'root'@'10.65.78.123'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON INORG.* TO 'root'@'10.65.78.123'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SAC.* TO 'root'@'10.65.78.123'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FLYWAY.* TO 'root'@'10.65.78.123'  WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.78.123' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.78.123`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.78.123';

-- DB접근제어 솔루션 IP
CREATE USER 'root'@'10.1.121.193' IDENTIFIED BY 'SinglevmffotvhaHr!';
-- DROP USER 'root'@'10.1.121.193';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPAPP.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPHRRT.* TO 'root'@'10.1.121.193'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON INORG.* TO 'root'@'10.1.121.193'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SAC.* TO 'root'@'10.1.121.193'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FLYWAY.* TO 'root'@'10.1.121.193'  WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.1.121.193' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.1.121.193`;
GRANT SELECT ON mysql.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.1.121.193';

-- CMS 모니터링 서버 IP
CREATE USER 'root'@'10.2.183.12' IDENTIFIED BY 'SinglevmffotvhaHr!';
-- DROP USER 'root'@'10.2.183.12';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPAPP.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ERPHRRT.* TO 'root'@'10.2.183.12'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON INORG.* TO 'root'@'10.2.183.12'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SAC.* TO 'root'@'10.2.183.12'  WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON FLYWAY.* TO 'root'@'10.2.183.12'  WITH GRANT OPTION;
-- GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.2.183.12' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.2.183.12`;
GRANT SELECT ON mysql.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.2.183.12';

DROP USER 'root'@'%';

/*
	select * from mysql.user where user = 'root';
	select * from mysql.db;
	select * from mysql.tables_priv where user = 'root';
	select * from mysql.columns_priv where user = 'root';
	select * from mysql.procs_priv where user = 'root';
	select * from mysql.global_grants where user = 'root';
*/



-- ************************ SPICEWARE ************************
-- 내 IP
CREATE USER 'root'@'10.65.60.10' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.60.10';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.60.10' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.60.10' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.60.10`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.60.10'  WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.60.10';

-- 전진 책임님 IP
CREATE USER 'root'@'10.65.62.115' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.62.115';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.62.115' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.62.115`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.62.115' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.62.115';

-- 승환 선임님 IP
CREATE USER 'root'@'10.65.78.123' IDENTIFIED BY 'SingleHrvmffotvha!';
-- DROP USER 'root'@'10.65.78.123';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.65.78.123' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.65.78.123`;
GRANT SELECT ON mysql.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.65.78.123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.65.78.123';

-- DB접근제어 솔루션 IP
CREATE USER 'root'@'10.1.121.193' IDENTIFIED BY 'SinglevmffotvhaHr!';
-- DROP USER 'root'@'10.1.121.193';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.1.121.193' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.1.121.193`;
GRANT SELECT ON mysql.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.1.121.193' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.1.121.193';

-- CMS 모니터링 서버 IP
CREATE USER 'root'@'10.2.183.12' IDENTIFIED BY 'SinglevmffotvhaHr!';
-- DROP USER 'root'@'10.2.183.12';
GRANT CREATE, ALTER, DROP, RELOAD, SHUTDOWN, PROCESS, EXECUTE, SHOW DATABASES, SHOW VIEW, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, CREATE TABLESPACE, DROP ROLE, ROLE_ADMIN, USAGE ON *.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON spiceware_business.* TO 'root'@'10.2.183.12' WITH GRANT OPTION; -- 이거는 spiceware 에서만 실행
GRANT `cloudsqlsuperuser`@`%` TO `root`@`10.2.183.12`;
GRANT SELECT ON mysql.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT SELECT ON sys.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON performance_schema.* TO 'root'@'10.2.183.12' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW GRANTS FOR 'root'@'10.2.183.12';

DROP USER 'root'@'%';