TTITLE "[DBname] Database|Oracle ASM Disk"

SET LINESIZE 200
SET PAGESIZE 500

COL GROUP_NAME  FORMAT A10
COL GROUP_NUMBER FORMAT 99 HEADING GROUP|NUMBER
COL HEADER_STATUS FORMAT A15 HEADING HEADER|STATUS
COL TOTAL_GB FORMAT 999,999
COL FREE_GB FORMAT 999,999
COL USED_GB FORMAT 999,999
COL USED_PCT FORMAT 999,999

SELECT G.NAME AS GROUP_NAME
     , G.GROUP_NUMBER
     , D.HEADER_STATUS
     , ROUND(SUM(D.TOTAL_MB/1024),2) AS TOTAL_GB
     , ROUND(SUM(D.FREE_MB/1024),2) AS FREE_GB
     , ROUND(SUM(D.TOTAL_MB/1024)-SUM(D.FREE_MB/1024),2) AS USED_GB
     , ROUND((SUM(D.TOTAL_MB)-SUM(D.FREE_MB)) / SUM(D.TOTAL_MB) * 100, 2) USED_PCT
  FROM V$ASM_DISK D
     , V$ASM_DISKGROUP G
 WHERE D.GROUP_NUMBER = G.GROUP_NUMBER (+)
   AND D.HEADER_STATUS = 'MEMBER'
 GROUP BY G.NAME, G.GROUP_NUMBER, D.HEADER_STATUS
 ORDER BY G.NAME;
 
TTITLE OFF