SELECT SEQUENCE#
     , FIRST_TIME
     , NEXT_TIME
     , COMPLETION_TIME
     , NAME
     , ARCHIVED
     , DELETED
     , STATUS
  FROM V$ARCHIVED_LOG
 ORDER BY SEQUENCE#;
 
 
 

-- ARCHIVED LOG 보관 주기 확인
SELECT THREAD#				-- 인스턴스 번호
     , MIN(COMPLETION_TIME)	-- 최소로그타임
	 , MAX(COMPLETION_TIME)	-- 
	 , COUNT(*)
  FROM V$ARCHIVED_LOG
 WHERE DELETED='NO'
 GROUP BY THREAD#;