SELECT schemaname
     , relname
     , seq_scan
     , seq_tup_read
     , idx_scan
     , idx_tup_fetch
     , n_tup_ins
     , n_tup_upd
     , n_tup_del
     , n_tup_hot_upd
     , n_live_tup
     , n_dead_tup
     , last_vacuum
     , last_autovacuum
     , last_analyze
     , last_autoanalyze
     , vacuum_count
     , autovacuum_count
     , analyze_count
     , autoanalyze_count
  FROM pg_stat_all_tables
 ORDER BY schemaname, relname;