ALTER SESSION ENABLE PARALLEL QUERY;
ALTER SESSION ENABLE PARALLEL DDL;
ALTER SESSION ENABLE PARALLEL DML;
ALTER SESSION SET WORKAREA_SIZE_POLICY=MANUAL;
ALTER SESSION SET SORT_AREA_SIZE=512000000;
ALTER SESSION SET SORT_AREA_RETAINED_SIZE=512000000;
ALTER SESSION SET HASH_AREA_SIZE=512000000;
ALTER SESSION SET HASH_MULTIBLOCK_IO_COUNT=128;
ALTER SESSION SET DB_FILE_MULTIBLOCK_READ_COUNT=128;


-- 테스트 결과 아래 CTAS와 SELECT-INSERT는 성능이 동일하다. (플랜에서 CREATE TABLE, INSERT문만 차이가 있음)
CREATE TABLE NEW_DUMMY TABLESPACE TS_DUMMY PARALLEL(DEGREE 8) NOLOGGING AS SELECT * FROM DUMMY A;
-- DROP TABLE NEW DUMMY PURGE;

CREATE TABLE NEW_DUMMY TABLESPACE TS_DUMMY NOLOGGING AS SELECT * FROM DUMMY WHERE 1=2;
INSERT /*+ APPEND PARALLEL(A 8) */ INTO NEW DUMMY A SELECT /*+ FULL(B) PARALLEL(B 8) */ * FROM DUMMY B;
COMMIT;

