/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE MIG_USER.PR_MIG_CREATE_INDEX
(
    V_TABLE_NAME        IN VARCHAR2,
    V_INDEX_NAME        IN VARCHAR2,
    V_CREATE_INDEX_SQL  IN VARCHAR2
)    
IS

  MIG_INDEX_RESULT   VARCHAR2(4000);
  
BEGIN  

    EXECUTE IMMEDIATE 'ALTER SESSION SET WORKAREA_SIZE_POLICY=MANUAL';
    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';
    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DDL';
    EXECUTE IMMEDIATE 'ALTER SESSION SET SORT_AREA_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET HASH_AREA_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET SORT_AREA_RETAINED_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET HASH_MULTIBLOCK_IO_COUNT=128';
    EXECUTE IMMEDIATE 'ALTER SESSION SET DB_FILE_MULTIBLOCK_READ_COUNT=128';

    --DBMS_OUTPUT.PUT_LINE('INSERT TABLE_NAME:'||V_TABLE_NAME);
    UPDATE MIG_USER.MSJ_MIG_INDEX_LOG 
      SET MIG_START_DT = SYSDATE 
     WHERE TABLE_NAME = V_TABLE_NAME 
       AND INDEX_NAME = V_INDEX_NAME
     ;
    
    COMMIT;
    --DBMS_OUTPUT.PUT_LINE('INDEX_SQL:'||V_CREATE_INDEX_SQL);
    EXECUTE IMMEDIATE V_CREATE_INDEX_SQL ;
    
    UPDATE MIG_USER.MSJ_MIG_INDEX_LOG 
       SET MIG_END_DT = SYSDATE 
         , JOB_RESULT = 'SUCCESS'
     WHERE TABLE_NAME = V_TABLE_NAME 
       AND INDEX_NAME = V_INDEX_NAME
     ;    
    COMMIT;
 --   EXECUTE IMMEDIATE 'ALTER INDEX PMPBADM.'||V_INDEX_NAME||' LOGGING NOPARALLEL;';
    
EXCEPTION
   WHEN OTHERS THEN
    MIG_INDEX_RESULT   :=  SQLERRM(SQLCODE) ;
    UPDATE MIG_USER.MSJ_MIG_INDEX_LOG SET JOB_RESULT='FAIL:'||MIG_INDEX_RESULT 
    WHERE TABLE_NAME = V_TABLE_NAME
     AND INDEX_NAME = V_INDEX_NAME;
    COMMIT;
END PR_MIG_CREATE_INDEX;
/