TTITLE "[DBname] Database|Oracle ASM Disk Summary"

SET LINESIZE 200
SET PAGESIZE 500

COL GROUP_NAME  FORMAT A10
COL GROUP_NUMBER FORMAT 99 HEADING GROUP|NUMBER
COL HEADER_STATUS FORMAT A15 HEADING HEADER|STATUS
COL TOTAL_GB FORMAT 999,999
COL FREE_GB FORMAT 999,999
COL USED_GB FORMAT 999,999
COL USED_PCT FORMAT 999,999

SELECT G.NAME AS GROUP_NAME
     , G.GROUP_NUMBER
     , D.HEADER_STATUS
     , ROUND(SUM(D.TOTAL_MB/1024),2) AS TOTAL_GB
     , ROUND(SUM(D.FREE_MB/1024),2) AS FREE_GB
     , ROUND(SUM(D.TOTAL_MB/1024)-SUM(D.FREE_MB/1024),2) AS USED_GB
     , ROUND((SUM(D.TOTAL_MB)-SUM(D.FREE_MB)) / SUM(D.TOTAL_MB) * 100, 2) USED_PCT
  FROM V$ASM_DISK D
     , V$ASM_DISKGROUP G
 WHERE D.GROUP_NUMBER = G.GROUP_NUMBER (+)
   AND D.HEADER_STATUS = 'MEMBER'
 GROUP BY G.NAME, G.GROUP_NUMBER, D.HEADER_STATUS
 ORDER BY G.NAME;
 
TTITLE OFF

TTITLE "[DBname] Database|Oracle ASM Disk"

COL GROUP_NAME  FORMAT A10
COL GROUP_NUMBER FORMAT 99 HEADING GROUP|NUMBER
COL DISK_NAME  FORMAT A20
COL HEADER_STATUS FORMAT A15 HEADING HEADER|STATUS
COL STATE FORMAT A10
COL FREE_GB FORMAT 999,999
COL TOTAL_GB FORMAT 999,999

SELECT G.NAME AS GROUP_NAME
     , G.GROUP_NUMBER
	 , D.NAME AS DISK_NAME
	 , D.HEADER_STATUS
	 , D.STATE
	 , D.FREE_MB/1024 AS FREE_GB
	 , D.TOTAL_MB/1024 AS TOTAL_GB
  FROM V$ASM_DISK D
     , V$ASM_DISKGROUP G
 WHERE D.GROUP_NUMBER = G.GROUP_NUMBER
 ORDER BY G.NAME, D.NAME;

TTITLE OFF

/*
-- DISKGROUP에 DISK 추가 / 삭제
ALTER DISKGROUP DG_TEST ADD DISK '/dev/disktest' REBALANCE POWER 10;
ALTER DISKGROUP DG_TEST DROP DISK '/dev/disktest' REBALANCE POWER 10;

-- 가능하면 ASM DISK DROP과 ADD를 동시에 수행하여 불필요한 I/O를 감소시키는 게 좋다.
ALTER DISKGROUP DG_TEST DROP DISK DG_DATA_0001, DG_DATA_0002 ADD DISK '/dev/disktest2' NAME DG_DATA_0003, "/dev/disktest3' NAME DG_DATA_0004 REBALANCE POWER 10 WAIT;

-- DISKGROUP 내 DISK RESIZE
ALTER DISKGROUP DG_TEST RESIZE DISK DG_DATA_0001 SIZE 5G;

-- ASM DISK CHECK (DISK 정합성 확인) 결과는 ALERT LOG에 기록됨.
-- ALERT LOG 위치: $ORACLE_BASE/diag/asm/+asm/+ASM{instance_number}/trace/alert_+ASM{instance_number}.log
ALTER DISKGROUP DG_TEST CHECK ALL;
*/