TTITLE "[DBname] Database|Oracle ASM Operation"

SET LINESIZE 200
SET PAGESIZE 500

COL GROUP_NAME FORMAT A10
COL OPERATION FORMAT A10
COL PASS FORMAT A10
COL STATE FORMAT A10
COL POWER FORMAT 999,999
COL SOFAR FORMAT 999,999
COL EST_WORK FORMAT 999,999
COL EST_MINUTES FORMAT 999,999

SELECT A.NAME GROUP_NAME
     , B.OEPRATION
	 , B.PASS
	 , B.STATE
	 , B.POWER
	 , B.SOFAR
	 , B.EST_WORK
	 , B.EST_MINUTES
  FROM V$ASM_DISKGROUP A
     , V$ASM_OPERATION B
 WHERE A.GROUP_NUMBER = B.GROUP_NUMBER
 ORDER BY B.EST_MINUTES DESC;
 
TTITLE OFF