TTITLE "[DBName] Database|Oracle Tablespace Quotas";

SET PAGESIZE 500
SET LINESIZE 200
SET HEADING ON

COL TS_NAME FORMAT A15
COL USERNAME FORMAT A20
COL TOTAL_MB FORMAT 999,999
COL MAX_MB FORMAT A15
COL BLOCKS FORMAT 999,999
COL MAX_BLOCKS FORMAT A15

SELECT TABLESPACE_NAME AS TS_NAME
     , USERNAME
	 , ROUND(BYTES/1024/1024,2) AS TOTAL_MB
	 , CASE WHEN MAX_BYTES = -1 THEN 'UNLIMITED' ELSE TO_CHAR(ROUND(MAX_BYTES/1024/1024,2)) END AS MAX_MB
	 , BLOCKS
	 , CASE WHEN MAX_BLOCKS = -1 THEN 'UNLIMITED' ELSE TO_CHAR(MAX_BLOCKS) END AS MAX_BLOCKS
	 -- , DROPPED
  FROM DBA_TS_QUTOAS
 ORDER BY 1;
 
TTITLE OFF
