-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.INNODB_INDEXES UNION ALL
-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.INNODB_TABLES UNION ALL
-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.INNODB_TABLESPACES UNION ALL
-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.ROUTINES UNION ALL
-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.SCHEMATA UNION ALL
-- SELECT 'DEV_LGC' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.VIEWS UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.INNODB_INDEXES UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.INNODB_TABLES UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.INNODB_TABLESPACES UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.ROUTINES UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.SCHEMATA UNION ALL
-- SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.VIEWS UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.INNODB_INDEXES UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.INNODB_TABLES UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.INNODB_TABLESPACES UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.ROUTINES UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.SCHEMATA UNION ALL
-- SELECT 'DEV_LGES' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.VIEWS UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.INNODB_INDEXES UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.INNODB_TABLES UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.INNODB_TABLESPACES UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.ROUTINES UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.SCHEMATA UNION ALL
-- SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.VIEWS UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.INNODB_INDEXES UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.INNODB_TABLES UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.INNODB_TABLESPACES UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.ROUTINES UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.SCHEMATA UNION ALL
-- SELECT 'PRD_LGC' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.VIEWS UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.INNODB_INDEXES UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.INNODB_TABLES UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.INNODB_TABLESPACES UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.ROUTINES UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.SCHEMATA UNION ALL
-- SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.VIEWS UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.INNODB_INDEXES UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.INNODB_TABLES UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.INNODB_TABLESPACES UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.ROUTINES UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.SCHEMATA UNION ALL
-- SELECT 'PRD_LGES' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.VIEWS UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.INNODB_INDEXES UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.INNODB_TABLES UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.INNODB_TABLESPACES UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.ROUTINES UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.SCHEMATA UNION ALL
-- SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.VIEWS UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.INNODB_INDEXES UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.INNODB_TABLES UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.INNODB_TABLESPACES UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.ROUTINES UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.SCHEMATA UNION ALL
-- SELECT 'QA3_LGC' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.VIEWS UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.INNODB_INDEXES UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.INNODB_TABLES UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.INNODB_TABLESPACES UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.ROUTINES UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.SCHEMATA UNION ALL
-- SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.VIEWS UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.INNODB_INDEXES UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.INNODB_TABLES UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.INNODB_TABLESPACES UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.ROUTINES UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.SCHEMATA UNION ALL
-- SELECT 'QA3_LGES' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.VIEWS UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.INNODB_INDEXES UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.INNODB_TABLES UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.INNODB_TABLESPACES UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.ROUTINES UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.SCHEMATA UNION ALL
-- SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.VIEWS UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.INNODB_INDEXES UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.INNODB_TABLES UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.INNODB_TABLESPACES UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.ROUTINES UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.SCHEMATA UNION ALL
-- SELECT 'STG_LGC' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.VIEWS UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.INNODB_INDEXES UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.INNODB_TABLES UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.INNODB_TABLESPACES UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.PARTITIONS UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.ROUTINES UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.SCHEMATA UNION ALL
-- SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.VIEWS UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.INNODB_INDEXES UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.INNODB_TABLES UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.INNODB_TABLESPACES UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.ROUTINES UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.SCHEMATA UNION ALL
-- SELECT 'STG_LGES' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.VIEWS UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'INNODB_INDEXES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.INNODB_INDEXES UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.INNODB_TABLES UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'INNODB_TABLESPACES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.INNODB_TABLESPACES UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'ROUTINES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.ROUTINES UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'SCHEMATA' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.SCHEMATA UNION ALL
-- SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'VIEWS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.VIEWS UNION ALL
SELECT 'DEV_LGC' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.TABLES UNION ALL
SELECT 'DEV_LGC' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.COLUMNS UNION ALL
SELECT 'DEV_LGC' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.PARTITIONS UNION ALL
SELECT 'DEV_LGC' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGC.STATISTICS UNION ALL
SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.TABLES UNION ALL
SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.COLUMNS UNION ALL
SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.PARTITIONS UNION ALL
SELECT 'DEV_LGCNS' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGCNS.STATISTICS UNION ALL
SELECT 'DEV_LGES' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.TABLES UNION ALL
SELECT 'DEV_LGES' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.COLUMNS UNION ALL
SELECT 'DEV_LGES' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.PARTITIONS UNION ALL
SELECT 'DEV_LGES' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_LGES.STATISTICS UNION ALL
SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.TABLES UNION ALL
SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.COLUMNS UNION ALL
SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.PARTITIONS UNION ALL
SELECT 'DEV_PORTAL' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM DEV_PORTAL.STATISTICS UNION ALL
SELECT 'PRD_LGC' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.TABLES UNION ALL
SELECT 'PRD_LGC' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.COLUMNS UNION ALL
SELECT 'PRD_LGC' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.PARTITIONS UNION ALL
SELECT 'PRD_LGC' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGC.STATISTICS UNION ALL
SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.TABLES UNION ALL
SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.COLUMNS UNION ALL
SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.PARTITIONS UNION ALL
SELECT 'PRD_LGCNS' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGCNS.STATISTICS UNION ALL
SELECT 'PRD_LGES' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.TABLES UNION ALL
SELECT 'PRD_LGES' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.COLUMNS UNION ALL
SELECT 'PRD_LGES' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.PARTITIONS UNION ALL
SELECT 'PRD_LGES' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_LGES.STATISTICS UNION ALL
SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.TABLES UNION ALL
SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.COLUMNS UNION ALL
SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.PARTITIONS UNION ALL
SELECT 'PRD_PORTAL' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM PRD_PORTAL.STATISTICS UNION ALL
SELECT 'QA3_LGC' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.TABLES UNION ALL
SELECT 'QA3_LGC' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.COLUMNS UNION ALL
SELECT 'QA3_LGC' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.PARTITIONS UNION ALL
SELECT 'QA3_LGC' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGC.STATISTICS UNION ALL
SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.TABLES UNION ALL
SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.COLUMNS UNION ALL
SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.PARTITIONS UNION ALL
SELECT 'QA3_LGCNS' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGCNS.STATISTICS UNION ALL
SELECT 'QA3_LGES' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.TABLES UNION ALL
SELECT 'QA3_LGES' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.COLUMNS UNION ALL
SELECT 'QA3_LGES' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.PARTITIONS UNION ALL
SELECT 'QA3_LGES' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_LGES.STATISTICS UNION ALL
SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.TABLES UNION ALL
SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.COLUMNS UNION ALL
SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.PARTITIONS UNION ALL
SELECT 'QA3_PORTAL' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM QA3_PORTAL.STATISTICS UNION ALL
SELECT 'STG_LGC' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.TABLES UNION ALL
SELECT 'STG_LGC' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.COLUMNS UNION ALL
SELECT 'STG_LGC' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.PARTITIONS UNION ALL
SELECT 'STG_LGC' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGC.STATISTICS UNION ALL
SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.TABLES UNION ALL
SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.COLUMNS UNION ALL
SELECT 'STG_LGCNS' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGCNS.STATISTICS UNION ALL
SELECT 'STG_LGES' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.TABLES UNION ALL
SELECT 'STG_LGES' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.COLUMNS UNION ALL
SELECT 'STG_LGES' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.PARTITIONS UNION ALL
SELECT 'STG_LGES' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_LGES.STATISTICS UNION ALL
SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'TABLES' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.TABLES UNION ALL
SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'COLUMNS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.COLUMNS UNION ALL
SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'PARTITIONS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.PARTITIONS UNION ALL
SELECT 'STG_PORTAL' AS SCHEMA_NAME, 'STATISTICS' AS TABLE_NAME, COUNT(1) AS CNT FROM STG_PORTAL.STATISTICS;









TRUNCATE TABLE STG_LGC.COLUMNS;
TRUNCATE TABLE STG_LGC.INNODB_INDEXES;
TRUNCATE TABLE STG_LGC.INNODB_TABLES;
TRUNCATE TABLE STG_LGC.INNODB_TABLESPACES;
TRUNCATE TABLE STG_LGC.PARTITIONS;
TRUNCATE TABLE STG_LGC.ROUTINES;
TRUNCATE TABLE STG_LGC.SCHEMATA;
TRUNCATE TABLE STG_LGC.STATISTICS;
TRUNCATE TABLE STG_LGC.TABLES;
TRUNCATE TABLE STG_LGC.TRIGGERS;
TRUNCATE TABLE STG_LGC.VIEWS;
TRUNCATE TABLE STG_LGCNS.COLUMNS;
TRUNCATE TABLE STG_LGCNS.INNODB_INDEXES;
TRUNCATE TABLE STG_LGCNS.INNODB_TABLES;
TRUNCATE TABLE STG_LGCNS.INNODB_TABLESPACES;
TRUNCATE TABLE STG_LGCNS.PARTITIONS;
TRUNCATE TABLE STG_LGCNS.ROUTINES;
TRUNCATE TABLE STG_LGCNS.SCHEMATA;
TRUNCATE TABLE STG_LGCNS.STATISTICS;
TRUNCATE TABLE STG_LGCNS.TABLES;
TRUNCATE TABLE STG_LGCNS.TRIGGERS;
TRUNCATE TABLE STG_LGCNS.VIEWS;
TRUNCATE TABLE STG_LGES.COLUMNS;
TRUNCATE TABLE STG_LGES.INNODB_INDEXES;
TRUNCATE TABLE STG_LGES.INNODB_TABLES;
TRUNCATE TABLE STG_LGES.INNODB_TABLESPACES;
TRUNCATE TABLE STG_LGES.PARTITIONS;
TRUNCATE TABLE STG_LGES.ROUTINES;
TRUNCATE TABLE STG_LGES.SCHEMATA;
TRUNCATE TABLE STG_LGES.STATISTICS;
TRUNCATE TABLE STG_LGES.TABLES;
TRUNCATE TABLE STG_LGES.TRIGGERS;
TRUNCATE TABLE STG_LGES.VIEWS;
TRUNCATE TABLE STG_PORTAL.COLUMNS;
TRUNCATE TABLE STG_PORTAL.INNODB_INDEXES;
TRUNCATE TABLE STG_PORTAL.INNODB_TABLES;
TRUNCATE TABLE STG_PORTAL.INNODB_TABLESPACES;
TRUNCATE TABLE STG_PORTAL.PARTITIONS;
TRUNCATE TABLE STG_PORTAL.ROUTINES;
TRUNCATE TABLE STG_PORTAL.SCHEMATA;
TRUNCATE TABLE STG_PORTAL.STATISTICS;
TRUNCATE TABLE STG_PORTAL.TABLES;
TRUNCATE TABLE STG_PORTAL.TRIGGERS;
TRUNCATE TABLE STG_PORTAL.VIEWS;

TRUNCATE TABLE DEV_LGC.COLUMNS;
TRUNCATE TABLE DEV_LGC.INNODB_INDEXES;
TRUNCATE TABLE DEV_LGC.INNODB_TABLES;
TRUNCATE TABLE DEV_LGC.INNODB_TABLESPACES;
TRUNCATE TABLE DEV_LGC.PARTITIONS;
TRUNCATE TABLE DEV_LGC.ROUTINES;
TRUNCATE TABLE DEV_LGC.SCHEMATA;
TRUNCATE TABLE DEV_LGC.STATISTICS;
TRUNCATE TABLE DEV_LGC.TABLES;
TRUNCATE TABLE DEV_LGC.TRIGGERS;
TRUNCATE TABLE DEV_LGC.VIEWS;
TRUNCATE TABLE DEV_LGCNS.COLUMNS;
TRUNCATE TABLE DEV_LGCNS.INNODB_INDEXES;
TRUNCATE TABLE DEV_LGCNS.INNODB_TABLES;
TRUNCATE TABLE DEV_LGCNS.INNODB_TABLESPACES;
TRUNCATE TABLE DEV_LGCNS.PARTITIONS;
TRUNCATE TABLE DEV_LGCNS.ROUTINES;
TRUNCATE TABLE DEV_LGCNS.SCHEMATA;
TRUNCATE TABLE DEV_LGCNS.STATISTICS;
TRUNCATE TABLE DEV_LGCNS.TABLES;
TRUNCATE TABLE DEV_LGCNS.TRIGGERS;
TRUNCATE TABLE DEV_LGCNS.VIEWS;
TRUNCATE TABLE DEV_LGES.COLUMNS;
TRUNCATE TABLE DEV_LGES.INNODB_INDEXES;
TRUNCATE TABLE DEV_LGES.INNODB_TABLES;
TRUNCATE TABLE DEV_LGES.INNODB_TABLESPACES;
TRUNCATE TABLE DEV_LGES.PARTITIONS;
TRUNCATE TABLE DEV_LGES.ROUTINES;
TRUNCATE TABLE DEV_LGES.SCHEMATA;
TRUNCATE TABLE DEV_LGES.STATISTICS;
TRUNCATE TABLE DEV_LGES.TABLES;
TRUNCATE TABLE DEV_LGES.TRIGGERS;
TRUNCATE TABLE DEV_LGES.VIEWS;
TRUNCATE TABLE DEV_PORTAL.COLUMNS;
TRUNCATE TABLE DEV_PORTAL.INNODB_INDEXES;
TRUNCATE TABLE DEV_PORTAL.INNODB_TABLES;
TRUNCATE TABLE DEV_PORTAL.INNODB_TABLESPACES;
TRUNCATE TABLE DEV_PORTAL.PARTITIONS;
TRUNCATE TABLE DEV_PORTAL.ROUTINES;
TRUNCATE TABLE DEV_PORTAL.SCHEMATA;
TRUNCATE TABLE DEV_PORTAL.STATISTICS;
TRUNCATE TABLE DEV_PORTAL.TABLES;
TRUNCATE TABLE DEV_PORTAL.TRIGGERS;
TRUNCATE TABLE DEV_PORTAL.VIEWS;

TRUNCATE TABLE QA3_LGC.COLUMNS;
TRUNCATE TABLE QA3_LGC.INNODB_INDEXES;
TRUNCATE TABLE QA3_LGC.INNODB_TABLES;
TRUNCATE TABLE QA3_LGC.INNODB_TABLESPACES;
TRUNCATE TABLE QA3_LGC.PARTITIONS;
TRUNCATE TABLE QA3_LGC.ROUTINES;
TRUNCATE TABLE QA3_LGC.SCHEMATA;
TRUNCATE TABLE QA3_LGC.STATISTICS;
TRUNCATE TABLE QA3_LGC.TABLES;
TRUNCATE TABLE QA3_LGC.TRIGGERS;
TRUNCATE TABLE QA3_LGC.VIEWS;
TRUNCATE TABLE QA3_LGCNS.COLUMNS;
TRUNCATE TABLE QA3_LGCNS.INNODB_INDEXES;
TRUNCATE TABLE QA3_LGCNS.INNODB_TABLES;
TRUNCATE TABLE QA3_LGCNS.INNODB_TABLESPACES;
TRUNCATE TABLE QA3_LGCNS.PARTITIONS;
TRUNCATE TABLE QA3_LGCNS.ROUTINES;
TRUNCATE TABLE QA3_LGCNS.SCHEMATA;
TRUNCATE TABLE QA3_LGCNS.STATISTICS;
TRUNCATE TABLE QA3_LGCNS.TABLES;
TRUNCATE TABLE QA3_LGCNS.TRIGGERS;
TRUNCATE TABLE QA3_LGCNS.VIEWS;
TRUNCATE TABLE QA3_LGES.COLUMNS;
TRUNCATE TABLE QA3_LGES.INNODB_INDEXES;
TRUNCATE TABLE QA3_LGES.INNODB_TABLES;
TRUNCATE TABLE QA3_LGES.INNODB_TABLESPACES;
TRUNCATE TABLE QA3_LGES.PARTITIONS;
TRUNCATE TABLE QA3_LGES.ROUTINES;
TRUNCATE TABLE QA3_LGES.SCHEMATA;
TRUNCATE TABLE QA3_LGES.STATISTICS;
TRUNCATE TABLE QA3_LGES.TABLES;
TRUNCATE TABLE QA3_LGES.TRIGGERS;
TRUNCATE TABLE QA3_LGES.VIEWS;
TRUNCATE TABLE QA3_PORTAL.COLUMNS;
TRUNCATE TABLE QA3_PORTAL.INNODB_INDEXES;
TRUNCATE TABLE QA3_PORTAL.INNODB_TABLES;
TRUNCATE TABLE QA3_PORTAL.INNODB_TABLESPACES;
TRUNCATE TABLE QA3_PORTAL.PARTITIONS;
TRUNCATE TABLE QA3_PORTAL.ROUTINES;
TRUNCATE TABLE QA3_PORTAL.SCHEMATA;
TRUNCATE TABLE QA3_PORTAL.STATISTICS;
TRUNCATE TABLE QA3_PORTAL.TABLES;
TRUNCATE TABLE QA3_PORTAL.TRIGGERS;
TRUNCATE TABLE QA3_PORTAL.VIEWS;

TRUNCATE TABLE PRD_LGC.COLUMNS;
TRUNCATE TABLE PRD_LGC.INNODB_INDEXES;
TRUNCATE TABLE PRD_LGC.INNODB_TABLES;
TRUNCATE TABLE PRD_LGC.INNODB_TABLESPACES;
TRUNCATE TABLE PRD_LGC.PARTITIONS;
TRUNCATE TABLE PRD_LGC.ROUTINES;
TRUNCATE TABLE PRD_LGC.SCHEMATA;
TRUNCATE TABLE PRD_LGC.STATISTICS;
TRUNCATE TABLE PRD_LGC.TABLES;
TRUNCATE TABLE PRD_LGC.TRIGGERS;
TRUNCATE TABLE PRD_LGC.VIEWS;
TRUNCATE TABLE PRD_LGCNS.COLUMNS;
TRUNCATE TABLE PRD_LGCNS.INNODB_INDEXES;
TRUNCATE TABLE PRD_LGCNS.INNODB_TABLES;
TRUNCATE TABLE PRD_LGCNS.INNODB_TABLESPACES;
TRUNCATE TABLE PRD_LGCNS.PARTITIONS;
TRUNCATE TABLE PRD_LGCNS.ROUTINES;
TRUNCATE TABLE PRD_LGCNS.SCHEMATA;
TRUNCATE TABLE PRD_LGCNS.STATISTICS;
TRUNCATE TABLE PRD_LGCNS.TABLES;
TRUNCATE TABLE PRD_LGCNS.TRIGGERS;
TRUNCATE TABLE PRD_LGCNS.VIEWS;
TRUNCATE TABLE PRD_LGES.COLUMNS;
TRUNCATE TABLE PRD_LGES.INNODB_INDEXES;
TRUNCATE TABLE PRD_LGES.INNODB_TABLES;
TRUNCATE TABLE PRD_LGES.INNODB_TABLESPACES;
TRUNCATE TABLE PRD_LGES.PARTITIONS;
TRUNCATE TABLE PRD_LGES.ROUTINES;
TRUNCATE TABLE PRD_LGES.SCHEMATA;
TRUNCATE TABLE PRD_LGES.STATISTICS;
TRUNCATE TABLE PRD_LGES.TABLES;
TRUNCATE TABLE PRD_LGES.TRIGGERS;
TRUNCATE TABLE PRD_LGES.VIEWS;
TRUNCATE TABLE PRD_PORTAL.COLUMNS;
TRUNCATE TABLE PRD_PORTAL.INNODB_INDEXES;
TRUNCATE TABLE PRD_PORTAL.INNODB_TABLES;
TRUNCATE TABLE PRD_PORTAL.INNODB_TABLESPACES;
TRUNCATE TABLE PRD_PORTAL.PARTITIONS;
TRUNCATE TABLE PRD_PORTAL.ROUTINES;
TRUNCATE TABLE PRD_PORTAL.SCHEMATA;
TRUNCATE TABLE PRD_PORTAL.STATISTICS;
TRUNCATE TABLE PRD_PORTAL.TABLES;
TRUNCATE TABLE PRD_PORTAL.TRIGGERS;
TRUNCATE TABLE PRD_PORTAL.VIEWS;