SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, TABLE_ROWS, DATA_LENGTH, INDEX_LENGTH, TABLE_COLLATION, CREATE_TIME, UPDATE_TIME, TABLE_COMMENT
     , CONCAT('ALTER TABLE ', TABLE_SCHEMA, '.', TABLE_NAME, ' DEFAULT CHARSET = ''utf8mb4'' COLLATE = ''utf8mb4_bin'';') AS ALTER_DDL
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_COLLATION <> 'utf8mb4_bin'
   AND TABLE_SCHEMA NOT IN ('sys','performance_schema','information_schema','mysql')
   AND TABLE_TYPE = 'BASE TABLE' 
 ORDER BY 1,2,3;

SELECT A.TABLE_SCHEMA
     , A.TABLE_NAME
	 , A.COLUMN_NAME
	 , A.ORDINAL_POSITION
	 , A.COLUMN_DEFAULT
	 , A.IS_NULLABLE
	 , A.COLUMN_TYPE
	 , A.CHARACTER_SET_NAME
	 , A.COLLATION_NAME
	 , A.COLUMN_KEY
	 , A.COLUMN_COMMENT
     , CONCAT('ALTER TABLE ', A.TABLE_SCHEMA, '.', A.TABLE_NAME, ' MODIFY COLUMN ', A.COLUMN_NAME, ' ', A.COLUMN_TYPE, CASE A.IS_NULLABLE WHEN 'NO' THEN ' NOT NULL ' WHEN 'YES' THEN ' NULL ' END, CASE WHEN A.COLUMN_DEFAULT IS NULL THEN '' ELSE CONCAT('DEFAULT ''', A.COLUMN_DEFAULT, '''') END, ' COLLATE ''utf8mb4_bin'' COMMENT ''', A.COLUMN_COMMENT, ''';' ) AS ALTER_DDL
  FROM INFORMATION_SCHEMA.COLUMNS A
 INNER JOIN INFORMATION_SCHEMA.TABLES B
    ON A.TABLE_CATALOG = B.TABLE_CATALOG
   AND A.TABLE_SCHEMA = B.TABLE_SCHEMA
   AND A.TABLE_NAME = B.TABLE_NAME
 WHERE (A.CHARACTER_SET_NAME <> 'utf8mb4' OR A.COLLATION_NAME <> 'utf8mb4_bin') 
   AND A.TABLE_SCHEMA NOT IN ('sys','performance_schema','information_schema','mysql') 
   AND B.TABLE_TYPE = 'BASE TABLE'
 ORDER BY 1,2,4;

---------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE INORG.SFI_USER_PROP MODIFY COLUMN `KEY` varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '속성키';

ALTER TABLE INORG.SFI_ROLE_ITEM_DATA DROP FOREIGN KEY `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE`;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA DROP FOREIGN KEY `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE_ITEM`;
ALTER TABLE INORG.SFI_API DROP FOREIGN KEY `FK_SFI_API_SFI_ROLE_ITEM`;

ALTER TABLE INORG.SFI_ROLE MODIFY COLUMN ID varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT '권한ID(MMS,SYSTEM,INSIGN)';
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA MODIFY COLUMN ROLE_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한ID';
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA MODIFY COLUMN ITEM_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한항목ID';
ALTER TABLE INORG.SFI_ROLE_ITEM MODIFY COLUMN ITEM_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한항목ID';
ALTER TABLE INORG.SFI_API MODIFY COLUMN API_ROLE_TYPE_CD varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT 'API권한코드(EMP,COMPANY,SYSTEM)';

ALTER TABLE INORG.SFI_API ADD CONSTRAINT `FK_SFI_API_SFI_ROLE_ITEM` FOREIGN KEY (`API_ROLE_TYPE_CD`) REFERENCES `SFI_ROLE_ITEM` (`ITEM_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA ADD CONSTRAINT `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `SFI_ROLE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA ADD CONSTRAINT `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `SFI_ROLE_ITEM` (`ITEM_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
---------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE INORG.SFI_USER_PROP MODIFY COLUMN `KEY` varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '속성키';

ALTER TABLE INORG.SFI_ROLE_ITEM_DATA DROP FOREIGN KEY `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE`;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA DROP FOREIGN KEY `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE_ITEM`;
ALTER TABLE INORG.SFI_API DROP FOREIGN KEY `FK_SFI_API_SFI_ROLE_ITEM`;
ALTER TABLE INORG.SFI_ROLE_ITEM DROP FOREIGN KEY `FK_sfi_role_item_sfi_role_item`;

ALTER TABLE INORG.SFI_ROLE MODIFY COLUMN ID varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT '권한ID(MMS,SYSTEM,INSIGN)';
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA MODIFY COLUMN ROLE_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한ID';
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA MODIFY COLUMN ITEM_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한항목ID';
ALTER TABLE INORG.SFI_ROLE_ITEM MODIFY COLUMN ITEM_ID varchar(255) NOT NULL  COLLATE 'utf8mb4_bin' COMMENT '권한항목ID';
ALTER TABLE INORG.SFI_ROLE_ITEM MODIFY COLUMN UP_ITEM_ID varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT '상위권한항목ID';
ALTER TABLE INORG.SFI_API MODIFY COLUMN API_ROLE_TYPE_CD varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT 'API권한코드(EMP,COMPANY,SYSTEM)';

ALTER TABLE INORG.SFI_ROLE_ITEM ADD CONSTRAINT `FK_sfi_role_item_sfi_role_item` FOREIGN KEY (`UP_ITEM_ID`) REFERENCES `SFI_ROLE_ITEM` (`ITEM_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INORG.SFI_API ADD CONSTRAINT `FK_SFI_API_SFI_ROLE_ITEM` FOREIGN KEY (`API_ROLE_TYPE_CD`) REFERENCES `SFI_ROLE_ITEM` (`ITEM_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA ADD CONSTRAINT `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `SFI_ROLE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INORG.SFI_ROLE_ITEM_DATA ADD CONSTRAINT `FK_SFI_ROLE_ITEM_DATA_SFI_ROLE_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `SFI_ROLE_ITEM` (`ITEM_ID`) ON DELETE CASCADE ON UPDATE CASCADE;



---------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE INORG.RCV_SFI_CMM_CODE MODIFY COLUMN OPT1 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드1';
ALTER TABLE INORG.RCV_SFI_CMM_CODE MODIFY COLUMN OPT2 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드2';
ALTER TABLE INORG.RCV_SFI_CMM_CODE MODIFY COLUMN OPT3 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드3';
ALTER TABLE INORG.RCV_SFI_CMM_CODE MODIFY COLUMN OPT4 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드4';
ALTER TABLE INORG.RCV_SFI_CMM_CODE MODIFY COLUMN OPT5 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드5';

ALTER TABLE INORG.SFI_CMM_CODE MODIFY COLUMN OPT1 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드1';
ALTER TABLE INORG.SFI_CMM_CODE MODIFY COLUMN OPT2 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드2';
ALTER TABLE INORG.SFI_CMM_CODE MODIFY COLUMN OPT3 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드3';
ALTER TABLE INORG.SFI_CMM_CODE MODIFY COLUMN OPT4 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드4';
ALTER TABLE INORG.SFI_CMM_CODE MODIFY COLUMN OPT5 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드5';

ALTER TABLE INORG.SFI_CMM_CODE_TYPE MODIFY COLUMN OPT1 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드1';
ALTER TABLE INORG.SFI_CMM_CODE_TYPE MODIFY COLUMN OPT2 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드2';
ALTER TABLE INORG.SFI_CMM_CODE_TYPE MODIFY COLUMN OPT3 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드3';
ALTER TABLE INORG.SFI_CMM_CODE_TYPE MODIFY COLUMN OPT4 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드4';
ALTER TABLE INORG.SFI_CMM_CODE_TYPE MODIFY COLUMN OPT5 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드5';

ALTER TABLE INORG.SFI_SVC_CODE MODIFY COLUMN OPT1 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드1';
ALTER TABLE INORG.SFI_SVC_CODE MODIFY COLUMN OPT2 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드2';
ALTER TABLE INORG.SFI_SVC_CODE MODIFY COLUMN OPT3 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드3';
ALTER TABLE INORG.SFI_SVC_CODE MODIFY COLUMN OPT4 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드4';
ALTER TABLE INORG.SFI_SVC_CODE MODIFY COLUMN OPT5 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드5';

ALTER TABLE INORG.SFI_SVC_CODE_TYPE MODIFY COLUMN OPT1 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드1';
ALTER TABLE INORG.SFI_SVC_CODE_TYPE MODIFY COLUMN OPT2 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드2';
ALTER TABLE INORG.SFI_SVC_CODE_TYPE MODIFY COLUMN OPT3 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드3';
ALTER TABLE INORG.SFI_SVC_CODE_TYPE MODIFY COLUMN OPT4 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드4';
ALTER TABLE INORG.SFI_SVC_CODE_TYPE MODIFY COLUMN OPT5 varchar(2000) NULL  COLLATE 'utf8mb4_bin' COMMENT '옵션필드5';

ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA01 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터01';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA02 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터02';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA03 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터03';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA04 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터04';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA05 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터05';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA06 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터06';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA07 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터07';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA08 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터08';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA09 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터09';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA10 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터10';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA11 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터11';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA12 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터12';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA13 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터13';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA14 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터14';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA15 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터15';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA16 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터16';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA17 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터17';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA18 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터18';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA19 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터19';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN DATA20 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터20';
ALTER TABLE INORG.SSP_EMP_ETC_DATA MODIFY COLUMN UP_USER_ID varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT '수정자';

ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA11 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터11';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA12 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터12';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA13 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터13';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA14 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터14';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA15 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터15';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA16 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터16';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA17 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터17';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA18 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터18';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA19 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터19';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA20 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터20';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA01 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터01';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA02 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터02';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA03 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터03';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA04 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터04';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA05 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터05';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA06 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터06';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA07 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터07';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA08 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터08';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA09 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터09';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN DATA10 varchar(512) NULL  COLLATE 'utf8mb4_bin' COMMENT '데이터10';
ALTER TABLE INORG.SSP_ORG_ETC_DATA MODIFY COLUMN UP_USER_ID varchar(255) NULL  COLLATE 'utf8mb4_bin' COMMENT '수정자';