-- DB 간 인덱스 구성 차이 확인
SHOW VARIABLES LIKE '%group_concat%';
SET SESSION group_concat_max_len = 1024 * 1024;
WITH PORTAL AS (SELECT 'PRD_PORTAL' AS DB, TABLE_NAME, INDEX_SCHEMA, INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ', ') AS INDEX_COLUMNS
                  FROM PRD_PORTAL.STATISTICS
                 GROUP BY TABLE_NAME, INDEX_SCHEMA, INDEX_NAME)
   , LGCNS AS (SELECT 'PRD_LGCNS' AS DB, TABLE_NAME, INDEX_SCHEMA, INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ', ') AS INDEX_COLUMNS
                 FROM PRD_LGCNS.STATISTICS
                GROUP BY TABLE_NAME, INDEX_SCHEMA, INDEX_NAME)
   , LGC AS (SELECT 'PRD_LGC' AS DB, TABLE_NAME, INDEX_SCHEMA, INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ', ') AS INDEX_COLUMNS
               FROM PRD_LGC.STATISTICS
              GROUP BY TABLE_NAME, INDEX_SCHEMA, INDEX_NAME)
   , LGES AS (SELECT 'PRD_LGES' AS DB, TABLE_NAME, INDEX_SCHEMA, INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ', ') AS INDEX_COLUMNS
                FROM PRD_LGES.STATISTICS
               GROUP BY TABLE_NAME, INDEX_SCHEMA, INDEX_NAME)
SELECT X.TABLE_NAME
     , X.INDEX_SCHEMA
     , X.INDEX_NAME
     , X.INDEX_COLUMNS
     , COUNT(1) DB_COUNT
     , GROUP_CONCAT(DB SEPARATOR ', ') AS DB_AGG
  FROM (SELECT * FROM PORTAL
         UNION ALL
        SELECT * FROM LGCNS
         UNION ALL
        SELECT * FROM LGC
         UNION ALL
        SELECT * FROM LGES) X
 WHERE 1=1
 GROUP BY X.TABLE_NAME, X.INDEX_SCHEMA, X.INDEX_NAME, X.INDEX_COLUMNS
HAVING COUNT(1) < 4
 ORDER BY X.TABLE_NAME, X.INDEX_SCHEMA, X.INDEX_NAME, DB_AGG DESC
;