-- PRD_PORTAL - (PRD_LGCNS + PRD_LGC + PRD_LGES)
SELECT 'PRD_PORTAL' AS DB_INSTANCE, A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.TABLE_TYPE, A.ENGINE, A.VERSION, A.ROW_FORMAT, A.TABLE_COLLATION, A.TABLE_COMMENT
  FROM PRD_PORTAL.TABLES A
  LEFT OUTER JOIN (SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGCNS.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGC.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGES.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE') B
    ON B.TABLE_CATALOG = A.TABLE_CATALOG
   AND B.TABLE_SCHEMA = A.TABLE_SCHEMA
   AND B.TABLE_NAME = A.TABLE_NAME
 WHERE B.TABLE_TYPE IS NULL
   AND A.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND A.TABLE_TYPE = 'BASE TABLE'
 UNION ALL
-- PRD_LGCNS - (PRD_PORTAL + PRD_LGC + PRD_LGES)
SELECT 'PRD_LGCNS' AS DB_INSTANCE, A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.TABLE_TYPE, A.ENGINE, A.VERSION, A.ROW_FORMAT, A.TABLE_COLLATION, A.TABLE_COMMENT
  FROM PRD_LGCNS.TABLES A
  LEFT OUTER JOIN (SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_PORTAL.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGC.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGES.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE') B
    ON B.TABLE_CATALOG = A.TABLE_CATALOG
   AND B.TABLE_SCHEMA = A.TABLE_SCHEMA
   AND B.TABLE_NAME = A.TABLE_NAME
 WHERE B.TABLE_TYPE IS NULL
   AND A.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND A.TABLE_TYPE = 'BASE TABLE'
 UNION ALL
-- PRD_LGC - (PRD_PORTAL + PRD_LGCNS + PRD_LGES)
SELECT 'PRD_LGC' AS DB_INSTANCE, A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.TABLE_TYPE, A.ENGINE, A.VERSION, A.ROW_FORMAT, A.TABLE_COLLATION, A.TABLE_COMMENT
  FROM PRD_LGC.TABLES A
  LEFT OUTER JOIN (SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_PORTAL.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGCNS.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGES.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE') B
    ON B.TABLE_CATALOG = A.TABLE_CATALOG
   AND B.TABLE_SCHEMA = A.TABLE_SCHEMA
   AND B.TABLE_NAME = A.TABLE_NAME
 WHERE B.TABLE_TYPE IS NULL
   AND A.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND A.TABLE_TYPE = 'BASE TABLE'
 UNION ALL
-- PRD_LGES - (PRD_PORTAL + PRD_LGCNS + PRD_LGC)
SELECT 'PRD_LGES' AS DB_INSTANCE, A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.TABLE_TYPE, A.ENGINE, A.VERSION, A.ROW_FORMAT, A.TABLE_COLLATION, A.TABLE_COMMENT
  FROM PRD_LGES.TABLES A
  LEFT OUTER JOIN (SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_PORTAL.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGCNS.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE'
                    UNION
                   SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                     FROM PRD_LGC.TABLES
                    WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                      AND TABLE_TYPE = 'BASE TABLE') B
    ON B.TABLE_CATALOG = A.TABLE_CATALOG
   AND B.TABLE_SCHEMA = A.TABLE_SCHEMA
   AND B.TABLE_NAME = A.TABLE_NAME
 WHERE B.TABLE_TYPE IS NULL
   AND A.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND A.TABLE_TYPE = 'BASE TABLE'
;







-- PRD_PORTAL MINUS QA3_PORTAL
SELECT PRD.*
  FROM PRD_PORTAL.TABLES PRD
  LEFT OUTER JOIN QA3_PORTAL.TABLES QA3
    ON PRD.TABLE_CATALOG = QA3.TABLE_CATALOG
   AND PRD.TABLE_SCHEMA = QA3.TABLE_SCHEMA
   AND PRD.TABLE_NAME = QA3.TABLE_NAME
   AND PRD.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
 WHERE QA3.TABLE_TYPE IS NULL;

-- QA3_PORTAL MINUS PRD_PORTAL
SELECT QA3.*
  FROM QA3_PORTAL.TABLES QA3
  LEFT OUTER JOIN PRD_PORTAL.TABLES PRD
    ON QA3.TABLE_CATALOG = PRD.TABLE_CATALOG
   AND QA3.TABLE_SCHEMA = PRD.TABLE_SCHEMA
   AND QA3.TABLE_NAME = PRD.TABLE_NAME   
 WHERE QA3.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND PRD.TABLE_TYPE IS NULL;





-- PRD_PORTAL MINUS PRD_LGCNS
SELECT PTL.*
  FROM PRD_PORTAL.TABLES PTL
  LEFT OUTER JOIN PRD_LGCNS.TABLES CNS
    ON PTL.TABLE_CATALOG = CNS.TABLE_CATALOG
   AND PTL.TABLE_SCHEMA = CNS.TABLE_SCHEMA
   AND PTL.TABLE_NAME = CNS.TABLE_NAME
   AND PTL.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
 WHERE CNS.TABLE_TYPE IS NULL;

-- PRD_LGCNS MINUS PRD_PORTAL
SELECT CNS.*
  FROM PRD_LGCNS.TABLES CNS
  LEFT OUTER JOIN PRD_PORTAL.TABLES PTL
    ON CNS.TABLE_CATALOG = PTL.TABLE_CATALOG
   AND CNS.TABLE_SCHEMA = PTL.TABLE_SCHEMA
   AND CNS.TABLE_NAME = PTL.TABLE_NAME   
 WHERE CNS.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
   AND PTL.TABLE_TYPE IS NULL;

SELECT A.*
  FROM (SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT 
          FROM PRD_PORTAL.TABLES
         WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
           AND TABLE_TYPE = 'BASE TABLE'
         UNION
        SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
          FROM PRD_LGCNS.TABLES
         WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
           AND TABLE_TYPE = 'BASE TABLE'
         UNION
        SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
          FROM PRD_LGC.TABLES
         WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
           AND TABLE_TYPE = 'BASE TABLE'
         UNION
        SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
          FROM PRD_LGES.TABLES
         WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
           AND TABLE_TYPE = 'BASE TABLE') A
 WHERE A.TABLE_COLLATION <> 'utf8mb4_bin'
 ORDER BY 1,2,3;

