-- DB 간 테이블 구성 차이 확인
WITH PORTAL AS (SELECT 'PRD_PORTAL' AS DB, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT 
                  FROM PRD_PORTAL.TABLES
                 WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                   AND TABLE_TYPE = 'BASE TABLE')
   , LGCNS AS (SELECT 'PRD_LGCNS' AS DB, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                 FROM PRD_LGCNS.TABLES
                WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                  AND TABLE_TYPE = 'BASE TABLE')
   , LGC AS (SELECT 'PRD_LGC' AS DB, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
               FROM PRD_LGC.TABLES
              WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                AND TABLE_TYPE = 'BASE TABLE')
   , LGES AS (SELECT 'PRD_LGES' AS DB, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, ENGINE, VERSION, ROW_FORMAT, TABLE_COLLATION, TABLE_COMMENT
                FROM PRD_LGES.TABLES
               WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'sys', 'mysql')
                 AND TABLE_TYPE = 'BASE TABLE')
SELECT X.TABLE_SCHEMA, X.TABLE_NAME, X.TABLE_TYPE, X.ENGINE, X.VERSION, X.ROW_FORMAT, X.TABLE_COLLATION, X.TABLE_COMMENT
     , COUNT(1) DB_COUNT
     , GROUP_CONCAT(DB SEPARATOR ', ') AS DB_AGG
  FROM (SELECT * FROM PORTAL
         UNION ALL
        SELECT * FROM LGCNS
         UNION ALL
        SELECT * FROM LGC
         UNION ALL
        SELECT * FROM LGES) X
 WHERE 1=1
 GROUP BY X.TABLE_SCHEMA, X.TABLE_NAME, X.TABLE_TYPE, X.ENGINE, X.VERSION, X.ROW_FORMAT, X.TABLE_COLLATION, X.TABLE_COMMENT 
HAVING COUNT(*) < 4
 ORDER BY X.TABLE_SCHEMA, X.TABLE_NAME, X.TABLE_TYPE, X.ENGINE, X.VERSION, X.ROW_FORMAT, X.TABLE_COLLATION, X.TABLE_COMMENT, DB_AGG DESC
;