SELECT 
	   A.TABLE_SCHEMA
	 , A.TABLE_NAME
	 , A.TABLE_COMMENT
	 , B.COLUMN_NAME
	 , B.COLUMN_COMMENT
	 , B.ORDINAL_POSITION
     , B.COLUMN_TYPE
     , B.COLUMN_KEY
	 , B.IS_NULLABLE
	 , B.COLUMN_DEFAULT
	 , MAX(C.PARTITION_EXPRESSION) AS PART_KEY
	 , MAX(C.PARTITION_METHOD) AS PART_METHOD
	 , MIN(C.PARTITION_NAME) AS MIN_PART
	 , MAX(C.PARTITION_NAME) AS MAX_PART
	 , MAX(C.SUBPARTITION_EXPRESSION) AS SUBPART_KEY
	 , MAX(C.SUBPARTITION_METHOD) AS SUBPART_METHOD
	 , MIN(C.SUBPARTITION_NAME) AS MIN_SUBPART
	 , MAX(C.SUBPARTITION_NAME) AS MAX_SUBPART
     -- , A.TABLE_CATALOG
	 -- , A.TABLE_TYPE
	 -- , A.TABLE_ROWS
	 -- , A.ENGINE
	 -- , A.CREATE_TIME
	 -- , A.UPDATE_TIME
	 -- , B.DATA_TYPE
	 -- , B.CHARACTER_MAXIMUM_LENGTH
     -- , B.CHARACTER_OCTET_LENGTH
     -- , B.NUMERIC_PRECISION
     -- , B.NUMERIC_SCALE
     -- , B.DATETIME_PRECISION
     -- , B.CHARACTER_SET_NAME
     -- , B.COLLATION_NAME
  FROM INFORMATION_SCHEMA.TABLES A
 INNER JOIN INFORMATION_SCHEMA.COLUMNS B
    ON A.TABLE_CATALOG = B.TABLE_CATALOG
   AND A.TABLE_SCHEMA = B.TABLE_SCHEMA
   AND A.TABLE_NAME = B.TABLE_NAME
 INNER JOIN INFORMATION_SCHEMA.PARTITIONS C
    ON A.TABLE_CATALOG = C.TABLE_CATALOG
   AND A.TABLE_SCHEMA = C.TABLE_SCHEMA
   AND A.TABLE_NAME = C.TABLE_NAME
 WHERE A.TABLE_SCHEMA IN ( 
  'ERPAPP'
, 'INORG'
, 'ERPHRRT'
, 'FLYWAY'
, 'SAC')
   AND A.TABLE_TYPE = 'BASE TABLE'
 GROUP BY A.TABLE_SCHEMA
	    , A.TABLE_NAME
	    , A.TABLE_COMMENT
	    , B.COLUMN_NAME
	    , B.COLUMN_COMMENT
	    , B.ORDINAL_POSITION
        , B.COLUMN_TYPE
        , B.COLUMN_KEY
	    , B.IS_NULLABLE
	    , B.COLUMN_DEFAULT
 ORDER BY A.TABLE_SCHEMA
        , A.TABLE_NAME
		, B.ORDINAL_POSITION
;



-- DESC INFORMATION_SCHEMA.TABLES;
-- DESC INFORMATION_SCHEMA.COLUMNS;
-- DESC INFORMATION_SCHEMA.PARTITIONS;