SELECT OBJECT_INSTANCE_BEGIN
     , STATEMENT_ID
     , STATEMENT_NAME
     , SQL_TEXT
     , OWNER_THREAD_ID
     , OWNER_EVENT_ID
     , OWNER_OBJECT_TYPE
     , OWNER_OBJECT_SCHEMA
     , OWNER_OBJECT_NAME
     , TIMER_PREPARE
     , COUNT_REPREPARE
     , COUNT_EXECUTE
     , SUM_TIMER_EXECUTE
     , MIN_TIMER_EXECUTE
     , AVG_TIMER_EXECUTE
     , MAX_TIMER_EXECUTE
     , SUM_LOCK_TIME
     , SUM_ERRORS
     , SUM_WARNINGS
     , SUM_ROWS_AFFECTED
     , SUM_ROWS_SENT
     , SUM_ROWS_EXAMINED
     , SUM_CREATED_TMP_DISK_TABLES
     , SUM_CREATED_TMP_TABLES
     , SUM_SELECT_FULL_JOIN
     , SUM_SELECT_FULL_RANGE_JOIN
     , SUM_SELECT_RANGE
     , SUM_SELECT_RANGE_CHECK
     , SUM_SELECT_SCAN
     , SUM_SORT_MERGE_PASSES
     , SUM_SORT_RANGE
     , SUM_SORT_ROWS
     , SUM_SORT_SCAN
     , SUM_NO_INDEX_USED
     , SUM_NO_GOOD_INDEX_USED
  FROM performance_schema.prepared_statements_instances;

-- sample prepared statement
PREPARE stmt FROM 'SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = ?';
SET @table = 'TABLES';
EXECUTE stmt USING @table;
DROP PREPARE stmt;