-- DESC INFORMATION_SCHEMA.TABLES;
-- DESC INFORMATION_SCHEMA.INNODB_INDEXES;
-- DESC INFORMATION_SCHEMA.INNODB_TABLES;
-- DESC INFORMATION_SCHEMA.STATISTICS;

/*
SELECT 
       A.TABLE_SCHEMA
	 , A.TABLE_NAME
     , C.NAME AS "INDEX_NAME"
     , C.TYPE
     , C.N_FIELDS
     , C.PAGE_NO
     , C.SPACE
     , C.MERGE_THRESHOLD
  FROM INFORMATION_SCHEMA.TABLES A
 INNER JOIN INFORMATION_SCHEMA.INNODB_TABLES B
    ON CONCAT(A.TABLE_SCHEMA, '/', A.TABLE_NAME) = B.NAME
 INNER JOIN INFORMATION_SCHEMA.INNODB_INDEXES C
    ON B.TABLE_ID = C.TABLE_ID
 WHERE A.TABLE_SCHEMA IN (
	   'ERPAPP'
	 , 'INORG'
	 , 'ERPHRRT'
	 , 'FLYWAY'
	 , 'SAC')
 ORDER BY 1,2,3
;	
*/

-- SHOW INDEX FROM [TABLE_NAME] LIKE '%%';
-- SHOW INDEX FROM [TABLE_NAME] FROM [DB_NAME];

SELECT 
--        TABLE_CATALOG
       TABLE_SCHEMA
     , TABLE_NAME
--      , INDEX_SCHEMA
     , INDEX_NAME
     , CASE NON_UNIQUE WHEN 0 THEN 'UNIQUE' ELSE 'NON_UNIQUE' END AS UNIQUENESS
     , COLUMN_NAME
     , SEQ_IN_INDEX
     , CASE COLLATION WHEN 'A' THEN 'ASC' WHEN 'D' THEN 'DESC' ELSE NULL END AS COLLATION
     , CARDINALITY
     , SUB_PART
     , PACKED
     , NULLABLE
     , INDEX_TYPE
     , COMMENT
     , INDEX_COMMENT
     , IS_VISIBLE
     , EXPRESSION
  FROM
    INFORMATION_SCHEMA.STATISTICS
 WHERE TABLE_SCHEMA IN (
	   'ERPAPP'
	 , 'INORG'
	 , 'ERPHRRT'
	 , 'FLYWAY'
	 , 'SAC')
 ORDER BY 1, 2, 3, 6
;