-- VIEW TABLE + INDEX SIZE
SELECT 
       TABLE_SCHEMA
     , TABLE_NAME
     , TABLE_ROWS
     , ROUND(DATA_LENGTH/1024/1024, 2) AS "TAB_SIZE_MB"
     , ROUND(INDEX_LENGTH/1024/1024, 2) AS "IDX_SIZE_MB"
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA IN ( 
       'ERPAPP'
     , 'INORG'
     , 'ERPHRRT'
     , 'FLYWAY'
     , 'SAC')
 ORDER BY DATA_LENGTH DESC
;

-- VIEW TABLE + INDEX SIZE USING ROLLUP
SELECT 
       IFNULL(A.TABLE_SCHEMA, '_ROLLUP_TOTAL') AS TABLE_SCHEMA
     , IFNULL(A.TABLE_NAME, '_ROLLUP_SUBTOTAL') AS TABLE_NAME
     , CASE WHEN A.TABLE_SCHEMA IS NULL THEN NULL ELSE SUM(A.TABLE_ROWS) END AS TABLE_ROWS
     , SUM(ROUND(A.DATA_LENGTH/1024/1024, 2)) AS "TAB_SIZE_MB"
     , SUM(ROUND(A.INDEX_LENGTH/1024/1024, 2)) AS "IDX_SIZE_MB"
  FROM INFORMATION_SCHEMA.TABLES A
 WHERE A.TABLE_SCHEMA IN ( 
       'ERPAPP'
     , 'INORG'
     , 'ERPHRRT'
     , 'FLYWAY'
     , 'SAC')
   AND A.TABLE_TYPE = 'BASE TABLE'
 GROUP BY A.TABLE_SCHEMA, A.TABLE_NAME WITH ROLLUP
 ORDER BY A.TABLE_SCHEMA, A.TABLE_NAME
;


-- VIEW PARTITION TABLE + PARTITION INDEX SIZE
SELECT 
       TABLE_SCHEMA
     , TABLE_NAME
     , PARTITION_NAME 
     , SUBPARTITION_NAME
     , TABLE_ROWS
     , ROUND(DATA_LENGTH/1024/1024, 2) AS "TAB_SIZE_MB"
     , ROUND(INDEX_LENGTH/1024/1024, 2) AS "IDX_SIZE_MB"
     , PARTITION_COMMENT
     , TABLESPACE_NAME 
  FROM INFORMATION_SCHEMA.PARTITIONS
 WHERE TABLE_SCHEMA IN ( 
       'ERPAPP'
     , 'INORG'
     , 'ERPHRRT'
     , 'FLYWAY'
     , 'SAC')
 ORDER BY TABLE_SCHEMA, TABLE_NAME, PARTITION_NAME



-- VIEW DATABASE SIZE 
SELECT TABLE_SCHEMA "DB_NAME"
     , ROUND(SUM(DATA_LENGTH + INDEX_LENGTH)/1024/1024/1024, 2) "DB_SIZE_GB" 
  FROM INFORMATION_SCHEMA.TABLES 
 GROUP BY TABLE_SCHEMA
; 