select * from STADM.TB_STC_IFUSF_ENPR_ORG where WORK_DTTM< = to_date('20211021165500','YYYYMMDDHH24MISS')
MINUS
select * from pmpbadm.TB_STC_IFUSF_ENPR_ORG@DL_PNUPB where WORK_DTTM < = to_date('20211021165500','YYYYMMDDHH24MISS');
;
 pmpbadm.TB_STV_FTR_DSTB_VRFY_SMRY
exec  PNPMIG.TB_INSERT;


INSERT INTO pmpbadm.TB_PMPB_INC_ENPR_MTA_APLY_D
SELECT * FROM pmpbadm.TB_PMPB_INC_ENPR_MTA_APLY_D@DL_PUSET1
WHERE SOAC_COMM_ENPR_NO='630' AND MTA_CRTE_YYMM='201706' AND CNTC_HUBB_DIVS_CD='1' AND  SOAC_PHCL_KD_CD='3' AND DATA_CRTE_DIVS_CD='02';
--WHERE SOAC_COMM_ENPR_NO='887' AND MTA_CRTE_YYMM='201704' AND CNTC_HUBB_DIVS_CD='2' AND  SOAC_PHCL_KD_CD='1' AND DATA_CRTE_DIVS_CD='02';

delete FROM pmpbadm.TB_PMPB_INC_ENPR_MTA_APLY_D
WHERE SOAC_COMM_ENPR_NO='887' AND MTA_CRTE_YYMM='201704' AND CNTC_HUBB_DIVS_CD='2' AND  SOAC_PHCL_KD_CD='1' AND DATA_CRTE_DIVS_CD='02';

commit;

rollback;


TRUNCATE TABLE PMPBADM.TB_STV_FTR_DSTB_VRFY_SMRY;

--PMPBADM	TB_PMPB_INC_ENPR_MTA_APLY_D
--PMPBADM	TB_PMPB_COC_GLCA_DS_SOA_PH_D -->0
--PMPBADM	TB_PMPB_COC_GLC_ICA_SOA_PH_D
--PMPBADM	TB_PMPB_INC_CNTC_RAT_M
-- PMPBADM	TB_PMPB_COC_OCTY_ICHR_RFLC_D
--PMPBADM	TB_PMPB_INC_ENPR_RLAY_NO_M
-- STADM	TB_STB_STACC_FTR_CD
--STADM	TB_STV_RECP_STACC_VRFY_SMRY
-- STADM	TB_STV_FTR_DSTB_VRFY_SMRY
STADM	TB_STC_IFUSF_ENPR_ORG
STADM	TB_STB_RNT_SBGN_HIST
PMPBADM	TB_PMPB_SB_BILL_ACNT_I
/*
/*
STADM	TB_STC_IFUSF_ENPR_ORG
STADM	TB_STB_RNT_SBGN_HIST
PMPBADM	TB_PMPB_SB_BILL_ACNT_I
*/

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='VW_PMPB_SB_BILL_ACNT_I';

CREATE TABLE ERR_TB_PMPB_SB_BILL_ACNT_I 
AS
SELECT BILL_ACNT_NO
FROM 
(
SELECT /*+ FULL(A) PARALLEL(A 8) */ * FROM  VW_PMPB_SB_BILL_ACNT_I A WHERE EXISTS(SELECT /*+ HASH_SJ FULL(C) PARALLEL(C 8) */ 'Y' FROM PMPBADM.TB_PMPB_SB_BILL_ACNT_I C WHERE C.BILL_ACNT_ID=A.BILL_ACNT_ID)
MINUS
SELECT  /*+ FULL(B) PARALLEL(B 8) */
        BILL_ACNT_ID,
        BILL_ADDR_SEQNO,
        CNTCT_PNT_SEQNO,
        PYM_ACNT_NO,
        PYM_ACNT_CHNG_DT,
        UTL_RAW.CAST_TO_RAW(MRKT_CD) AS MRKT_CD ,
        BILL_ACNT_FRST_CRTE_DTTM,
        UTL_RAW.CAST_TO_RAW(BLTXT_RCPT_MAN_NM) AS BLTXT_RCPT_MAN_NM ,
        UTL_RAW.CAST_TO_RAW(BLTXT_KD_CD) AS BLTXT_KD_CD ,
        BLTXT_KD_VALD_STRT_DT,
        BLTXT_KD_VALD_END_DT,
        UTL_RAW.CAST_TO_RAW(BLTXT_RCP_PROD_NO) AS BLTXT_RCP_PROD_NO ,
        UTL_RAW.CAST_TO_RAW(SCUR_MAIL_RCP_YN) AS SCUR_MAIL_RCP_YN ,
        UTL_RAW.CAST_TO_RAW(BILL_EMAIL_ADDR) AS BILL_EMAIL_ADDR ,
        UTL_RAW.CAST_TO_RAW(BILL_ACNT_STTS_CD) AS BILL_ACNT_STTS_CD ,
        BILL_ACNT_STTS_CHNG_DTTM,
        ACNT_BLNC,
        UTL_RAW.CAST_TO_RAW(NTHNG_RTNG_PRSS_TRGT_YN) AS NTHNG_RTNG_PRSS_TRGT_YN ,
        UTL_RAW.CAST_TO_RAW(BRLL_BLTXT_RQST_YN) AS BRLL_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(BLTXT_ACNT_IDC_DENY_YN) AS BLTXT_ACNT_IDC_DENY_YN ,
        UTL_RAW.CAST_TO_RAW(PPAY_ACNT_YN) AS PPAY_ACNT_YN ,
        INTG_BILL_TRGT_ACNT_NO,
        UTL_RAW.CAST_TO_RAW(MRGR_BILL_NO) AS MRGR_BILL_NO ,
        BILL_CYCL_CD,
        CHNG_AFT_BILL_CYCL_CD,
        BLPROC_SRLNO,
        CHNG_AFT_BILL_CYCL_CD_APLY_DT,
        LAST_BILL_STRT_DT,
        UTL_RAW.CAST_TO_RAW(BLPROC_DV_CD) AS BLPROC_DV_CD ,
        BLPROC_DV_CHNG_DTTM,
        BILL_END_DT,
        BILL_STRT_DT,
        LAST_BILL_TRGT_TERM_END_DT,
        LAST_BILL_CYCL_CD,
        CPCNT_BILL_TRGT_MME_DT,
        BLPROC_CNCL_TRGT_BGMM_DT,
        CPCNT_BILL_CYCL_CD,
        UTL_RAW.CAST_TO_RAW(BLTXT_RSV_RSN_CD) AS BLTXT_RSV_RSN_CD ,
        BLTXT_RSV_VALD_STRT_DT,
        BLTXT_RSV_VALD_END_DT,
        BLTXT_RSV_RECV,
        BLTXT_RSV_OPRTR,
        UTL_RAW.CAST_TO_RAW(BLTXT_DUP_SEND_YN) AS BLTXT_DUP_SEND_YN ,
        UTL_RAW.CAST_TO_RAW(BLPROC_DTTM_RSV_YN) AS BLPROC_DTTM_RSV_YN ,
        MNTH_BLPROC_CNT,
        UTL_RAW.CAST_TO_RAW(BILL_PRSS_MEDIA_KD_CD) AS BILL_PRSS_MEDIA_KD_CD ,
        UTL_RAW.CAST_TO_RAW(INTCAL_DTL_DTL_BLTXT_RQST_YN) AS INTCAL_DTL_DTL_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(EMAIL_BLTXT_EXPRY_RQST_DV_CD) AS EMAIL_BLTXT_EXPRY_RQST_DV_CD ,
        UTL_RAW.CAST_TO_RAW(EMAIL_BLTXT_RETN_RSN_CD) AS EMAIL_BLTXT_RETN_RSN_CD ,
        UTL_RAW.CAST_TO_RAW(DM_AD_GDS_XCLN_YN) AS DM_AD_GDS_XCLN_YN ,
        REP_ENTR_ID,
        UTL_RAW.CAST_TO_RAW(SPRTBL_TRGT_BILL_ACNT_YN) AS SPRTBL_TRGT_BILL_ACNT_YN ,
        BILL_ACNT_GRP_NO,
        UTL_RAW.CAST_TO_RAW(MRGR_BILL_PRMS_YN) AS MRGR_BILL_PRMS_YN ,
        UTL_RAW.CAST_TO_RAW(BILL_PRSS_XCLN_YN) AS BILL_PRSS_XCLN_YN ,
        UTL_RAW.CAST_TO_RAW(TAX_BILL_ISUE_YN) AS TAX_BILL_ISUE_YN ,
        STTS_CHNG_DT,
        LAST_BLPROC_SRLNO,
        UTL_RAW.CAST_TO_RAW(VIP_BLTXT_CD) AS VIP_BLTXT_CD ,
        BILL_ACNT_ACT_DT,
        UTL_RAW.CAST_TO_RAW(BLTXT_KD_CHNG_DV_CD) AS BLTXT_KD_CHNG_DV_CD ,
        UTL_RAW.CAST_TO_RAW(BLTXT_KD_CHNG_DLR_CD) AS BLTXT_KD_CHNG_DLR_CD ,
        UTL_RAW.CAST_TO_RAW(SLVR_BILL_RQST_YN) AS SLVR_BILL_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(NMTH_DUED_YN) AS NMTH_DUED_YN ,
        NMTH_DUED_VALD_STRT_DT,
        NMTH_DUED_VALD_END_DT,
        UTL_RAW.CAST_TO_RAW(SMS_MSNGR) AS SMS_MSNGR ,
        UTL_RAW.CAST_TO_RAW(ENG_BLTXT_RQST_YN) AS ENG_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(PRODMASK_BLTXT_RQST_YN) AS PRODMASK_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(WIRELESS_DEV_BLTXT_RQST_YN) AS WIRELESS_DEV_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(TAXI_BLTXT_RQST_YN) AS TAXI_BLTXT_RQST_YN ,
        UTL_RAW.CAST_TO_RAW(EMAIL_MBGR_BILL_YN) AS EMAIL_MBGR_BILL_YN ,
        EMAL_MRGR_BILL_ACNT_ID ,
        EMAIL_MBGR_STRT_DT,
        EMAIL_MBGR_END_DT,
        UTL_RAW.CAST_TO_RAW(BILL_ACNT_STTS_CHNG_RSN_CD) AS BILL_ACNT_STTS_CHNG_RSN_CD ,
        UTL_RAW.CAST_TO_RAW(BILL_ACNT_STTS_CHNG_RDTL_CD) AS BILL_ACNT_STTS_CHNG_RDTL_CD ,
        UTL_RAW.CAST_TO_RAW(BILL_CUR_CD) AS BILL_CUR_CD ,
        UTL_RAW.CAST_TO_RAW(ATST_DSCNT_YN) AS ATST_DSCNT_YN ,
        UTL_RAW.CAST_TO_RAW(SELNG_DV_CD) AS SELNG_DV_CD ,
        UTL_RAW.CAST_TO_RAW(AMGT_BLTXT_DIRT_SEND_YN) AS AMGT_BLTXT_DIRT_SEND_YN ,
        UTL_RAW.CAST_TO_RAW(LGUPLUS_NO_YN) AS LGUPLUS_NO_YN ,
        UTL_RAW.CAST_TO_RAW(PRMAN_YN) AS PRMAN_YN ,
        TEL_REP_ENTR_NO,
        UTL_RAW.CAST_TO_RAW(ENPR_DV_CD) AS ENPR_DV_CD ,
        UTL_RAW.CAST_TO_RAW(BILL_WORK_KD_CD) AS BILL_WORK_KD_CD ,
        UTL_RAW.CAST_TO_RAW(APCNT_NM) AS APCNT_NM ,
        UTL_RAW.CAST_TO_RAW(APCNT_TELNO) AS APCNT_TELNO ,
        UTL_RAW.CAST_TO_RAW(OWNR_APCNT_RELS_CD) AS OWNR_APCNT_RELS_CD ,
        UTL_RAW.CAST_TO_RAW(FCUR_RFLCT_DD) AS FCUR_RFLCT_DD ,
        UTL_RAW.CAST_TO_RAW(VAT_GRNT_CD) AS VAT_GRNT_CD ,
        DVACCOUNTID,
        DVCSSACCOUNTID,
        UTL_RAW.CAST_TO_RAW(FRST_WDRW_RGST_DD) AS FRST_WDRW_RGST_DD ,
        UTL_RAW.CAST_TO_RAW(FCUR_CALC_BASE_CD) AS FCUR_CALC_BASE_CD ,
        UTL_RAW.CAST_TO_RAW(CSS_BILL_ACNT_ID ) AS CSS_BILL_ACNT_ID  ,
        UTL_RAW.CAST_TO_RAW(DETL_DTL_XCLN_YN) AS DETL_DTL_XCLN_YN ,
        UCUBE_BILL_ACNT_NO,
        UTL_RAW.CAST_TO_RAW(DUMMY_DV_CD) AS DUMMY_DV_CD ,
        UTL_RAW.CAST_TO_RAW(ISCT_COMM_YN) AS ISCT_COMM_YN ,
        ENTR_ID ENTR_NO,
        UTL_RAW.CAST_TO_RAW(DATA_INPS_ID) AS DATA_INPS_ID ,
        DATA_INPT_DTTM,
        UTL_RAW.CAST_TO_RAW(DATA_INPT_PGM_ID) AS DATA_INPT_PGM_ID ,
        UTL_RAW.CAST_TO_RAW(DATA_MFPN_ID) AS DATA_MFPN_ID ,
        DATA_UPD_DTTM,
        UTL_RAW.CAST_TO_RAW(DATA_UPD_PGM_ID) AS DATA_UPD_PGM_ID 
  FROM PMPBADM.TB_PMPB_SB_BILL_ACNT_I B
 ) 
 ;
*/ 


CREATE TABLE ERR_TB_STC_IFUSF_ENPR_ORG
AS
SELECT SEQ,RTNG_PREFIX_CD,SVC_POFN,SVC_TELNO,SVC_STRT_DT
FROM
(
SELECT /*+ FULL(A) PARALLEL(A 8) */ * 
  FROM  VW_STC_IFUSF_ENPR_ORG A 
 WHERE EXISTS(SELECT /*+ HASH_SJ FULL(C) PARALLEL(C 8) */ 'Y' 
                FROM PMPBADM.TB_STC_IFUSF_ENPR_ORG C 
               WHERE C.SEQ = A.SEQ
                 AND C.RTNG_PREFIX_CD = A.RTNG_PREFIX_CD
                 AND C.SVC_POFN = A.SVC_POFN
                 AND C.SVC_TELNO = A.SVC_TELNO
                 AND C.SVC_STRT_DT = A.SVC_STRT_DT)
 MINUS
SELECT /*+ FULL(B) PARALLEL(B 8) */
       SEQ,
       RTNG_PREFIX_CD ,
       SVC_POFN ,
       SVC_TELNO ,
       SVC_STRT_DT ,
       UTL_RAW.CAST_TO_RAW(SVC_END_DT) AS SVC_END_DT ,
       UTL_RAW.CAST_TO_RAW(BS_REG_NO) AS BS_REG_NO ,
       UTL_RAW.CAST_TO_RAW(CMPNY_NM) AS CMPNY_NM ,
       UTL_RAW.CAST_TO_RAW(ENPR_NM) AS ENPR_NM ,
       UTL_RAW.CAST_TO_RAW(ENPR_ADDR) AS ENPR_ADDR ,
       UTL_RAW.CAST_TO_RAW(INKND_DV) AS INKND_DV ,
       UTL_RAW.CAST_TO_RAW(INKND_DTL_DV) AS INKND_DTL_DV ,
       UTL_RAW.CAST_TO_RAW(TAX_KD_DV) AS TAX_KD_DV ,
       UTL_RAW.CAST_TO_RAW(KT_DV) AS KT_DV ,
       UTL_RAW.CAST_TO_RAW(SVC_KD) AS SVC_KD ,
       UTL_RAW.CAST_TO_RAW(STACC_YM) AS STACC_YM ,
       UTL_RAW.CAST_TO_RAW(PTN_ID) AS PTN_ID ,
       WORK_DTTM
  FROM TB_STC_IFUSF_ENPR_ORG B
  );
  
CREATE TABLE ERR_TB_STB_RNT_SBGN_HIST
AS
SELECT GTHR_YM, LNKG_SYS_CD, LNKG_DV_CD, RNT_MGMT_NO, RNT_SEQ, LINE_NO 
FROM
(
SELECT /*+ FULL(A) PARALLEL(A 8) */ * 
  FROM  VW_TB_STB_RNT_SBGN_HIST A 
 WHERE EXISTS(SELECT /*+ HASH_SJ FULL(C) PARALLEL(C 8) */ 'Y' 
                FROM PMPBADM.TB_STB_RNT_SBGN_HIST C 
               WHERE C.GTHR_YM = A.GTHR_YM
                 AND C.LNKG_SYS_CD = A.LNKG_SYS_CD
                 AND C.LNKG_DV_CD = A.LNKG_DV_CD
                 AND C.RNT_MGMT_NO = A.RNT_MGMT_NO
                 AND C.RNT_SEQ = A.RNT_SEQ
                 AND C.LINE_NO = A.LINE_NO)
 MINUS
SELECT /*+ FULL(B) PARALLEL(B 8) */
       GTHR_YM ,
       LNKG_SYS_CD ,
       LNKG_DV_CD ,
       RNT_MGMT_NO ,
       RNT_SEQ,
       LINE_NO ,
       UTL_RAW.CAST_TO_RAW(RNT_STAT_CD) AS RNT_STAT_CD ,
       UTL_RAW.CAST_TO_RAW(ENPR_NO) AS ENPR_NO ,
       UTL_RAW.CAST_TO_RAW(ENPR_NM) AS ENPR_NM ,
       UTL_RAW.CAST_TO_RAW(HPOS_ITO_NM) AS HPOS_ITO_NM ,
       UTL_RAW.CAST_TO_RAW(HPOS_ITO_ADDR) AS HPOS_ITO_ADDR ,
       UTL_RAW.CAST_TO_RAW(HPOS_ITO_INTG_ITO_ID) AS HPOS_ITO_INTG_ITO_ID ,
       UTL_RAW.CAST_TO_RAW(LPOS_ITO_NM) AS LPOS_ITO_NM ,
       UTL_RAW.CAST_TO_RAW(LPOS_ITO_ADDR) AS LPOS_ITO_ADDR ,
       UTL_RAW.CAST_TO_RAW(LPOS_ITO_INTG_ITO_ID) AS LPOS_ITO_INTG_ITO_ID ,
       UTL_RAW.CAST_TO_RAW(HDLNG_ITO_CD) AS HDLNG_ITO_CD ,
       UTL_RAW.CAST_TO_RAW(HDLNG_ITO_NM) AS HDLNG_ITO_NM ,
       UTL_RAW.CAST_TO_RAW(BROFF_CD) AS BROFF_CD ,
       UTL_RAW.CAST_TO_RAW(BROFF_NM) AS BROFF_NM ,
       UTL_RAW.CAST_TO_RAW(TLBLDG_CD) AS TLBLDG_CD ,
       UTL_RAW.CAST_TO_RAW(TLBLDG_NM) AS TLBLDG_NM ,
       UTL_RAW.CAST_TO_RAW(SSCRB_NO) AS SSCRB_NO ,
       UTL_RAW.CAST_TO_RAW(SSCRB_NM) AS SSCRB_NM ,
       UTL_RAW.CAST_TO_RAW(FRST_SBGN_DD) AS FRST_SBGN_DD ,
       UTL_RAW.CAST_TO_RAW(SBGN_DT) AS SBGN_DT ,
       UTL_RAW.CAST_TO_RAW(CHNG_DT) AS CHNG_DT ,
       UTL_RAW.CAST_TO_RAW(EXPRY_DT) AS EXPRY_DT ,
       UTL_RAW.CAST_TO_RAW(EXPRY_RQST_CRTE_DT) AS EXPRY_RQST_CRTE_DT ,
       UTL_RAW.CAST_TO_RAW(EXPRY_RQST_LAST_PRNT_DT) AS EXPRY_RQST_LAST_PRNT_DT ,
       UTL_RAW.CAST_TO_RAW(EXPRY_RQST_LAST_PRNT_NM) AS EXPRY_RQST_LAST_PRNT_NM ,
       UTL_RAW.CAST_TO_RAW(COST_ACNT_CD) AS COST_ACNT_CD ,
       UTL_RAW.CAST_TO_RAW(COST_ACNT_NM) AS COST_ACNT_NM ,
       UTL_RAW.CAST_TO_RAW(SBGN_CHRGR_NM) AS SBGN_CHRGR_NM ,
       UTL_RAW.CAST_TO_RAW(BIZ_CHRGR_NM) AS BIZ_CHRGR_NM ,
       UTL_RAW.CAST_TO_RAW(CHRG_LOCALE_CD) AS CHRG_LOCALE_CD ,
       UTL_RAW.CAST_TO_RAW(SPEED_VAL) AS SPEED_VAL ,
       UTL_RAW.CAST_TO_RAW(DSTNC_DV_CD) AS DSTNC_DV_CD ,
       DSTNC_VAL,
       UTL_RAW.CAST_TO_RAW(RAIL_DV_CD) AS RAIL_DV_CD ,
       UTL_RAW.CAST_TO_RAW(WIRE_TYPE_DV_CD) AS WIRE_TYPE_DV_CD ,
       UTL_RAW.CAST_TO_RAW(LINE_USG_DV_CD) AS LINE_USG_DV_CD ,
       UTL_RAW.CAST_TO_RAW(LNWLS_DV_CD) AS LNWLS_DV_CD ,
       UTL_RAW.CAST_TO_RAW(MSVC_ENTR_ID) AS MSVC_ENTR_NO ,
       UTL_RAW.CAST_TO_RAW(MSVC_NM) AS MSVC_NM ,
       UTL_RAW.CAST_TO_RAW(MSVC_STAT_CD) AS MSVC_STAT_CD ,
       UTL_RAW.CAST_TO_RAW(MSVC_STAT_NM) AS MSVC_STAT_NM ,
       MSVC_CHRG_AMT,
       UTL_RAW.CAST_TO_RAW(CORP_RQST_NO) AS CORP_RQST_NO ,
       UTL_RAW.CAST_TO_RAW(NOTC_SHT_NO) AS NOTC_SHT_NO ,
       UTL_RAW.CAST_TO_RAW(ATRCT_MAN_NM) AS ATRCT_MAN_NM ,
       UTL_RAW.CAST_TO_RAW(ATRCT_DEPT) AS ATRCT_DEPT ,
       UTL_RAW.CAST_TO_RAW(PMNT_MAN_NO) AS PMNT_MAN_NO ,
       UTL_RAW.CAST_TO_RAW(RNT_DV_CD) AS RNT_DV_CD ,
       UTL_RAW.CAST_TO_RAW(EQPM_DV_CD) AS EQPM_DV_CD ,
       UTL_RAW.CAST_TO_RAW(EQPM_STND_CD) AS EQPM_STND_CD ,
       EQPM_QTY,
       UPR_AMT,
       EXPT_CHRG_AMT,
       UTL_RAW.CAST_TO_RAW(ESTB_CHNG_YN) AS ESTB_CHNG_YN ,
       UTL_RAW.CAST_TO_RAW(ESTB_CHNG_NM) AS ESTB_CHNG_NM ,
       UTL_RAW.CAST_TO_RAW(RSV1) AS RSV1 ,
       UTL_RAW.CAST_TO_RAW(RSV2) AS RSV2 ,
       UTL_RAW.CAST_TO_RAW(RSV3) AS RSV3 ,
       UTL_RAW.CAST_TO_RAW(RSV4) AS RSV4 ,
       UTL_RAW.CAST_TO_RAW(RSV5) AS RSV5 ,
       WORK_DTTM,
       UTL_RAW.CAST_TO_RAW(TEAM_CD) AS TEAM_CD ,
       UTL_RAW.CAST_TO_RAW(MSVC_CD) AS MSVC_CD ,
       UTL_RAW.CAST_TO_RAW(KTIX) AS KTIX ,
       UTL_RAW.CAST_TO_RAW(LINE_TYPE) AS LINE_TYPE ,
       UTL_RAW.CAST_TO_RAW(SEND_DT) AS SEND_DT ,
       UTL_RAW.CAST_TO_RAW(ENTR_RCGN_NO2) AS ENTR_RCGN_NO2
  FROM TB_STB_RNT_SBGN_HIST B
  );  
  


/*
SELECT * FROM USER_TABLES@DL_PNUDB ORDER BY 1;

ERR_TB_PMPB_SB_BILL_ACNT_I
ERR_TB_STB_RNT_SBGN_HIST
ERR_TB_STC_IFUSF_ENPR_ORG

STADM	TB_STC_IFUSF_ENPR_ORG
STADM	TB_STB_RNT_SBGN_HIST
PMPBADM	TB_PMPB_SB_BILL_ACNT_I
*/


SELECT * FROM PMPBADM.TB_PMPB_SB_BILL_ACNT_I WHERE BILL_ACNT_NO IN (SELECT * FROM ERR_TB_PMPB_SB_BILL_ACNT_I@DL_PNUDB);


SELECT /*+ LEADING(@SUB A) USE_NL(A) INDEX_RS(A STC_IFUSF_ENPR_ORG_PK) */*
  FROM STADM.TB_STC_IFUSF_ENPR_ORG A
 WHERE (SEQ,
        RTNG_PREFIX_CD,
        SVC_POFN,
        SVC_TELNO,
        SVC_STRT_DT) IN (SELECT /*+ QB_NAME(SUB) */
                                SEQ,
                                RTNG_PREFIX_CD,
                                SVC_POFN,
                                SVC_TELNO,
                                SVC_STRT_DT B
                           FROM ERR_TB_STC_IFUSF_ENPR_ORG@DL_PNUDB B);
						   


SELECT /*+ LEADING(@SUB A) USE_NL(A) INDEX_RS(A STB_RNT_SBGN_HIST_PK) */ *
  FROM STADM.TB_STB_RNT_SBGN_HIST A
 WHERE (GTHR_YM,LNKG_SYS_CD,LNKG_DV_CD,RNT_MGMT_NO,RNT_SEQ,LINE_NO) 
                                                                   IN (SELECT /*+ QB_NAME(SUB) */         
                                                                               GTHR_YM,
                                                                               LNKG_SYS_CD,
                                                                               LNKG_DV_CD,
                                                                               RNT_MGMT_NO,
                                                                               RNT_SEQ,
                                                                               LINE_NO
                                                                          FROM ERR_TB_STB_RNT_SBGN_HIST@DL_PNUDB B);