WITH T AS (
    SELECT 1 AS NUM,'이대호' AS NAME FROM DUAL UNION ALL
    SELECT 3 AS NUM,'이승엽' AS NAME FROM DUAL UNION ALL
    SELECT 2 AS NUM,'양준혁' AS NAME FROM DUAL UNION ALL
    SELECT 5 AS NUM,'박용택' AS NAME FROM DUAL UNION ALL
    SELECT 4 AS NUM,'이종범' AS NAME FROM DUAL
) 
--SELECT LISTAGG(T.NAME, ',') WITHIN GROUP(ORDER BY NUM) FROM T;
SELECT MAX(DECODE(NUM,1,NAME,NULL))
     , MAX(DECODE(NUM,2,NAME,NULL))
     , MAX(DECODE(NUM,3,NAME,NULL))
     , MAX(DECODE(NUM,4,NAME,NULL))
     , MAX(DECODE(NUM,5,NAME,NULL))
FROM T;