WITH PRP_TEST AS (
     SELECT 1 AS ID, 1 AS CUSTOMER_ID, 'A' AS PRODUCT_CODE, 10 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 2 AS ID, 1 AS CUSTOMER_ID, 'B' AS PRODUCT_CODE, 20 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 3 AS ID, 1 AS CUSTOMER_ID, 'C' AS PRODUCT_CODE, 30 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 4 AS ID, 2 AS CUSTOMER_ID, 'A' AS PRODUCT_CODE, 40 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 5 AS ID, 2 AS CUSTOMER_ID, 'C' AS PRODUCT_CODE, 50 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 6 AS ID, 2 AS CUSTOMER_ID, 'A' AS PRODUCT_CODE, 60 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 7 AS ID, 3 AS CUSTOMER_ID, 'B' AS PRODUCT_CODE, 70 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 8 AS ID, 3 AS CUSTOMER_ID, 'C' AS PRODUCT_CODE, 80 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 9 AS ID, 3 AS CUSTOMER_ID, 'D' AS PRODUCT_CODE, 90 AS QUANTITY FROM DUAL
      UNION ALL
     SELECT 10 AS ID, 4 AS CUSTOMER_ID, 'A' AS PRODUCT_CODE, 100 AS QUANTITY FROM DUAL
)
SELECT ID, CUSTOMER_ID, PRODUCT_CODE, QUANTITY
  FROM (SELECT ROWNUM NO, A.*
          FROM (SELECT ID, CUSTOMER_ID, PRODUCT_CODE, QUANTITY
                  FROM PRP_TEST
                 ORDER BY QUANTITY DESC) A
         WHERE ROWNUM <= :PAGE_NO * 20) B
 WHERE B.NO >= (:PAGE_NO - 1) * 20 + 1
;