SELECT * FROM DICTIONARY;


SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_TABLES WHERE TABLESPACE_NAME = 'USERS';


CREATE TABLE SOURCE
AS
SELECT ROWNUM AS NO FROM DUAL CONNECT BY LEVEL <= 100000;
DROP TABLE SOURCE;



