CREATE SCHEMA HKG_TEST;

CREATE TABLE HKG_TEST.HKG_TEST(
	C1 INTEGER COMMENT 'C1'
) PARTITION BY LIST (C1) (
	PARTITION NO1 VALUES IN (1),
	PARTITION NO2 VALUES IN (2)
);
INSERT INTO HKG_TEST.HKG_TEST(C1) VALUES (1);
INSERT INTO HKG_TEST.HKG_TEST(C1) VALUES (2);
COMMIT;
SELECT * FROM HKG_TEST.HKG_TEST;

TRUNCATE TABLE HKG_TEST.HKG_TEST;

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HKG_TEST';
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HKG_TEST';
SELECT * FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_NAME = 'HKG_TEST';


DROP TABLE HKG_TEST.HKG_TEST;
DROP SCHEMA HKG_TEST;