

SELECT 
       A.ROUTINE_CATALOG
     , A.ROUTINE_SCHEMA
	 , A.ROUTINE_NAME
	 , A.ROUTINE_TYPE
	 , A.CREATED
	 , A.LAST_ALTERED
	 , B.REFERENCED_SERVER_NAME
	 , B.REFERENCED_DATABASE_NAME
	 , B.REFERENCED_ENTITY_NAME
	 , B.REFERENCED_MINOR_NAME
	 , A.ROUTINE_BODY
	 , A.ROUTINE_DEFINITION
     --, * 
  FROM (
         SELECT * FROM INFORMATION_SCHEMA.ROUTINES (NOLOCK)
          WHERE 1=1
            AND SPECIFIC_SCHEMA = 'DBO'
            AND SPECIFIC_NAME NOT IN (
                ''  -- 프로시저 / 함수 자체에 문법 오류가 있거나 없는 테이블을 참조하면 DM_SQL_REFERENCED_ENTITIES 함수에 입력할 때 오류 발생한다. 그래서 제외함.
              )
     ) A
 CROSS APPLY SYS.DM_SQL_REFERENCED_ENTITIES(A.SPECIFIC_SCHEMA+ '.' + A.SPECIFIC_NAME, 'OBJECT')  B
 WHERE B.REFERENCED_DATABASE_NAME = 'COMMONDB'

 



SELECT 
       A.ROUTINE_CATALOG
     , A.ROUTINE_SCHEMA
	 , A.ROUTINE_NAME
	 , A.ROUTINE_TYPE
	 , A.CREATED
	 , A.LAST_ALTERED
	 , B.REFERENCED_SERVER_NAME
	 , B.REFERENCED_DATABASE_NAME
	 , B.REFERENCED_ENTITY_NAME
	 --, B.REFERENCED_MINOR_NAME
	 , A.ROUTINE_BODY
	 , A.ROUTINE_DEFINITION
     --, * 
  FROM (
         SELECT * FROM INFORMATION_SCHEMA.ROUTINES (NOLOCK)
          WHERE 1=1
            AND SPECIFIC_SCHEMA = 'DBO'
            AND SPECIFIC_NAME NOT IN (
                ''  -- 프로시저 / 함수 자체에 문법 오류가 있거나 없는 테이블을 참조하면 DM_SQL_REFERENCED_ENTITIES 함수에 입력할 때 오류 발생한다. 그래서 제외함.
              )
     ) A
 CROSS APPLY SYS.DM_SQL_REFERENCED_ENTITIES(A.SPECIFIC_SCHEMA+ '.' + A.SPECIFIC_NAME, 'OBJECT')  B
 WHERE 1=1
   AND B.REFERENCED_DATABASE_NAME IS NOT NULL
 GROUP BY A.ROUTINE_CATALOG, A.ROUTINE_SCHEMA, A.ROUTINE_NAME, A.ROUTINE_TYPE, A.CREATED, A.LAST_ALTERED, B.REFERENCED_SERVER_NAME, B.REFERENCED_DATABASE_NAME, B.REFERENCED_ENTITY_NAME, A.ROUTINE_BODY, A.ROUTINE_DEFINITION
 ORDER BY A.ROUTINE_CATALOG, A.ROUTINE_SCHEMA, A.ROUTINE_NAME, A.ROUTINE_TYPE, A.CREATED, A.LAST_ALTERED, B.REFERENCED_SERVER_NAME, B.REFERENCED_DATABASE_NAME, B.REFERENCED_ENTITY_NAME, A.ROUTINE_BODY, A.ROUTINE_DEFINITION
