DROP TABLE HKG_TEST
DROP TABLE NW_HKG_TEST

CREATE TABLE HKG_TEST (C1 INT)
CREATE TABLE NW_HKG_TEST (C1 INT)

INSERT INTO NW_HKG_TEST VALUES (11)
EXEC SP_RENAME 'dbo.HKG_TEST', 'NW_HKG_TEST';	EXEC SP_RENAME 'dbo.ZZ_HKG_TEST', 'HKG_TEST';
SELECT TOP 100 * FROM NW_HKG_TEST
SELECT TOP 100 * FROM HKG_TEST


EXEC SP_RENAME 'dbo.HKG_TEST', 'ZZ_HKG_TEST';	EXEC SP_RENAME 'dbo.NW_HKG_TEST', 'HKG_TEST';
SELECT TOP 100 * FROM HKG_TEST
SELECT TOP 100 * FROM ZZ_HKG_TEST