-- You need to inquire whether 10000 is big enough to start the new sequence.
-- Start numbers of sequences cannot be altered; they have to be dropped and recreated.

SELECT A.SEQUENCE_OWNER TOBE_OWNER
     , B.SEQUENCE_OWNER ASIS_OWNER
     , A.SEQUENCE_NAME
     , A.MIN_VALUE
     , A.MAX_VALUE
     , A.INCREMENT_BY
     , A.CYCLE_FLAG
     , A.ORDER_FLAG
     , A.CACHE_SIZE
     , A.LAST_NUMBER TOBE_LAST_NUM
     , B.LAST_NUMBER ASIS_LAST_NUM
     , A.LAST_NUMBER - B.LAST_NUMBER AS "TOBE-ASIS_LAST_NUM_DIFF"
     , CASE WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'N'
            THEN B.LAST_NUMBER + 10000
            WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'Y' AND B.LAST_NUMBER + 10000 > A.MAX_VALUE
            THEN 1
            WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'Y' AND B.LAST_NUMBER + 10000 < = A.MAX_VALUE
            THEN B.LAST_NUMBER + 10000
            ELSE A.LAST_NUMBER
       END NEW_LAST_NUM
     , 'DROP SEQUENCE ' || A.SEQUENCE_OWNER || '.' || A.SEQUENCE_NAME || ';' AS DROP_DDL
     , 'CREATE SEQUENCE ' || A.SEQUENCE_OWNER || '.' || A.SEQUENCE_NAME || ' INCREMENT BY ' || A.INCREMENT_BY || ' START WITH ' || 
       CASE WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'N'
            THEN B.LAST_NUMBER + 10000
            WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'Y' AND B.LAST_NUMBER + 10000 > A.MAX_VALUE
            THEN 1
            WHEN A.LAST_NUMBER <  B.LAST_NUMBER AND A.CYCLE_FLAG = 'Y' AND B.LAST_NUMBER + 10000 < = A.MAX_VALUE
            THEN B.LAST_NUMBER + 10000
            ELSE A.LAST_NUMBER
       END || ' MINVALUE ' || A.MIN_VALUE || ' MAXVALUE ' || A.MAX_VALUE || DECODE(A.CYCLE_FLAG, 'Y', ' CYCLE ', 'N', ' NOCYCLE ') || 'CACHE ' || A.CACHE_SIZE || ';' AS CREATE_DDL
  FROM DBA_SEQUENCES A
     , DBA_SEQUENCES@DL_PUSET1 B
 WHERE A.SEQUENCE_OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND A.SEQUENCE_NAME = B.SEQUENCE_NAME (+)
   AND B.SEQUENCE_OWNER < > 'SYS'
   AND A.LAST_NUMBER <  B.LAST_NUMBER
 ORDER BY 1,2,3;