/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장
* 저장일     : 2022-01-25
*/

CREATE TABLE MIG_USER.MSJ_MIG_INDEX_LOG
(
    TABLE_NAME      VARCHAR2(128),
    INDEX_NAME      VARCHAR2(4000),
    MIG_START_DT    DATE,
    MIG_END_DT      DATE,
    JOB_RESULT      VARCHAR2(4000)
)
TABLESPACE TS_MIG_USER_D01
NOCOMPRESS;