/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장
* 저장일     : 2022-01-25
*/


SELECT 'SELECT '||TOBE_COLUMN_NAME||' FROM ADM_USER2.'||TABLE_NAME||'@DB_LINK ;' FROM MSJ_MIG_RULE WHERE ASIS_COLUMN_NAME='NULL';
/*
TRUNCATE TABLE MSJ_MIG_JOB_LOG;
INSERT INTO MSJ_MIG_JOB_LOG(TABLE_NAME)
SELECT TABLE_NAME FROM MSJ_MIG_TABLE WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL;
*/

SELECT * FROM MSJ_MIG_TABLE A WHERE (A.MIG_TYPE IN ('A','B','C') OR A.MIG_TYPE IS NULL);

TRUNCATE TABLE MIG_USER.MSJ_PK_COLUMN;
-- CREATE TABLE MIG_USER.MSJ_PK_COLUMN AS
INSERT INTO MIG_USER.MSJ_PK_COLUMN
SELECT TABLE_NAME,INDEX_NAME,COLUMN_NAME 
 FROM DBA_IND_COLUMNS 
WHERE INDEX_OWNER ='ADM_USER' 
  AND INDEX_NAME IN (
					 SELECT /*+ UNNEST */
						    DISTINCT B.INDEX_NAME
					   FROM MIG_USER.MSJ_MIG_TABLE A
						  , DBA_INDEXES           B
						  , DBA_CONSTRAINTS       C
					  WHERE A.TOBE_TABLE_NAME = B.TABLE_NAME
					    AND (A.MIG_TYPE IN ('A','B','C') OR A.MIG_TYPE IS NULL)
					    AND B.OWNER ='ADM_USER'
					    AND B.UNIQUENESS='UNIQUE'
					    AND B.INDEX_NAME = C.INDEX_NAME
					    AND B.OWNER = C.OWNER
					    AND C.CONSTRAINT_TYPE='P'
					 )
 ORDER BY TABLE_NAME,INDEX_NAME,COLUMN_POSITION;

SELECT COUNT(*) FROM  -- 1482 ,FBI(2개)
(
SELECT 'CREATE '||DECODE(UNIQUENESS,'UNIQUE','UNIQUE ',NULL)||'INDEX ADM_USER.'||INDEX_NAME||' ON ADM_USER.'||TABLE_NAME||INDEX_SQL||' TABLESPACE '||TABLESPACE_NAME||CASE WHEN DEGREE > 1 THEN ' PARALLEL 8 NOLOGGING ' ELSE ' NOLOGGING ' END ||DECODE(PART_YN,'Y','LOCAL',NULL)||';'||CHR(13)||CHR(10)||
       'ALTER INDEX ADM_USER.'||INDEX_NAME||' LOGGING NOPARALLEL;'
  FROM
	(
	SELECT B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
		   DECODE(D.TABLE_NAME,NULL,'N','Y') PART_YN,
		   '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS INDEX_SQL
		   ,C.DEGREE
           ,NVL(D.DEF_TABLESPACE_NAME,B.TABLESPACE_NAME) TABLESPACE_NAME
	  FROM DBA_IND_COLUMNS A,
		   DBA_INDEXES B,
           (SELECT DISTINCT TABLE_NAME,DEGREE,MIG_TYPE,INST_ID FROM MIG_USER.MSJ_MIG_TABLE) C,
           DBA_PART_INDEXES D
	 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TABLE_NAME
	   AND B.INDEX_TYPE='NORMAL'
	   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
       AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
       AND B.OWNER = D.OWNER(+)
       AND B.INDEX_NAME = D.INDEX_NAME(+)
	 GROUP 
		BY B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
           D.TABLE_NAME,
           D.DEF_TABLESPACE_NAME,
           B.TABLESPACE_NAME,
           C.DEGREE
	)       
);

TRUNCATE TABLE MSJ_MIG_INDEX_LOG; --1484
INSERT INTO MSJ_MIG_INDEX_LOG(TABLE_NAME,INDEX_NAME)
SELECT TABLE_NAME,
       INDEX_NAME
  FROM
	(
	SELECT B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
		   DECODE(D.TABLE_NAME,NULL,'N','Y') PART_YN,
		   '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS INDEX_SQL
		   ,C.DEGREE
           ,NVL(D.DEF_TABLESPACE_NAME,B.TABLESPACE_NAME) TABLESPACE_NAME
	  FROM DBA_IND_COLUMNS A,
		   DBA_INDEXES B,
           (SELECT DISTINCT TABLE_NAME,DEGREE,MIG_TYPE,INST_ID FROM MIG_USER.MSJ_MIG_TABLE WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL) C,
           DBA_PART_INDEXES D
	 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TABLE_NAME
	   AND B.INDEX_TYPE < >'LOB'
	   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
       AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
       AND B.OWNER = D.OWNER(+)
       AND B.INDEX_NAME = D.INDEX_NAME(+)
	 GROUP 
		BY B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
           D.TABLE_NAME,
           D.DEF_TABLESPACE_NAME,
           B.TABLESPACE_NAME,
           C.DEGREE
	) ;      
COMMIT;	
TRUNCATE TABLE MSJ_MIG_INDEX;
INSERT INTO MSJ_MIG_INDEX  -- 1484
SELECT TABLE_NAME,
       INDEX_NAME,
       TO_CHAR('CREATE '||DECODE(UNIQUENESS,'UNIQUE','UNIQUE ',NULL)||'INDEX ADM_USER.'||INDEX_NAME||' ON ADM_USER.'||TABLE_NAME||INDEX_SQL||' TABLESPACE '||TABLESPACE_NAME||CASE WHEN DEGREE > 1 THEN ' PARALLEL 8 NOLOGGING ' ELSE ' NOLOGGING ' END ||DECODE(PART_YN,'Y','LOCAL',NULL))  AS INDEX_SQL
  FROM
	(
	SELECT B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
		   DECODE(D.TABLE_NAME,NULL,'N','Y') PART_YN,
		   '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS INDEX_SQL
		   ,C.DEGREE
           ,NVL(D.DEF_TABLESPACE_NAME,B.TABLESPACE_NAME) TABLESPACE_NAME
	  FROM DBA_IND_COLUMNS A,
		   DBA_INDEXES B,
           (SELECT DISTINCT TABLE_NAME,DEGREE,MIG_TYPE,INST_ID FROM MIG_USER.MSJ_MIG_TABLE WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL) C,
           DBA_PART_INDEXES D
	 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TABLE_NAME
	   AND B.INDEX_TYPE='NORMAL'
	   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
       AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
       AND B.OWNER = D.OWNER(+)
       AND B.INDEX_NAME = D.INDEX_NAME(+)
	 GROUP 
		BY B.TABLE_NAME,
		   B.INDEX_NAME,
		   B.UNIQUENESS,
           D.TABLE_NAME,
           D.DEF_TABLESPACE_NAME,
           B.TABLESPACE_NAME,
           C.DEGREE
	) ;      

SELECT COUNT(*)  -- 1161
FROM 
(
SELECT 'ALTER TABLE ADM_USER.'||TABLE_NAME||' ADD CONSTRAINT '||CONSTRAINT_NAME||' PRIMARY KEY '||PK_SQL||';'
FROM
(
SELECT B.TABLE_NAME,
       B.CONSTRAINT_NAME,
       '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS PK_SQL
  FROM DBA_IND_COLUMNS A,
       DBA_CONSTRAINTS B,
       MIG_USER.MSJ_MIG_TABLE C
 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TOBE_TABLE_NAME
   AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
   AND B.CONSTRAINT_TYPE='P'
   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
 GROUP 
    BY B.TABLE_NAME,
       B.CONSTRAINT_NAME
)       
);

TRUNCATE TABLE MSJ_MIG_PK;
INSERT INTO MSJ_MIG_PK  -- 1161
SELECT TABLE_NAME,CONSTRAINT_NAME,'ALTER TABLE ADM_USER.'||TABLE_NAME||' ADD CONSTRAINT '||CONSTRAINT_NAME||' PRIMARY KEY '||PK_SQL
FROM
(
SELECT B.TABLE_NAME,
       B.CONSTRAINT_NAME,
       '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS PK_SQL
  FROM DBA_IND_COLUMNS A,
       DBA_CONSTRAINTS B,
       MIG_USER.MSJ_MIG_TABLE C
 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TOBE_TABLE_NAME
   AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
   AND B.CONSTRAINT_TYPE='P'
   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
 GROUP 
    BY B.TABLE_NAME,
       B.CONSTRAINT_NAME
);

/*
SELECT 'ALTER TABLE ADM_USER.'||TABLE_NAME||' ADD CONSTRAINT '||CONSTRAINT_NAME||' PRIMARY KEY '||PK_SQL||';'
FROM
(
SELECT B.TABLE_NAME,
       B.CONSTRAINT_NAME,
       '('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME) ORDER BY A.COLUMN_POSITION).EXTRACT('//text()').GETCLOBVAL(),2)||')' AS PK_SQL
  FROM DBA_IND_COLUMNS A,
       DBA_CONSTRAINTS B,
       MIG_USER.MSJ_MIG_TABLE C
 WHERE B.OWNER='ADM_USER' AND B.TABLE_NAME = C.TOBE_TABLE_NAME
   AND (C.MIG_TYPE IN ('A','B','C') OR C.MIG_TYPE IS NULL)
   AND B.CONSTRAINT_TYPE='P'
   AND B.OWNER = A.INDEX_OWNER AND B.INDEX_NAME = A.INDEX_NAME
 GROUP 
    BY B.TABLE_NAME,
       B.CONSTRAINT_NAME
);
*/
SELECT COUNT(*)  FROM MSJ_MIG_INDEX ;
SELECT COUNT(*)  FROM MSJ_MIG_INDEX_LOG;

SELECT COUNT(*) 
  FROM DBA_INDEXES 
 WHERE TABLE_NAME IN (SELECT TABLE_NAME 
						FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL) 
   AND OWNER ='ADM_USER' 
   AND INDEX_TYPE < > 'LOB' ;    
--1484


SELECT COUNT(*)  FROM MSJ_MIG_PK ;
SELECT COUNT(DISTINCT INDEX_NAME ) FROM MSJ_PK_COLUMN;  --  1161 
SELECT COUNT(*) 
  FROM DBA_CONSTRAINTS 
 WHERE TABLE_NAME IN (SELECT TABLE_NAME 
						FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL) 
   AND OWNER ='ADM_USER' 
   AND CONSTRAINT_TYPE='P'; 
--1162

/*==============================================================================================================*/

SELECT 'TRUNCATE TABLE ADM_USER.'||TABLE_NAME||';' 
  FROM DBA_TABLES 
 WHERE OWNER ='ADM_USER' 
   AND TABLE_NAME IN (SELECT TOBE_TABLE_NAME      
                        FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE (MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL));
					   
/* INDEX PK 백업 */
SELECT 'ALTER TABLE ADM_USER.'||TABLE_NAME||' DROP PRIMARY KEY;' 
  FROM DBA_CONSTRAINTS 
 WHERE OWNER='ADM_USER' 
   AND CONSTRAINT_TYPE='P' 
   AND TABLE_NAME IN (SELECT TOBE_TABLE_NAME 
                        FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE (MIG_TYPE IN ('A') OR MIG_TYPE IS NULL));
					   
/* PK COLUMN NOT NULL CHECK */
SELECT * 
  FROM DBA_TAB_COLUMNS 
 WHERE OWNER ='ADM_USER' 
   AND (TABLE_NAME,COLUMN_NAME) IN (SELECT TABLE_NAME,COLUMN_NAME 
                                      FROM MIG_USER.MSJ_PK_COLUMN ) 
   AND NULLABLE ='Y';

SELECT 'DROP INDEX ADM_USER.'||INDEX_NAME||';'     
  FROM DBA_INDEXES 
 WHERE OWNER='ADM_USER' 
   AND TABLE_NAME IN (SELECT TOBE_TABLE_NAME 
                        FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE (MIG_TYPE IN ('A') OR MIG_TYPE IS NULL)) 
   AND INDEX_TYPE < >'LOB';

DELETE FROM MSJ_MIG_JOB_LOG;
INSERT INTO MSJ_MIG_JOB_LOG(TABLE_NAME) SELECT TABLE_NAME FROM MSJ_MIG_TABLE WHERE MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL;
COMMIT;


SELECT 'ALTER TRIGGER '||OWNER||'.'||TRIGGER_NAME||' DISABLE;' 
  FROM DBA_TRIGGERS 
 WHERE OWNER='ADM_USER';

SELECT 'ALTER TABLE ADM_USER.'||TABLE_NAME||' NOLOGGING;' 
  FROM DBA_TABLES 
 WHERE OWNER ='ADM_USER' 
   AND TABLE_NAME IN (SELECT TABLE_NAME 
                        FROM MIG_USER.MSJ_MIG_TABLE 
					   WHERE (MIG_TYPE IN ('A','B','C') OR MIG_TYPE IS NULL));