/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE TABLE PMPBMIG.MSJ_MIG_RULE
(
    TABLE_NAME          VARCHAR2(128) NOT NULL,
    TOBE_TABLE_NAME     VARCHAR2(128) NOT NULL,
    ASIS_COLUMN_NAME    VARCHAR2(128) NOT NULL,
    TOBE_COLUMN_NAME    VARCHAR2(128) NOT NULL
)
TABLESPACE TS_PMPBMIG_D01
NOCOMPRESS;


GRANT ALTER,DELETE,INDEX,INSERT,SELECT,FLASHBACK,REFERENCES,READ,ON COMMIT REFRESH,QUERY REWRITE,DEBUG,UPDATE ON PMPBMIG.MSJ_MIG_RULE TO PMPBADM;