/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE PMPBMIG.PR_MIG_FETCH
(
  I_INST_ID NUMBER
)  
IS
  MIG_SQL           VARCHAR2(32767);       
  MIG_TABLE_NAME    VARCHAR2(4000);
  
  CURSOR CUR1 IS
  SELECT TABLE_NAME,
       ' INSERT /*+ APPEND '||CASE WHEN DEGREE > 1 THEN 'PARALLEL('||TABLE_NAME ||' '||DEGREE||')' ELSE '' END  ||' */ INTO '||TABLE_NAME||'('||SUBSTR(XMLAGG(XMLELEMENT(COLUMN_NAME,',',COLUMN_NAME)
         ORDER BY COLUMN_ID).EXTRACT('//text()').GETCLOBVAL(),2)||')'||CHR(13)||CHR(10)||
       ' SELECT /*+ FULL(B) '||CASE WHEN DEGREE > 1 THEN 'PARALLEL(B '||DEGREE||')' ELSE '' END  ||' */'||SUBSTR(XMLAGG(XMLELEMENT(ASIS_COLUMN_NAME,',',ASIS_COLUMN_NAME)
         ORDER BY COLUMN_ID).EXTRACT('//text()').GETSTRINGVAL(),2)||
       ' FROM '||OWNER||'.'||TABLE_NAME||CASE WHEN I_INST_ID <  5 THEN '@DL_PUSET1_OGG' ELSE '@DL_PUSET2_OGG' END ||' B '||MIG_SQL
  FROM (    
        SELECT /*+ LEADING(B A C) */
               B.OWNER,A.TABLE_NAME,A.COLUMN_NAME,NVL(C.ASIS_COLUMN_NAME,A.COLUMN_NAME) ASIS_COLUMN_NAME,A.COLUMN_ID,B.MIG_SQL,B.DEGREE
          FROM DBA_TAB_COLUMNS A,PMPBMIG.MSJ_MIG_TABLE B,PMPBMIG.MSJ_MIG_RULE C
         WHERE A.OWNER ='PMPBADM'
           AND A.TABLE_NAME = B.TABLE_NAME
           AND (B.MIG_TYPE = 'A' OR B.MIG_TYPE IS NULL)
           AND B.INST_ID = I_INST_ID
           AND A.TABLE_NAME = C.TABLE_NAME(+)
           AND A.COLUMN_NAME = C.TOBE_COLUMN_NAME(+)
       )
  GROUP BY OWNER,TABLE_NAME,MIG_SQL,DEGREE ;

BEGIN  
  OPEN CUR1;
      LOOP
          FETCH CUR1 INTO MIG_TABLE_NAME,MIG_SQL;
          EXIT WHEN CUR1%NOTFOUND; 
          PMPBMIG.PR_MIG_INSERT(MIG_TABLE_NAME,MIG_SQL);
          --EXIT WHEN CUR1%NOTFOUND;
      END LOOP;
  CLOSE CUR1;
 
END PR_MIG_FETCH;
/