/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE PMPBMIG.PR_MIG_CREATE_PK
(
    V_TABLE_NAME     IN VARCHAR2,
    V_CREATE_PK_SQL  IN VARCHAR2
)    
IS

  MIG_PK_RESULT   VARCHAR2(4000);
  
BEGIN  

    EXECUTE IMMEDIATE V_CREATE_PK_SQL ;
    
EXCEPTION
   WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('PK ERROR SQL:'||V_CREATE_PK_SQL);
    NULL;
END PR_MIG_CREATE_PK;
/