/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE PMPBMIG.PR_MIG_ALTER_TABLE_INDEX
(
  I_INST_ID NUMBER
)  
IS
  MIG_SQL  VARCHAR2(32767);       
  
  CURSOR CUR1 IS
    SELECT DISTINCT 'ALTER TABLE PMPBADM.'||TABLE_NAME||' LOGGING' AS V_SQL
      FROM MSJ_MIG_TABLE
     WHERE INST_ID = I_INST_ID
     UNION ALL
    SELECT DISTINCT 'ALTER INDEX PMPBADM.'||INDEX_NAME||' NOPARALLEL LOGGING' 
      FROM DBA_INDEXES A,
           MSJ_MIG_TABLE B
     WHERE B.INST_ID = I_INST_ID
       AND B.TABLE_NAME = A.TABLE_NAME
       AND A.INDEX_TYPE < > 'LOB';

BEGIN  
  OPEN CUR1;
      LOOP
          FETCH CUR1 INTO MIG_SQL;
            EXIT WHEN CUR1%NOTFOUND; 
            EXECUTE IMMEDIATE MIG_SQL ;
      END LOOP;
  CLOSE CUR1;
 
END PR_MIG_ALTER_TABLE_INDEX;
/