/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE PMPBMIG.PR_MIG_INDEX_FETCH
(
  I_INST_ID NUMBER
)  
IS
  MIG_CREATE_INDEX_SQL  VARCHAR2(32767);       
  MIG_TABLE_NAME        VARCHAR2(4000);
  MIG_INDEX_NAME        VARCHAR2(4000);   
  
  CURSOR CUR1 IS
  SELECT DISTINCT A.TABLE_NAME,A.INDEX_NAME,A.INDEX_SQL 
    FROM MSJ_MIG_INDEX A , MSJ_MIG_TABLE B
   WHERE B.INST_ID=I_INST_ID  
     AND (B.MIG_TYPE ='A' OR B.MIG_TYPE IS NULL)
     AND B.TABLE_NAME = A.TABLE_NAME; 

BEGIN  
  OPEN CUR1;
      LOOP
          FETCH CUR1 INTO MIG_TABLE_NAME,MIG_INDEX_NAME,MIG_CREATE_INDEX_SQL;
          EXIT WHEN CUR1%NOTFOUND; 
          PMPBMIG.PR_MIG_CREATE_INDEX(MIG_TABLE_NAME,MIG_INDEX_NAME,MIG_CREATE_INDEX_SQL);
          --EXIT WHEN CUR1%NOTFOUND;
      END LOOP;
  CLOSE CUR1;
 
END PR_MIG_INDEX_FETCH;
/