/*
* 용도       : PNP정산시스템 고도화 프로젝트
* 생성자     : 문성진 부장님
* 저장일     : 2022-01-25
*/

CREATE OR REPLACE PROCEDURE PMPBMIG.PR_MIG_INSERT
(
    V_TABLE_NAME  IN VARCHAR2,
    V_MIG_SQL     IN VARCHAR2
)    
IS
  MIG_INSERT_COUNT  NUMBER(15);     
  MIG_SQL           VARCHAR2(32767);       
  MIG_TABLE_NAME    VARCHAR2(4000);
  MIG_RESULT        VARCHAR2(4000);
  
BEGIN  

    EXECUTE IMMEDIATE 'ALTER SESSION SET WORKAREA_SIZE_POLICY=MANUAL';
    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DML';
    EXECUTE IMMEDIATE 'ALTER SESSION ENABLE PARALLEL DDL';
    EXECUTE IMMEDIATE 'ALTER SESSION SET SORT_AREA_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET HASH_AREA_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET SORT_AREA_RETAINED_SIZE=512000000';
    EXECUTE IMMEDIATE 'ALTER SESSION SET HASH_MULTIBLOCK_IO_COUNT=128';
    EXECUTE IMMEDIATE 'ALTER SESSION SET DB_FILE_MULTIBLOCK_READ_COUNT=128';

    UPDATE PMPBMIG.MSJ_MIG_JOB_LOG SET MIG_START_DT = SYSDATE WHERE TABLE_NAME = V_TABLE_NAME AND MIG_START_DT IS NULL;
    COMMIT;
    --DBMS_OUTPUT.PUT_LINE('INSERT TABLE_NAME:'||V_TABLE_NAME);
    EXECUTE IMMEDIATE V_MIG_SQL ;
    MIG_INSERT_COUNT := SQL%ROWCOUNT;
    MIG_RESULT       := SQLERRM ;
    UPDATE PMPBMIG.MSJ_MIG_JOB_LOG SET MIG_END_DT = SYSDATE,MIG_COUNT=NVL(MIG_COUNT,0) + MIG_INSERT_COUNT,JOB_RESULT='SUCCESS' WHERE TABLE_NAME = V_TABLE_NAME;
    COMMIT;
EXCEPTION
   WHEN OTHERS THEN
    ROLLBACK;
    MIG_RESULT   :=  SQLERRM(SQLCODE) ;
    UPDATE PMPBMIG.MSJ_MIG_JOB_LOG SET MIG_END_DT = SYSDATE,MIG_COUNT=-999,JOB_RESULT='FAIL:'||MIG_RESULT WHERE TABLE_NAME = V_TABLE_NAME;
    COMMIT;
END PR_MIG_INSERT;
/