DROP SCHEMA ERPAPP;
DROP SCHEMA INORG;
DROP SCHEMA ERPHRRT;
DROP SCHEMA FLYWAY;
DROP SCHEMA SAC;

CREATE SCHEMA PRD_PORTAL;
CREATE SCHEMA PRD_LGC;
CREATE SCHEMA PRD_LGCNS;
CREATE SCHEMA PRD_LGES;

USE PRD_PORTAL;
CREATE TABLE `CM_HEALTH_CHK_LOG` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '서비스아이디',
  `MENU_URL` varchar(300) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '서비스URL',
  `MENU_CD` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '메뉴코드',
  `ARGUMENT_TEXT` varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '데이타',
  `EXEC_START_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행시작시각',
  `EXEC_END_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행종료시각',
  `TIME_GAP` decimal(22,3) DEFAULT NULL COMMENT '타임갭초단위',
  `RESULT_STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '상태',
  `RESULT_MESSAGE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '결과메시지',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자',
  `CRT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '생성시각',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자',
  `UPDT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '변경시각',
  `ATTR1` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성1',
  `ATTR2` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성2',
  `ATTR3` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성3',
  `ATTR4` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성4',
  `ATTR5` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성5',
  `ATTR6` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성6',
  `ATTR7` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성7',
  `ATTR8` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성8',
  `ATTR9` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성9',
  `ATTR10` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성10',
  `ATTR11` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성11',
  `ATTR12` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성12',
  `ATTR13` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성13',
  `ATTR14` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성14',
  `ATTR15` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성15',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '유저아이피',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`),
  KEY `CM_HEALTH_CHK_LOG_N03` (`TIME_GAP`),
  KEY `CM_HEALTH_CHK_LOG_N01` (`SERVICE_ID`) USING BTREE,
  KEY `CM_HEALTH_CHK_LOG_N02` (`EXEC_START_DT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=661041 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='health check';

CREATE TABLE `CM_USER_LOGIN` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` decimal(22,0) NOT NULL COMMENT '유저아이디',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유저아이피',
  `BROWSER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브라우저 종류',
  `LOGIN_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인 방식',
  `LOGIN_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '로그인일시',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자아이디',
  `CRT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '생성일시',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자아이디',
  `UPDT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '변경일시',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사용자_로그인';

USE PRD_LGC;
CREATE TABLE `CM_HEALTH_CHK_LOG` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '서비스아이디',
  `MENU_URL` varchar(300) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '서비스URL',
  `MENU_CD` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '메뉴코드',
  `ARGUMENT_TEXT` varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '데이타',
  `EXEC_START_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행시작시각',
  `EXEC_END_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행종료시각',
  `TIME_GAP` decimal(22,3) DEFAULT NULL COMMENT '타임갭초단위',
  `RESULT_STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '상태',
  `RESULT_MESSAGE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '결과메시지',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자',
  `CRT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '생성시각',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자',
  `UPDT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '변경시각',
  `ATTR1` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성1',
  `ATTR2` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성2',
  `ATTR3` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성3',
  `ATTR4` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성4',
  `ATTR5` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성5',
  `ATTR6` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성6',
  `ATTR7` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성7',
  `ATTR8` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성8',
  `ATTR9` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성9',
  `ATTR10` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성10',
  `ATTR11` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성11',
  `ATTR12` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성12',
  `ATTR13` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성13',
  `ATTR14` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성14',
  `ATTR15` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성15',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '유저아이피',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`),
  KEY `CM_HEALTH_CHK_LOG_N03` (`TIME_GAP`),
  KEY `CM_HEALTH_CHK_LOG_N01` (`SERVICE_ID`) USING BTREE,
  KEY `CM_HEALTH_CHK_LOG_N02` (`EXEC_START_DT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=661041 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='health check';

CREATE TABLE `CM_USER_LOGIN` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` decimal(22,0) NOT NULL COMMENT '유저아이디',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유저아이피',
  `BROWSER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브라우저 종류',
  `LOGIN_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인 방식',
  `LOGIN_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '로그인일시',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자아이디',
  `CRT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '생성일시',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자아이디',
  `UPDT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '변경일시',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사용자_로그인';

USE PRD_LGES;
CREATE TABLE `CM_HEALTH_CHK_LOG` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '서비스아이디',
  `MENU_URL` varchar(300) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '서비스URL',
  `MENU_CD` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '메뉴코드',
  `ARGUMENT_TEXT` varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '데이타',
  `EXEC_START_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행시작시각',
  `EXEC_END_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행종료시각',
  `TIME_GAP` decimal(22,3) DEFAULT NULL COMMENT '타임갭초단위',
  `RESULT_STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '상태',
  `RESULT_MESSAGE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '결과메시지',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자',
  `CRT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '생성시각',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자',
  `UPDT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '변경시각',
  `ATTR1` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성1',
  `ATTR2` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성2',
  `ATTR3` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성3',
  `ATTR4` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성4',
  `ATTR5` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성5',
  `ATTR6` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성6',
  `ATTR7` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성7',
  `ATTR8` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성8',
  `ATTR9` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성9',
  `ATTR10` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성10',
  `ATTR11` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성11',
  `ATTR12` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성12',
  `ATTR13` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성13',
  `ATTR14` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성14',
  `ATTR15` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성15',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '유저아이피',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`),
  KEY `CM_HEALTH_CHK_LOG_N03` (`TIME_GAP`),
  KEY `CM_HEALTH_CHK_LOG_N01` (`SERVICE_ID`) USING BTREE,
  KEY `CM_HEALTH_CHK_LOG_N02` (`EXEC_START_DT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=661041 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='health check';

CREATE TABLE `CM_USER_LOGIN` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` decimal(22,0) NOT NULL COMMENT '유저아이디',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유저아이피',
  `BROWSER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브라우저 종류',
  `LOGIN_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인 방식',
  `LOGIN_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '로그인일시',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자아이디',
  `CRT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '생성일시',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자아이디',
  `UPDT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '변경일시',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사용자_로그인';

USE PRD_LGCNS;
CREATE TABLE `CM_HEALTH_CHK_LOG` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '서비스아이디',
  `MENU_URL` varchar(300) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '서비스URL',
  `MENU_CD` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '메뉴코드',
  `ARGUMENT_TEXT` varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '데이타',
  `EXEC_START_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행시작시각',
  `EXEC_END_DT` varchar(17) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '실행종료시각',
  `TIME_GAP` decimal(22,3) DEFAULT NULL COMMENT '타임갭초단위',
  `RESULT_STATUS` varchar(1) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '상태',
  `RESULT_MESSAGE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '결과메시지',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자',
  `CRT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '생성시각',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자',
  `UPDT_DT` varchar(14) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '변경시각',
  `ATTR1` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성1',
  `ATTR2` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성2',
  `ATTR3` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성3',
  `ATTR4` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성4',
  `ATTR5` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성5',
  `ATTR6` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성6',
  `ATTR7` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성7',
  `ATTR8` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성8',
  `ATTR9` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성9',
  `ATTR10` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성10',
  `ATTR11` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성11',
  `ATTR12` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성12',
  `ATTR13` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성13',
  `ATTR14` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성14',
  `ATTR15` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '예비속성15',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '유저아이피',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`),
  KEY `CM_HEALTH_CHK_LOG_N03` (`TIME_GAP`),
  KEY `CM_HEALTH_CHK_LOG_N01` (`SERVICE_ID`) USING BTREE,
  KEY `CM_HEALTH_CHK_LOG_N02` (`EXEC_START_DT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=661041 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='health check';

CREATE TABLE `CM_USER_LOGIN` (
  `AUTO_INC_SEQ_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` decimal(22,0) NOT NULL COMMENT '유저아이디',
  `CLIENT_IP` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '유저아이피',
  `BROWSER_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '브라우저 종류',
  `LOGIN_TYPE` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '로그인 방식',
  `LOGIN_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '로그인일시',
  `CRT_ID` decimal(22,0) NOT NULL COMMENT '생성자아이디',
  `CRT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '생성일시',
  `UPDT_ID` decimal(22,0) NOT NULL COMMENT '변경자아이디',
  `UPDT_DT` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '변경일시',
  PRIMARY KEY (`AUTO_INC_SEQ_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16981 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='사용자_로그인';
