DESC INFORMATION_SCHEMA.TABLES;
DESC INFORMATION_SCHEMA.COLUMNS;
DESC INFORMATION_SCHEMA.PARTITIONS;
DESC INFORMATION_SCHEMA.STATISTICS;
DESC INFORMATION_SCHEMA.ROUTINES;
DESC INFORMATION_SCHEMA.TRIGGERS;
DESC INFORMATION_SCHEMA.VIEWS;
DESC INFORMATION_SCHEMA.SCHEMATA;
DESC INFORMATION_SCHEMA.INNODB_TABLES;
DESC INFORMATION_SCHEMA.INNODB_TABLESPACES;
DESC INFORMATION_SCHEMA.INNODB_INDEXES;

USE STG_PORTAL;
CREATE TABLE `TABLES` (
    TABLE_CATALOG	varchar(64) NOT NULL
  , TABLE_SCHEMA	varchar(64) NOT NULL
  , TABLE_NAME	varchar(64) NOT NULL
  , TABLE_TYPE	enum('BASE TABLE','VIEW','SYSTEM VIEW') NOT NULL
  , ENGINE	varchar(64)
  , VERSION	int(2)
  , ROW_FORMAT	enum('Fixed','Dynamic','Compressed','Redundant','Compact','Paged')
  , TABLE_ROWS	bigint(21) unsigned
  , AVG_ROW_LENGTH	bigint(21) unsigned
  , DATA_LENGTH	bigint(21) unsigned
  , MAX_DATA_LENGTH	bigint(21) unsigned
  , INDEX_LENGTH	bigint(21) unsigned
  , DATA_FREE	bigint(21) unsigned
  , AUTO_INCREMENT	bigint(21) unsigned
  , CREATE_TIME	timestamp NOT NULL
  , UPDATE_TIME	datetime
  , CHECK_TIME	datetime
  , TABLE_COLLATION	varchar(64)
  , CHECKSUM	bigint(21)
  , CREATE_OPTIONS	varchar(256)
  , TABLE_COMMENT	text
  , PRIMARY KEY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.TABLES';

CREATE TABLE `COLUMNS` (
    TABLE_CATALOG	varchar(64) NOT NULL
  , TABLE_SCHEMA	varchar(64) NOT NULL
  , TABLE_NAME	varchar(64) NOT NULL
  , COLUMN_NAME	varchar(64)
  , ORDINAL_POSITION	int(10) unsigned NOT NULL
  , COLUMN_DEFAULT	text
  , IS_NULLABLE	varchar(3) NOT NULL
  , DATA_TYPE	longtext
  , CHARACTER_MAXIMUM_LENGTH	bigint(21)
  , CHARACTER_OCTET_LENGTH	bigint(21)
  , NUMERIC_PRECISION	bigint(10) unsigned
  , NUMERIC_SCALE	bigint(10) unsigned
  , DATETIME_PRECISION	int(10) unsigned
  , CHARACTER_SET_NAME	varchar(64)
  , COLLATION_NAME	varchar(64)
  , COLUMN_TYPE	mediumtext NOT NULL
  , COLUMN_KEY	enum('','PRI','UNI','MUL') NOT NULL
  , EXTRA	varchar(256)
  , PRIVILEGES	varchar(154)
  , COLUMN_COMMENT	text NOT NULL
  , GENERATION_EXPRESSION	longtext NOT NULL
  , SRS_ID	int(10) unsigned
  , PRIMARY KEY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.COLUMNS';

CREATE TABLE `PARTITIONS` (
    TABLE_CATALOG	varchar(64) NOT NULL
  , TABLE_SCHEMA	varchar(64) NOT NULL
  , TABLE_NAME	varchar(64) NOT NULL
  , PARTITION_NAME	varchar(64)
  , SUBPARTITION_NAME	varchar(64)
  , PARTITION_ORDINAL_POSITION	int(6) unsigned
  , SUBPARTITION_ORDINAL_POSITION	int(6) unsigned
  , PARTITION_METHOD	varchar(13)
  , SUBPARTITION_METHOD	varchar(13)
  , PARTITION_EXPRESSION	varchar(2048)
  , SUBPARTITION_EXPRESSION	varchar(2048)
  , PARTITION_DESCRIPTION	text
  , TABLE_ROWS	bigint(21) unsigned
  , AVG_ROW_LENGTH	bigint(21) unsigned
  , DATA_LENGTH	bigint(21) unsigned
  , MAX_DATA_LENGTH	bigint(21) unsigned
  , INDEX_LENGTH	bigint(21) unsigned
  , DATA_FREE	bigint(21) unsigned
  , CREATE_TIME	timestamp NOT NULL
  , UPDATE_TIME	datetime
  , CHECK_TIME	datetime
  , CHECKSUM	bigint(21)
  , PARTITION_COMMENT	text NOT NULL
  , NODEGROUP	varchar(256)
  , TABLESPACE_NAME	varchar(268)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.PARTITIONS';

CREATE TABLE `STATISTICS` (
    TABLE_CATALOG	varchar(64) NOT NULL
  , TABLE_SCHEMA	varchar(64) NOT NULL
  , TABLE_NAME	varchar(64) NOT NULL
  , NON_UNIQUE	int(1) NOT NULL
  , INDEX_SCHEMA	varchar(64) NOT NULL
  , INDEX_NAME	varchar(64)
  , SEQ_IN_INDEX	int(10) unsigned NOT NULL
  , COLUMN_NAME	varchar(64)
  , COLLATION	varchar(1)
  , CARDINALITY	bigint(21)
  , SUB_PART	bigint(21)
  , PACKED	binary(0)
  , NULLABLE	varchar(3) NOT NULL
  , INDEX_TYPE	varchar(11) NOT NULL
  , COMMENT	varchar(8) NOT NULL
  , INDEX_COMMENT	varchar(2048) NOT NULL
  , IS_VISIBLE	varchar(3) NOT NULL
  , EXPRESSION	longtext
  , PRIMARY KEY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, NON_UNIQUE, INDEX_SCHEMA, SEQ_IN_INDEX, INDEX_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.STATISTICS';

CREATE TABLE `ROUTINES` (
    SPECIFIC_NAME	varchar(64) NOT NULL
  , ROUTINE_CATALOG	varchar(64) NOT NULL
  , ROUTINE_SCHEMA	varchar(64) NOT NULL
  , ROUTINE_NAME	varchar(64) NOT NULL
  , ROUTINE_TYPE	enum('FUNCTION','PROCEDURE') NOT NULL
  , DATA_TYPE	longtext
  , CHARACTER_MAXIMUM_LENGTH	bigint(21)
  , CHARACTER_OCTET_LENGTH	bigint(21)
  , NUMERIC_PRECISION	int(10) unsigned
  , NUMERIC_SCALE	int(10) unsigned
  , DATETIME_PRECISION	int(10) unsigned
  , CHARACTER_SET_NAME	varchar(64)
  , COLLATION_NAME	varchar(64)
  , DTD_IDENTIFIER	longtext
  , ROUTINE_BODY	varchar(3) NOT NULL
  , ROUTINE_DEFINITION	longtext
  , EXTERNAL_NAME	binary(0)
  , EXTERNAL_LANGUAGE	varchar(64) NOT NULL
  , PARAMETER_STYLE	varchar(3) NOT NULL
  , IS_DETERMINISTIC	varchar(3) NOT NULL
  , SQL_DATA_ACCESS	enum('CONTAINS SQL','NO SQL','READS SQL DATA','MODIFIES SQL DATA') NOT NULL
  , SQL_PATH	binary(0)
  , SECURITY_TYPE	enum('DEFAULT','INVOKER','DEFINER') NOT NULL
  , CREATED	timestamp NOT NULL
  , LAST_ALTERED	timestamp NOT NULL
  , SQL_MODE	set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL') NOT NULL
  , ROUTINE_COMMENT	text NOT NULL
  , DEFINER	varchar(288) NOT NULL
  , CHARACTER_SET_CLIENT	varchar(64) NOT NULL
  , COLLATION_CONNECTION	varchar(64) NOT NULL
  , DATABASE_COLLATION	varchar(64) NOT NULL
  , PRIMARY KEY (ROUTINE_CATALOG, ROUTINE_SCHEMA, ROUTINE_NAME, ROUTINE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.ROUTINES';

CREATE TABLE `TRIGGERS` (
    TRIGGER_CATALOG	varchar(64)	 NOT NULL
  , TRIGGER_SCHEMA	varchar(64)	 NOT NULL
  , TRIGGER_NAME	varchar(64)	 NOT NULL
  , EVENT_MANIPULATION	enum('INSERT','UPDATE','DELETE')	 NOT NULL
  , EVENT_OBJECT_CATALOG	varchar(64)	 NOT NULL
  , EVENT_OBJECT_SCHEMA	varchar(64)	 NOT NULL
  , EVENT_OBJECT_TABLE	varchar(64)	 NOT NULL
  , ACTION_ORDER	int(10) unsigned	 NOT NULL
  , ACTION_CONDITION	binary(0)	
  , ACTION_STATEMENT	longtext	 NOT NULL
  , ACTION_ORIENTATION	varchar(3)	 NOT NULL
  , ACTION_TIMING	enum('BEFORE','AFTER')	 NOT NULL
  , ACTION_REFERENCE_OLD_TABLE	binary(0)	
  , ACTION_REFERENCE_NEW_TABLE	binary(0)	
  , ACTION_REFERENCE_OLD_ROW	varchar(3)	 NOT NULL
  , ACTION_REFERENCE_NEW_ROW	varchar(3)	 NOT NULL
  , CREATED	timestamp(2)	 NOT NULL
  , SQL_MODE	set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL')	 NOT NULL
  , DEFINER	varchar(288)	 NOT NULL
  , CHARACTER_SET_CLIENT	varchar(64)	 NOT NULL
  , COLLATION_CONNECTION	varchar(64)	 NOT NULL
  , DATABASE_COLLATION	varchar(64)	 NOT NULL
  , PRIMARY KEY (TRIGGER_CATALOG, TRIGGER_SCHEMA, TRIGGER_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.TRIGGERS';

CREATE TABLE `VIEWS` (
    TABLE_CATALOG	varchar(64)	NOT NULL
  , TABLE_SCHEMA	varchar(64)	NOT NULL
  , TABLE_NAME	varchar(64)	NOT NULL
  , VIEW_DEFINITION	longtext	
  , CHECK_OPTION	enum('NONE','LOCAL','CASCADED')	
  , IS_UPDATABLE	enum('NO','YES')	
  , DEFINER	varchar(288)	
  , SECURITY_TYPE	varchar(7)	
  , CHARACTER_SET_CLIENT	varchar(64)	NOT NULL
  , COLLATION_CONNECTION	varchar(64)	NOT NULL
  , PRIMARY KEY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.VIEWS';

CREATE TABLE `SCHEMATA` (
    CATALOG_NAME	varchar(64)	NOT NULL
  , SCHEMA_NAME	varchar(64)	NOT NULL
  , DEFAULT_CHARACTER_SET_NAME	varchar(64)	NOT NULL
  , DEFAULT_COLLATION_NAME	varchar(64)	NOT NULL
  , SQL_PATH	binary(0)
  , DEFAULT_ENCRYPTION	enum('NO','YES')	NOT NULL
  , PRIMARY KEY (CATALOG_NAME, SCHEMA_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.SCHEMATA';

CREATE TABLE `INNODB_TABLES` (
    TABLE_ID	bigint(21) unsigned	NOT NULL
  , NAME	varchar(655)	NOT NULL
  , FLAG	int(11)	NOT NULL
  , N_COLS	int(11)	NOT NULL
  , SPACE	bigint(21)	NOT NULL
  , ROW_FORMAT	varchar(12)
  , ZIP_PAGE_SIZE	int(11) unsigned	NOT NULL
  , SPACE_TYPE	varchar(10)
  , INSTANT_COLS	int(11)	NOT NULL
  , PRIMARY KEY (TABLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.INNODB_TABLES';

CREATE TABLE `INNODB_TABLESPACES` (
    SPACE	int(11) unsigned	 NOT NULL
  , NAME	varchar(655)	 NOT NULL
  , FLAG	int(11) unsigned	NOT NULL
  , ROW_FORMAT	varchar(22)
  , PAGE_SIZE	int(11) unsigned	NOT NULL
  , ZIP_PAGE_SIZE	int(11) unsigned	NOT NULL
  , SPACE_TYPE	varchar(10)
  , FS_BLOCK_SIZE	int(11) unsigned	NOT NULL
  , FILE_SIZE	bigint(21) unsigned	NOT NULL
  , ALLOCATED_SIZE	bigint(21) unsigned	NOT NULL
  , SERVER_VERSION	varchar(10)
  , SPACE_VERSION	int(11) unsigned	NOT NULL
  , ENCRYPTION	varchar(1)
  , STATE	varchar(10)
  , PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.INNODB_TABLESPACES';

CREATE TABLE `INNODB_INDEXES` (
    INDEX_ID	bigint(21) unsigned	NOT NULL
  , NAME	varchar(193)	NOT NULL
  , TABLE_ID	bigint(21) unsigned	NOT NULL
  , TYPE	int(11)	NOT NULL
  , N_FIELDS	int(11)	NOT NULL
  , PAGE_NO	int(11)	NOT NULL
  , SPACE	int(11)	NOT NULL
  , MERGE_THRESHOLD	int(11)	NOT NULL
  , PRIMARY KEY (TABLE_ID, INDEX_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='INFORMATION_SCHEMA.INNODB_INDEXES';

SELECT * FROM STG_PORTAL.TABLES;
SELECT * FROM STG_PORTAL.COLUMNS;
SELECT * FROM STG_PORTAL.PARTITIONS;
SELECT * FROM STG_PORTAL.STATISTICS;
SELECT * FROM STG_PORTAL.ROUTINES;
SELECT * FROM STG_PORTAL.TRIGGERS;
SELECT * FROM STG_PORTAL.VIEWS;
SELECT * FROM STG_PORTAL.SCHEMATA;
SELECT * FROM STG_PORTAL.INNODB_TABLES;
SELECT * FROM STG_PORTAL.INNODB_TABLESPACES;
SELECT * FROM STG_PORTAL.INNODB_INDEXES;


INSERT INTO STG_PORTAL.COLUMNS SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
INSERT INTO STG_PORTAL.PARTITIONS SELECT * FROM INFORMATION_SCHEMA.PARTITIONS;
INSERT INTO STG_PORTAL.STATISTICS SELECT * FROM INFORMATION_SCHEMA.STATISTICS;
INSERT INTO STG_PORTAL.ROUTINES SELECT * FROM INFORMATION_SCHEMA.ROUTINES;
INSERT INTO STG_PORTAL.TRIGGERS SELECT * FROM INFORMATION_SCHEMA.TRIGGERS;
INSERT INTO STG_PORTAL.VIEWS SELECT * FROM INFORMATION_SCHEMA.VIEWS;
INSERT INTO STG_PORTAL.SCHEMATA SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
INSERT INTO STG_PORTAL.INNODB_TABLES SELECT * FROM INFORMATION_SCHEMA.INNODB_TABLES;
INSERT INTO STG_PORTAL.INNODB_TABLESPACES SELECT * FROM INFORMATION_SCHEMA.INNODB_TABLESPACES;
INSERT INTO STG_PORTAL.INNODB_INDEXES SELECT * FROM INFORMATION_SCHEMA.INNODB_INDEXES;

TRUNCATE TABLE STG_PORTAL.TABLES;
TRUNCATE TABLE STG_PORTAL.COLUMNS;
TRUNCATE TABLE STG_PORTAL.PARTITIONS;
TRUNCATE TABLE STG_PORTAL.STATISTICS;
TRUNCATE TABLE STG_PORTAL.ROUTINES;
TRUNCATE TABLE STG_PORTAL.TRIGGERS;
TRUNCATE TABLE STG_PORTAL.VIEWS;
TRUNCATE TABLE STG_PORTAL.SCHEMATA;
TRUNCATE TABLE STG_PORTAL.INNODB_TABLES;
TRUNCATE TABLE STG_PORTAL.INNODB_TABLESPACES;
TRUNCATE TABLE STG_PORTAL.INNODB_INDEXES;