TTITLE "[DBname] Database|Oracle ASM Diskgroup"

SET LINESIZE 250
SET PAGESIZE 1000
SET HEADING ON

COL GROUP#                  FORMAT 99
COL NAME                    FORMAT A10
COL SECTOR_SIZE             FORMAT 999,999
COL LOGICAL_SECTOR_SIZE     FORMAT 999,999
COL BLOCK_SIZE              FORMAT 999,999
COL ALLOCATION_UNIT_SIZE    FORMAT 999,999,999
COL STATE                   FORMAT A10
COL TYPE                    FORMAT A8
COL TOTAL_GB                FORMAT 999,999
COL FREE_GB                 FORMAT 999,999
COL HOT_USED_GB             FORMAT 999,999
COL COLD_USED_GB            FORMAT 999,999
COL REQUIRED_MIRROR_FREE_GB FORMAT 999,999
COL USABLE_FILE_GB          FORMAT 999,999
COL OFFLINE_DISKS           FORMAT 999,999
COL COMPATIBILITY           FORMAT A20
COL DATABASE_COMPATIBILITY  FORMAT A20
COL VOTE_FILES              FORMAT A10

SELECT GROUP_NUMBER GROUP#
     , NAME
     , SECTOR_SIZE
     , LOGICAL_SECTOR_SIZE
     , BLOCK_SIZE
     , ALLOCATION_UNIT_SIZE
     , STATE
     , TYPE
     , TOTAL_MB/1024 TOTAL_GB
     , FREE_MB/1024 FREE_GB
     , HOT_USED_MB/1024 HOT_USED_GB
     , COLD_USED_MB/1024 COLD_USED_GB
     , REQUIRED_MIRROR_FREE_MB/1024 REQUIRED_MIRROR_FREE_GB
     , USABLE_FILE_MB/1024 USABLE_FILE_GB
     , OFFLINE_DISKS
--     , COMPATIBILITY
--     , DATABASE_COMPATIBILITY
     , VOTING_FILES VOTE_FILES
  FROM V$ASM_DISKGROUP;
  
TTITLE OFF


/*
CREATE DISKGROUP DG_TEST EXTERNAL REDUNDANCY DISK '/disk/path/';
DROP DISKGROUP DG_TEST [INCLUDING CONTENTS];
ALTER DISKGROUP DG_TEST DISMOUNT;
ALTER DISKGROUP DG_TEST MOUNT;
*/