SET LINESIZE 250
SET PAGESIZE 100
SET HEADING ON

COL STATUS FORMAT A8
COL NAME FORMAT A50
COL IS_RECOVERY_DEST_FILE FORMAT A21
COL BLOCK_SIZE FORMAT 9999999
COL FILE_SIZE_BLKS FORMAT 99999
COL CON_ID FORMAT 99

SELECT STATUS
     , NAME
	 , IS_RECOVERY_DEST_FILE
	 , BLOCK_SIZE
	 , FILE_SIZE_BLKS
	 , CON_ID
  FROM V$CONTROLFILE;
  
TTITLE OFF
  
/*
SELECT * FROM V$CONTROLFILE_RECORD_SECTION;
*/