cat << 'EOF' > df.sql
TTITLE "[DBName] Database|Oracle Data Files";

SET PAGESIZE 500
SET LINESIZE 200
SET HEADING ON

COL TS_NAME FORMAT A15
COL FILE_NAME FORMAT A40
COL TOTAL_MB FORMAT 999,999
COL USED_MB FORMAT 999,999
COL FREE_MB FORMAT 999,999
COL USED_PCT FORMAT 999.99
COL AUTOEXTENSIBLE FORMAT A15
COL "RESIZE_DDL (USED_PCT >= 90%)" FORMAT A80

SELECT DF.TABLESPACE_NAME AS TS_NAME
     , DF.FILE_NAME
	 , ROUND(DF.BYTES/1024/1024) AS TOTAL_MB
	 , NVL(ROUND(USEDBYTES/1024/1024),0) AS USED_MB
	 , NVL(ROUND(FREEBYTES/1024/1024), 0) AS FREE_MB
	 , TO_CHAR(NVL(ROUND((USEDBYTES)/DF.BYTES * 100), 0),'fm990D00','NLS_NUMERIC_CHARACTERS = ''.,''') || '%' AS USED_PCT
	 , DF.AUTOEXTENSIBLE
     , CASE WHEN NVL(ROUND((USEDBYTES)/DF.BYTES * 100), 0) >= 90 THEN 'ALTER DATABASE DATAFILE ''' || DF.FILE_NAME || ''' RESIZE 30G;'
            ELSE NULL
	   END AS "RESIZE_DDL (USED_PCT >= 90%)"
  FROM DBA_DATA_FILES DF
  LEFT OUTER JOIN ( SELECT FILE_ID, SUM(BYTES) USEDBYTES FROM DBA_EXTENTS GROUP BY FILE_ID) EXT
    ON DF.FILE_ID = EXT.FILE_ID
  LEFT OUTER JOIN (SELECT FILE_ID, SUM(BYTES) FREEBYTES FROM DBA_FREE_SPACE GROUP BY FILE_ID) FREE
    ON DF.FILE_ID = FREE.FILE_ID
 UNION ALL
SELECT TF.TABLESPACE_NAME AS TS_NAME
     , TF.FILE_NAME
	 , ROUND(TF.BYTES/1024/1024) AS TOTAL_MB
	 , NVL(ROUND(USEDBYTES/1024/1024),0) AS USED_MB
	 , NVL(ROUND(FREEBYTES/1024/1024), 0) AS FREE_MB
	 , TO_CHAR(NVL(ROUND((USEDBYTES)/TF.BYTES * 100), 0),'fm990D00','NLS_NUMERIC_CHARACTERS = ''.,''') || '%' AS USED_PCT
	 , TF.AUTOEXTENSIBLE
     , CASE WHEN NVL(ROUND((USEDBYTES)/TF.BYTES * 100), 0) >= 90 THEN 'ALTER DATABASE TEMPFILE ''' || TF.FILE_NAME || ''' RESIZE 30G;'
            ELSE NULL
	   END AS "RESIZE_DDL (USED_PCT >= 90%)"
  FROM DBA_TEMP_FILES TF
  LEFT OUTER JOIN ( SELECT FILE_ID, SUM(BYTES) USEDBYTES FROM DBA_EXTENTS GROUP BY FILE_ID) EXT
    ON TF.FILE_ID = EXT.FILE_ID
  LEFT OUTER JOIN (SELECT FILE_ID, SUM(BYTES) FREEBYTES FROM DBA_FREE_SPACE GROUP BY FILE_ID) FREE
    ON TF.FILE_ID = FREE.FILE_ID
 ORDER BY 1,2;

TTITLE OFF

EOF
