TTITLE "[DBName] Database|Oracle Top Events";

SET LINESIZE 200
SET PAGESIZE 1000
SET HEADING ON

COL EVENT FOR A60
SELECT EVENT
     , COUNT(*)
  FROM GV$SESSION
 GROUP BY EVENT
 ORDER BY 2 DESC;

TTITLE OFF


/*
TTITLE "[DBName] Database|Oracle Top Session Events"
SET LINESIZE 200
SET PAGESZIE 1000
SET HEADING ON
COL INST_ID FOR 999
COL SID FOR 99999999
COL EVENT FOR A40
COL TOTAL_WAITS FOR 999,999,999
COL TOTAL_TIMEOUTS FOR 999,999,999
COL TIME_WAITED FOR 999,999,999
COL AVERAGE_WAIT FOR 999,999,999
COL MAX_WAIT FOR 999,999,999
COL TIME_WAITED_MICRO FOR 999,999,999
COL EVENT_ID FOR 999999999999
COL WAIT_CLASS_ID FOR 999,999,999
COL WAIT_CLASS# FOR 999,999,999
COL WAIT_CLASS FOR A20
COL CON_ID FOR 999
SELECT INST_ID
     , SID
     , EVENT
     , TOTAL_WAITS
     , TOTAL_TIMEOUTS
     , TIME_WAITED
     , AVERAGE_WAIT
     , MAX_WAIT
     -- , TIME_WAITED_MICRO
     , EVENT_ID
     -- , WAIT_CLASS_ID
     -- , WAIT_CLASS#
     , WAIT_CLASS
     -- , CON_ID
  FROM GV$SESSION_EVENT
 WHERE 1=1
   AND WAIT_CLASS <> 'Idle'
   AND SID = 1
 ORDER BY TIME_WAITED DESC
;
TTITLE OFF

SELECT EVENT
     ,TOTAL_WAITS
     ,TOTAL_TIMEOUTS
     ,TIME_WAITED
     ,AVERAGE_WAIT
     ,TIME_WAITED_MICRO
     ,TOTAL_WAITS_FG
     ,TOTAL_TIMEOUTS_FG
     ,TIME_WAITED_FG
     ,AVERAGE_WAIT_FG
     ,TIME_WAITED_MICRO_FG
     ,EVENT_ID
     ,WAIT_CLASS_ID
     ,WAIT_CLASS#
     ,WAIT_CLASS
     ,CON_ID
  FROM GV$SYSTEM_EVENT;
*/