SET LINES 200 PAGES 1000
COL NAME FOR A50
COL DESC FOR A70
COL CURR_VAL FOR A10
COL DEF_VAL FOR A10
COL DEF_TF FOR A10

SELECT A.KSPPINM NAME
     , A.KSPPDESC "DESC"
	 , B.KSPPSTVL CURR_VAL
	 , B.KSPPSTDFL DEF_VAL
	 , B.KSPPSTDF DEF_TF
  FROM X$KSPPI A, X$KSSPPCV B
 WHERE A.INDX = B.INDX
   AND A.KSPPINM LIKE '%%';