TTITLE "[DBname] Database|Oracle Scheduler Job Log"

SET LINESIZE 250
SET PAGESIZE 1000
SET HEADING ON

COL LOG_ID            FORMAT 999999
COL LOG_DATE          FORMAT A19
COL OWNER             FORMAT A12
COL JOB_NAME          FORMAT A30
COL JOB_CLASS         FORMAT A20
COL OPERATION         FORMAT A10
COL STATUS            FORMAT A10
COL ACTUAL_START_DATE FORMAT A19
COL CPU_USED          FORMAT A16
COL INST#             FORMAT 99
COL SESSION_ID        FORMAT A12
COL ADDITIONAL_INFO   FORMAT A80
COL OUTPUT            FORMAT A40
COL ERRORS            FORMAT A10

SELECT *
  FROM (SELECT A.LOG_ID
             , TO_CHAR(A.LOG_DATE, 'YYYY/MM/DD HH24:MM:SS') LOG_DATE
			 , B.CPU_USED
             , A.STATUS
             , A.OPERATION
             , A.OWNER
             , A.JOB_NAME
--             , A.JOB_SUBNAME
--             , A.JOB_CLASS
             , B.INSTANCE_ID AS INST#
--             , TO_CHAR(B.REQ_START_DATE, 'YYYY/MM/DD HH24:MM:SS') AS REQ_START_DATE
--             , TO_CHAR(B.ACTUAL_START_DATE, 'YYYY/MM/DD HH24:MM:SS') AS ACTUAL_START_DATE
--             , B.SESSION_ID
             , SUBSTR(A.ADDITIONAL_INFO, 1, 80) AS ADDITIONAL_INFO
             , SUBSTR(B.OUTPUT, 1, 40) AS OUTPUT
--             , B.ERROR#
             , SUBSTR(B.ERRORS, 1, 10) AS ERRORS
          FROM DBA_SCHEDULER_JOB_LOG A
             , DBA_SCHEDULER_JOB_RUN_DETAILS B
         WHERE A.LOG_ID = B.LOG_ID (+)
--           AND A.STATUS < > 'SUCCEEDED'
         ORDER BY A.LOG_DATE DESC ) A
 WHERE ROWNUM < = 100 
;

TTITLE OFF