TTITLE "[DBname] Database|Oracle Redo Log Status"

SET LINESIZE 250
SET PAGESIZE 1000
SET HEADING ON
COL INST_ID FORMAT 999
COL GROUP# FORMAT 99
COL THREAD# FORMAT 99
COL SEQ# FORMAT 99999
COL MB FORMAT 9999
COL ARCHIVED FORMAT A10
COL LOG_STAT FORMAT A10
COL FIRST_CHANGE# FORMAT 9999999999999999999
COL FIRST_TIME FORMAT A19
COL NEXT_CHANGE# FORMAT 9999999999999999999
COL NEXT_TIME FORMAT A19
COL MEMBER_STAT FORMAT A15
COL TYPE FORMAT A7
COL MEMBER FORMAT A50
COL IS_RECOVERY_DEST_FILE FORMAT A15

SELECT A.INST_ID
     , A.GROUP#
     , A.THREAD#
     , A.SEQUENCE# AS SEQ#
     , A.BYTES/1024/1024 MB
--     , A.BLOCKSIZE
--     , A.MEMBERS
     , A.ARCHIVED
     , A.STATUS AS LOG_STAT
     -- , A.FIRST_CHANGE#
     -- , TO_CHAR(A.FIRST_TIME,'YYYY/MM/DD HH24:MM:SS') FIRST_TIME
     -- , A.NEXT_CHANGE#
     -- , TO_CHAR(A.NEXT_TIME,'YYYY/MM/DD HH24:MM:SS') NEXT_TIME
     , B.STATUS AS MEMBER_STAT
     , B.TYPE
     , B.MEMBER
--     , B.IS_RECOVERY_DEST_FILE
  FROM GV$LOG A
     , GV$LOGFILE B
 WHERE A.GROUP# = B.GROUP#
   AND A.INST_ID = B.INST_ID
 ORDER BY A.INST_ID, A.GROUP#, A.THREAD#, A.SEQUENCE#, B.MEMBER;
 
TTITLE OFF
 
/*
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM CHECKPOINT;

SELECT * FROM GV$LOG_HISTORY;
SELECT * FROM GV$ARCHIVED_LOG;
*/