TTITLE "[DBName] Database|Oracle SQL Monitor"

SET PAGESIZE 1000
SET LINESIZE 200
SET HEADING ON
COL INST# FORMAT 9
COL SQL_ID FORMAT A15
COL REPORT_ID FORMAT 999999999
COL STATUS FORMAT A20
COL USERNAME FORMAT A12
COL MODULE FORMAT A20
COL PROGRAM FORMAT A15
COL FIRST_REFRESH_TIME FORMAT A19
COL LAST_REFRESH_TIME FORMAT A19
COL ELAPSED_SEC FORMAT 999999.99
COL CPU_SEC FORMAT 999999.99
COL REPORT_QRY FORMAT A150

SELECT INST_ID AS INST#
     , SQL_ID
     , REPORT_ID
     , STATUS
     , USERNAME
     , SUBSTR(MODULE, 1, 20) AS MODULE
     , SUBSTR(PROGRAM, 1, 15) AS PROGRAM
     , TO_CHAR(FIRST_REFRESH_TIME, 'YYYY/MM/DD HH24:MM:SS') AS FIRST_REFRESH_TIME
     , TO_CHAR(LAST_REFRESH_TIME, 'YYYY/MM/DD HH24:MM:SS') AS LAST_REFRESH_TIME
--     , REFRESH_COUNT
     , ROUND(ELAPSED_TIME / 1000 / 1000, 2) AS ELAPSED_SEC
     , ROUND(CPU_TIME / 1000 / 1000, 2) AS CPU_SEC
--     , ROUND(QUEUING_TIME / 1000 / 1000, 2) AS QUEUING_SEC
--     , 'SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(SQL_ID=>''' || SQL_ID || ''', EVENT_DETAIL=>''YES'', TYPE=>''TEXT'', REPORT_LEVEL=>''ALL-SQL_TEXT'') FROM DUAL;' AS REPORT_QRY
  FROM GV$SQL_MONITOR
 WHERE USERNAME LIKE '%%'
--   AND SQL_TEXT LIKE '%QUERY_IDENTIFIER%'
 ORDER BY LAST_REFRESH_TIME
;

TTITLE OFF

SELECT 
       'SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(SQL_ID=>''' || SQL_ID || ''', EVENT_DETAIL=>''YES'', TYPE=>''TEXT'', REPORT_LEVEL=>''ALL-SQL_TEXT'') AS REPORT FROM DUAL;' AS REPORT_QRY
  FROM GV$SQL_MONITOR
 WHERE USERNAME LIKE '%%'
--   AND SQL_TEXT LIKE '%QUERY_IDENTIFIER%'
 ORDER BY LAST_REFRESH_TIME
;

SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET LINESIZE 250
SET PAGESIZE 0
SET TRIM ON
SET TRIMSPOOL ON
SET ECHO OFF
SET FEEDBACK OFF