TTITLE "[DBName] Database|Oracle Check Table Statistics"

SET PAGESIZE 1000
SET LINESIZE 400
SET HEADING ON
COL OWNER FORMAT A10
COL TABLE_NAME FORMAT A35
COL TS_NAME FORMAT A15
COL PART_NAME FORMAT A10
COL PART_POS FORMAT 999
COL SUBPART_NAME FORMAT A16
COL SUBPART_POS FORMAT 999
COL OBJ_TYPE FORMAT A12
COL LAST_ANALYZED FORMAT A19
COL GATHER_STATS_DDL FORMAT A250

SELECT 
       OWNER
     , TABLE_NAME
     , PARTITION_NAME AS PART_NAME
     , PARTITION_POSITION AS PART_POS
     , SUBPARTITION_NAME AS SUBPART_NAME
     , SUBPARTITION_POSITION AS SUBPART_POS
     , OBJECT_TYPE AS OBJ_TYPE
     , TO_CHAR(LAST_ANALYZED, 'YYYY/MM/DD HH24:MM:SS') AS LAST_ANALYZED
--       DECODE(OBJECT_TYPE, 'TABLE', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''ALL'', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);'
--                         , 'PARTITION', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''PARTITION'', PARTNAME=>''' || PARTITION_NAME || ''', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);'
--                         , 'SUBPARTITION', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''SUBPARTITION'', PARTNAME=>''' || SUBPARTITION_NAME || ''', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);' 
--       ) GATHER_STATS_DDL
  FROM DBA_TAB_STATISTICS
 WHERE 1=1
   AND OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LAST_ANALYZED IS NULL
   AND OBJECT_TYPE = 'TABLE'
 ORDER BY OWNER, TABLE_NAME, DECODE(OBJECT_TYPE, 'TABLE', 1, 'PARTITION', 2, 'SUBPARTITION', 3), PARTITION_NAME, SUBPARTITION_NAME;


SELECT 
--       OWNER
--     , TABLE_NAME
--     , PARTITION_NAME AS PART_NAME
--     , PARTITION_POSITION AS PART_POS
--     , SUBPARTITION_NAME AS SUBPART_NAME
--     , SUBPARTITION_POSITION AS SUBPART_POS
--     , OBJECT_TYPE AS OBJ_TYPE
--     , TO_CHAR(LAST_ANALYZED, 'YYYY/MM/DD HH24:MM:SS') AS LAST_ANALYZED
       DECODE(OBJECT_TYPE, 'TABLE', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''ALL'', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);'
                         , 'PARTITION', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''PARTITION'', PARTNAME=>''' || PARTITION_NAME || ''', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);'
                         , 'SUBPARTITION', 'EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>''' || OWNER || ''', TABNAME=>''' || TABLE_NAME || ''', GRANULARITY=>''SUBPARTITION'', PARTNAME=>''' || SUBPARTITION_NAME || ''', DEGREE=>8, CASCADE=>TRUE, METHOD_OPT=>''FOR ALL COLUMNS SIZE 1'', NO_INVALIDATE=>FALSE, ESTIMATE_PERCENT=>DBMS_STATS.AUTO_SAMPLE_SIZE);' 
       ) GATHER_STATS_DDL
  FROM DBA_TAB_STATISTICS
 WHERE 1=1
   AND OWNER IN ('PMPBADM', 'BLCP01ADM', 'BLCP02ADM', 'BLCP03ADM', 'BLCP04ADM', 'BLCP05ADM', 'BLCP06ADM', 'BLCP07ADM', 'BLCP08ADM', 'BLCP09ADM', 'BLCP10ADM')
   AND LAST_ANALYZED IS NULL
   AND OBJECT_TYPE = 'TABLE'
 ORDER BY OWNER, TABLE_NAME, DECODE(OBJECT_TYPE, 'TABLE', 1, 'PARTITION', 2, 'SUBPARTITION', 3), PARTITION_NAME, SUBPARTITION_NAME;