TTITLE "[DBname] Database|Oracle Undo Status"

SET LINESIZE 250
SET PAGESIZE 2000
SET HEADING ON
COL INST_ID FORMAT 999
COL BEGIN_TIME FORMAT A19
COL END_TIME FORMAT A19
COL UNDOTSN FORMAT 999999
COL UNDOBLKS FORMAT 999999
COL TXNCOUNT FORMAT 999999
COL MAXQUERYLEN FORMAT 999999
COL MAXQUERYID FORMAT A13
COL MAXCONCURRENCY FORMAT 999999
COL UNXPSTEALCNT FORMAT 999999
COL UNXPBLKRELCNT FORMAT 999999
COL UNXPBLKREUCNT FORMAT 999999
COL EXPSTEALCNT FORMAT 999999
COL EXPBLKRELCNT FORMAT 999999
COL EXPBLKREUCNT FORMAT 999999
COL SSOLDERRCNT FORMAT 999999
COL NOSPACEERRCNT FORMAT 999999
COL ACTIVEBLKS FORMAT 999999
COL UNEXPIREDBLKS FORMAT 999999
COL EXPIREDBLKS FORMAT 999999
COL TUNED_UNDORETENTION FORMAT 999999

SELECT INST_ID
     , TO_CHAR(BEGIN_TIME,'YYYY/MM/DD HH24:MM:SS') BEGIN_TIME
     , TO_CHAR(END_TIME,'YYYY/MM/DD HH24:MM:SS') END_TIME
     , UNDOTSN
     , UNDOBLKS
     , TXNCOUNT
     , MAXQUERYLEN
     , MAXQUERYID
     , MAXCONCURRENCY
     , UNXPSTEALCNT
     , UNXPBLKRELCNT
     , UNXPBLKREUCNT
     , EXPSTEALCNT
     , EXPBLKRELCNT
     , EXPBLKREUCNT
     , SSOLDERRCNT
     , NOSPACEERRCNT
--     , ACTIVEBLKS
--     , UNEXPIREDBLKS
--     , EXPIREDBLKS
     , TUNED_UNDORETENTION
  FROM GV$UNDOSTAT
 ORDER BY INST_ID, BEGIN_TIME, END_TIME;
 
TTITLE OFF
 
/*
SELECT * FROM DBA_HIST_UNDOSTAT;
*/