-- 테이블별로 분류해서 집계한 잠금 종류별 대기 시간 통계 정보 확인
SELECT object_type
     , object_schema
     , object_name
     , count_star
     , sum_timer_wait
     , min_timer_wait
     , avg_timer_wait
     , max_timer_wait
     , count_read
     , sum_timer_read
     , min_timer_read
     , avg_timer_read
     , max_timer_read
     , count_write
     , sum_timer_write
     , min_timer_write
     , avg_timer_write
     , max_timer_write
     , count_read_normal
     , sum_timer_read_normal
     , min_timer_read_normal
     , avg_timer_read_normal
     , max_timer_read_normal
     , count_read_with_shared_locks
     , sum_timer_read_with_shared_locks
     , min_timer_read_with_shared_locks
     , avg_timer_read_with_shared_locks
     , max_timer_read_with_shared_locks
     , count_read_high_priority
     , sum_timer_read_high_priority
     , min_timer_read_high_priority
     , avg_timer_read_high_priority
     , max_timer_read_high_priority
     , count_read_no_insert
     , sum_timer_read_no_insert
     , min_timer_read_no_insert
     , avg_timer_read_no_insert
     , max_timer_read_no_insert
     , count_read_external
     , sum_timer_read_external
     , min_timer_read_external
     , avg_timer_read_external
     , max_timer_read_external
     , count_write_allow_write
     , sum_timer_write_allow_write
     , min_timer_write_allow_write
     , avg_timer_write_allow_write
     , max_timer_write_allow_write
     , count_write_concurrent_insert
     , sum_timer_write_concurrent_insert
     , min_timer_write_concurrent_insert
     , avg_timer_write_concurrent_insert
     , max_timer_write_concurrent_insert
     , count_write_low_priority
     , sum_timer_write_low_priority
     , min_timer_write_low_priority
     , avg_timer_write_low_priority
     , max_timer_write_low_priority
     , count_write_normal
     , sum_timer_write_normal
     , min_timer_write_normal
     , avg_timer_write_normal
     , max_timer_write_normal
     , count_write_external
     , sum_timer_write_external
     , min_timer_write_external
     , avg_timer_write_external
     , max_timer_write_external
  FROM performance_schema.table_lock_waits_summary_by_table;