-- SHOW PROCESSLIST;
-- SHOW FULL PROCESSLIST;

SELECT ID
     , USER
     , HOST
     , DB
     , COMMAND
     , TIME AS TIME_SEC
     , TIME / 60 / 60 AS TIME_HOURS
     , STATE
     , CONCAT('KILL ', ID, ';') AS KILL_CMD
     , INFO
  FROM INFORMATION_SCHEMA.PROCESSLIST
 WHERE 1=1
   AND COMMAND <> 'SLEEP'
   AND HOST NOT LIKE '10.65.60.10%' -- my IP
   AND USER NOT IN ('SYSTEM USER', 'EVENT_SCHEDULER')
 ORDER BY TIME DESC
;

-- VIEW CONNECTION COUNT
SELECT USER
     , COUNT(1) CONN_CNT
     , MAX(TIME) / 60 / 60 TIME_HOURS
  FROM INFORMATION_SCHEMA.PROCESSLIST
 WHERE 1=1
   AND USER NOT IN ('SYSTEM USER', 'EVENT_SCHEDULER')
 GROUP BY USER
 ORDER BY USER
;