-- SHOW PROCESSLIST;
-- SHOW FULL PROCESSLIST;

SELECT ID
     , USER
     , HOST
     , DB
     , COMMAND
     , TIME
     , STATE
     , CONCAT('KILL ', ID, ';') AS KILL_CMD
     , INFO
  FROM INFORMATION_SCHEMA.PROCESSLIST
 WHERE 1=1
   AND COMMAND <> 'SLEEP'
   AND HOST NOT LIKE '10.65.60.10%' -- my IP
   AND USER NOT IN ('SYSTEM USER', 'EVENT_SCHEDULER');